Repository MTES-MCT/trackdechets, pull requests merged in 2023-07, with the labels that each got.

#2516 Fixes featureflags dependencies
  front/src/common/contexts/FeatureFlagsContext.tsx
  front/src/layout/LayoutContainer.tsx
Labels: ready for review

#2509 [Snyk] Upgrade prisma from 4.12.0 to 4.15.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2532 [Bug] Il ne devrait pas être possible de s'inscrire avec une adresse mail mal formattée (caractères spéciaux)
  front/src/login/Signup.tsx
Labels: ready for review

#2510 [Snyk] Upgrade pg from 8.5.1 to 8.11.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2511 [Snyk] Upgrade helmet from 6.0.1 to 6.2.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2512 [Snyk] Upgrade mongodb from 4.10.0 to 4.16.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2530 BUG Front V2 - tonne vs Kg pour les fluides / [Dashboard] V2 - Page Révision - Afficher le poids du bsd
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/WasteDetails/WasteDetails.tsx
  front/src/Apps/Dashboard/Components/WasteDetails/wasteDetails.scss
  front/src/Apps/Dashboard/Components/WasteDetails/wasteTypes.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  front/src/common/components/Icons.tsx
Labels: ready for review

#2508 [Snyk] Upgrade @prisma/client from 4.12.0 to 4.15.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2523 [Refonte] Pages - Transporteur affichage des bsd dans l'onglet et rebrancher les boutons d'action
  front/public/icons/dashboard/custom-info-icon.svg
  front/public/icons/dashboard/transporter-number-plate-icon.svg
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActions.test.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/InfoWithIcon.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconTypes.ts
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconUtils.ts
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/Components/DropdownMenu/DropdownMenu.tsx
  front/src/Apps/common/hooks/useOnClickOutsideRefTarget.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/Apps/common/types/commonTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Pages/Dashboard.tsx
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/BSDDActions.tsx
  front/src/dashboard/components/BSDList/BSDD/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/BSDaActions.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/BSDasriActions.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasriSecretCode.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/BsffActions.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterCustomInfo.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/BSVhuActions.tsx
  front/src/dashboard/components/BSDList/RoadControlButton.tsx
Labels: ready for review

#2531 [TRA-1108] BSFF - API : permettre de filtrer les BSFFS sur le numéro SIRET du détenteur initial
  Changelog.md
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/queries/__tests__/bsffs.integration.ts
  back/src/bsffs/typeDefs/bsff.inputs.graphql
  back/src/bsffs/where.ts
Labels: ready for review

#2484 Add zod parsing for envs
  back/prisma/scripts/set-contacts.ts
  back/src/__tests__/errors.integration.ts
  back/src/bsds/indexation/bulkIndexBsds.ts
  back/src/common/middlewares/__tests__/errorHandler.test.ts
  back/src/common/pdf/pdf.ts
  back/src/common/repository/helper.ts
  back/src/companies/sirene/trackdechets/client.ts
  back/src/cron.ts
  back/src/env.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/validation.ts
  back/src/index.ts
  back/src/mailer/backends/consoleBackend.ts
  back/src/mailer/backends/sendInBlueBackend.ts
  back/src/mailer/index.ts
  back/src/mailer/templates/provider/templateIds.ts
  back/src/prisma.ts
  back/src/queue/consumerIndexation.ts
  back/src/queue/producers/mail.ts
  back/src/server.ts
  back/src/utils.ts
Labels: ready for review

#2496 [tra-10736] - Glitch d'auto remplissage
  front/src/form/bsda/stepper/steps/Emitter.tsx
Labels: ready for review

#2495 Tra-10736 - Ajout d'un entreposage provisoire
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/validate.ts
  front/src/form/bsda/FormContainer.tsx
Labels: ready for review

#2460 [TRA-10073] ETQ entreprise je peux transporter des déchets sans être TRANSPORTER (si exemption de récépissé)
  Changelog.md
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/schema.ts
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsffs/__tests__/validation.integration.ts
  back/src/bsvhu/__tests__/validation.integration.ts
  back/src/common/validation.ts
  back/src/common/validation/siret.ts
  back/src/forms/__tests__/validation.integration.ts
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/dashboard/DashboardTabs.tsx
  front/src/dashboard/transport/hooks/useShowTransportTabs.ts
Labels: ready for review

#2478 Auto Empty string
  back/src/bsda/converter.ts
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/schema.ts
  back/src/common/converter.ts
Labels: ready for review

#2115 Adds an info box for producers
  front/src/account/AccountCompanyAddProducer.tsx
Labels: ready for review

#2529 [tra-11793] BSDA - Checks sur les workers
  back/src/common/validation/siret.ts
  back/src/companies/__tests__/search.test.ts
  back/src/companies/resolvers/queries/favorites.ts
  back/src/companies/search.ts
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/companies/validation.ts
  front/src/form/bsda/stepper/steps/Worker.tsx
  front/src/form/common/components/company/CompanySelector.tsx
  front/src/form/common/components/company/query.ts
Labels: ready for review

#2549 [TRA-10976] Corrige le wording du transport de ses propres déchets
  front/src/account/AccountCompanyAddProducer.tsx
Labels: ready for review

#2556 Page transport refonte : cta controle routier devient un bouton primaire (fix recette)
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActions.test.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2585 [TRA-12375] Introduction des comptes gouvernementaux pour remplacer le champ `isRegistreNational`
  Changelog.md
  back/prisma/migrations/148_add_government_account.sql
  back/prisma/schema.prisma
  back/prisma/scripts/createGovernementAccounts.ts
  back/prisma/scripts/denormalize-dasris-grouping.ts
  back/src/__tests__/factories.ts
  back/src/env.ts
  back/src/registry/permissions.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/incomingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/managedWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/outgoingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/transportedWastes.integration.ts
  back/src/registry/resolvers/queries/incomingWastes.ts
  back/src/registry/resolvers/queries/managedWastes.ts
  back/src/registry/resolvers/queries/outgoingWastes.ts
  back/src/registry/resolvers/queries/transportedWastes.ts
Labels: ready for review

#2594 [Dashboard]V2 - Filtres batch #2 - Front
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/DatePicker/DatePickerWrapper.tsx
  front/src/Apps/common/Components/Filters/Filters.tsx
  front/src/Apps/common/Components/Filters/filters.scss
  front/src/Apps/common/Components/Filters/filters.test.tsx
  front/src/Apps/common/Components/Filters/filtersTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review

#2595 Page transport refonte - Fix action primaire controle routier
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
Labels: ready for review

#2568 Page transport refonte : [fix] annexe 1 btn signer et faire signer cas ou le transporteur peux signer a la place de l'emetteur
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/bsdCardListTypes.ts
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/company/query.ts
  front/src/Pages/Dashboard.tsx
  front/src/account/accountCompanyAdd/AccountCompanyAddSiret.tsx
  front/src/account/fields/forms/AccountFormCompanySignatureAutomation.tsx
  front/src/dashboard/components/BSDList/BSDCards/BSDCards.tsx
  front/src/dashboard/components/BSDList/BSDD/index.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bsdd/Emitter.tsx
  front/src/form/bsdd/utils/schema.ts
  front/src/form/common/components/company/CompanySelector.tsx
  front/src/form/common/components/company/TransporterReceipt.tsx
Labels: ready for review

#2599 Simplify telemetry
  back/package-lock.json
  back/package.json
  back/src/prisma.ts
  back/src/tracer.ts
Labels: ready for review

#2601 [tra-12420] Message d'erreur incompréhensible dans le formulaire BSFF
  Changelog.md
  front/src/common/validation/schema.ts
Labels: ready for review

#2561 [TRA-12023] Harmonisation coordonnées géographiques BSDD en cas de terres
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  front/src/form/bsdd/components/parcel-number/ParcelNumber.tsx
Labels: ready for review

#2603 Ajout de routes de profiling
  back/package-lock.json
  back/package.json
  back/src/index.ts
  back/src/logging/heapSnapshot.ts
Labels: ready for review

#2589 [TRA-12285] Annexe 1: une seule entrée d'immatriculation pour les bordereaux enfants + chapeau
  back/src/forms/resolvers/mutations/__tests__/signTransportForm.integration.ts
  back/src/forms/resolvers/mutations/signTransportForm.ts
Labels: ready for review

#2587 [TRA-12361] Rewording pour la création d'une entreprise avec le profil Transporteur
  front/src/account/accountCompanyAdd/AccountCompanyAddTransporterReceipt.tsx
Labels: bug, ready for review

#2597 [Bugfix] Correction des messages d'erreur à la sélection d'une entreprise de travaux sur les BSDA
  front/src/form/bsda/stepper/steps/Worker.tsx
Labels: bug, ready for review

#2596 TRA-12219 - Correctif - Impossible d'enlever la présence de POP via la révision
  Changelog.md
  front/src/dashboard/components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/request/ReviewableField.tsx
Labels: bug, ready for review

#2584 Fix BSDA update transporter receipt, clean frontend
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  front/src/form/bsda/stepper/steps/Transporter.tsx
Labels: ready for review

#2604 Replace toArray by streams for mongodb activity-events
  back/src/activity-events/data.ts
  back/src/activity-events/dataloader.ts
  back/src/events/mongodb.ts
Labels: ready for review
