Repository MTES-MCT/trackdechets, pull requests merged in 2023-06, with the labels that each got.

#2328 [TRA-11664] Ajout des rôles Chauffeur et Lecteur en DB
  Changelog.md
  back/prisma/migrations/142_add_new_roles.sql
  back/prisma/schema.prisma
  back/src/bsda/permissions.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEcoorganismeEmissionWithSecretCode.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEmission.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEmissionWithSecretCode.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriTransport.integration.ts
  back/src/bsdasris/resolvers/mutations/sign.ts
  back/src/bsdasris/resolvers/mutations/signBsdasri.ts
  back/src/bsdasris/resolvers/mutations/signBsdasriEmissionWithSecretCode.ts
  back/src/bsdasris/resolvers/mutations/signatureUtils.ts
  back/src/bsdasris/workflow/dasriTransition.ts
  back/src/bsdasris/workflow/machine.ts
  back/src/bsdasris/workflow/types.ts
  back/src/bsffs/permissions.ts
  back/src/bsffs/resolvers/mutations/__tests__/signBsff.integration.ts
  back/src/bsffs/resolvers/mutations/signBsff.ts
  back/src/bsvhu/permissions.ts
  back/src/bsvhu/resolvers/mutations/sign.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/forms/permissions.ts
  back/src/permissions.ts
  back/src/users/resolvers/queries/invitation.ts
Labels: ready for review

#2430 Github actions upgrades
  .github/workflows/build-and-test.yml
  .github/workflows/deploy.yml
Labels: ready for review

#2442 Rend le lien vers les dasris associés plus visible
  front/src/dashboard/detail/bsdasri/BsdasriDetailContent.tsx
Labels: ready for review

#2429 [TRA-8972] Recette - Adds wording to gerep field
  front/src/account/AccountCompanyAdd.tsx
Labels: ready for review

#2451 [TRA-11952] Updates React-Aria
  front/package-lock.json
  front/package.json
Labels: ready for review

#2446 fix Affichage Recepissé pour Bsdasri de synthèse
  front/src/form/bsdasri/steps/Transporter.tsx
  front/src/form/bsdasri/steps/Type.tsx
Labels: ready for review

#2469 Dashboard V2 - Bug d'orientation d'un bsdasri à signer par un transporteur - pas de bouton primaire dans 'à collecter'
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsdaValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsvhuValidation.test.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignWork.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
Labels: ready for review

#2471 Obfuscate invited user names
  Changelog.md
  back/src/__tests__/factories.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/mailer/templates/mustache/notification-invitation.html
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.integration.ts
  back/src/users/resolvers/mutations/__tests__/sendMembershipRequest.integration.ts
  back/src/users/resolvers/queries/__tests__/myCompanies.integration.ts
Labels: ready for review

#2431 [TRA-10538] Harmonisation des inputs & validations de dates sur les étapes de signature des bordereaux
  Changelog.md
  back/src/bsda/resolvers/mutations/publish.ts
  back/src/bsdasris/resolvers/mutations/signBsdasri.ts
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ReceivedInfo.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignWork.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/utils.ts
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignAcceptation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignReception.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
  front/src/form/bsda/stepper/steps/Operation.tsx
  front/src/form/bsdasri/steps/Transport.tsx
  front/src/form/bsvhu/Operation.tsx
Labels: ready for review

#2453 Amélioration du test `duplicateBsda.integration.ts`
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
Labels: ready for review

#2441 V2 - Page Révision affichage des bdx et boutons d'action
  front/src/Apps/Dashboard/Components/Badge/Badge.tsx
  front/src/Apps/Dashboard/Components/Badge/badge.scss
  front/src/Apps/Dashboard/Components/Badge/badgeTypes.ts
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActions.test.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/bsdCardList.scss
  front/src/Apps/Dashboard/Components/BsdCardList/bsdCardListTypes.ts
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/reviews/BsdaReviewQuery.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Pages/Dashboard.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaCancelRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaConsultRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddCancelRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddConsultRevision.tsx
  front/src/layout/Header.module.scss
  front/src/layout/Header.tsx
Labels: ready for review

#2472 Annexe 1 - Améliorations diverses
  back/src/__tests__/cron.test.ts
  back/src/commands/__tests__/appendix1.helpers.integration.ts
  back/src/commands/appendix1.helpers.ts
  back/src/common/converter.ts
  back/src/cron.ts
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  front/src/form/bsdd/appendix1Producer/form.tsx
  front/src/form/bsdd/components/packagings/Packagings.tsx
Labels: ready for review

#2486 [TRA-10538] Harmonisation des dates - Fix de recette
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
  front/src/form/bsda/stepper/steps/Transport.tsx
  front/src/form/bsvhu/Operation.tsx
Labels: ready for review

#2311 [Snyk] Upgrade apollo-server-express from 3.10.1 to 3.12.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2309 [Snyk] Upgrade @aws-sdk/lib-storage and @aws-sdk/client-s3 from 3.287.0 to 3.359.0
  back/package-lock.json
  back/package.json
Labels: dependencies, ready for review

#2491 Upgrade @apollo/client 3.7.16
  front/package-lock.json
  front/package.json
Labels: dependencies

#2494 Controls dashboard access via a feature flag
  front/src/App.tsx
  front/src/common/contexts/FeatureFlagsContext.tsx
  front/src/layout/Header.tsx
  front/src/layout/Layout.tsx
  front/src/layout/LayoutContainer.tsx
Labels: ready for review

#2515 [BUGFIX] L'envoi de mails de rappels ne devrait pas crasher si une entreprise a été supprimée
  back/src/commands/__tests__/onboarding.helpers.integration.ts
  back/src/commands/onboarding.helpers.ts
Labels: ready for review
