Repository MTES-MCT/trackdechets, pull requests merged in 2023-11, with the labels that each got.

#2814 Fix Crash when LayoutContainer.tsx when the user has no company
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: hotfix

#2807 [TRA-11095] Wording: mise en conformité ADR2023 sur les quantités estimées
  back/src/bsda/pdf/components/WasteDetails.tsx
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/forms/pdf/generateBsddPdf.tsx
  front/src/common/components/EstimatedQuantityTooltip.tsx
Labels: ready for review

#2816 [tra-12860] fix cas restants
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2799 [tra-12933]Afficher le bouton 'Valider l'acceptation' au lieu de 'Gérer les contenants' lorsqu'il n'y a qu'un seul contenant pour un BSFF
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2798 [tra-12935]Absence de certains boutons d'actions dans l'onglet Tous les bordereaux
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2817 [tra-13054]Modifier le statut 'Traité (avec rupture de traçabilité)'par 'Traité' lorsqu'il n'y a pas de rupture de traçabilité sur un BSFF
  front/src/Apps/Dashboard/Components/Badge/badge.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsff.ts
Labels: ready for review

#2805 [TRA-7806] Corrections diverses dans le registre
  back/src/bsda/registry.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/compat.ts
  back/src/bsffs/registry.ts
  back/src/bsvhu/registry.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
Labels: ready for review

#2820 [TRA-11095] Fix de recette: PDF des DASRIs
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
Labels: ready for review

#2827 [tra-13124]Ouvrir la modale d'Emport direct transporteur au clic sur Signer directement lorsque l'emport direct est autorisé pour un BSDASRI
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
Labels: ready for review

#2829 [TRA-13148] Le registre contient systématiquement tous les champs possibles, par type d'export
  back/src/bsda/registry.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/registry.ts
  back/src/bsvhu/registry.ts
  back/src/forms/registry.ts
  back/src/registry/columns.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryCsv.integration.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryXls.integration.ts
  back/src/registry/types.ts
Labels: ready for review

#2778 [TRA-12704] Ajout des champs de recherche rapide à la V2
  back/prisma/scripts/index-bsdasris-indentificationNumbers.ts
  back/src/bsdasris/elastic.ts
  back/src/bsds/__tests__/where.integration.ts
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/Filters/AdvancedFilters.stories.tsx
  front/src/Apps/common/Components/Filters/AdvancedFilters.tsx
  front/src/Apps/common/Components/Filters/Filters.tsx
  front/src/Apps/common/Components/Filters/QuickFilter.tsx
  front/src/Apps/common/Components/Filters/QuickFilters.stories.tsx
  front/src/Apps/common/Components/Filters/QuickFilters.tsx
  front/src/Apps/common/Components/Filters/advancedFilters.test.tsx
  front/src/Apps/common/Components/Filters/filtersTypes.ts
  front/src/Apps/common/hooks/use-debounce.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Pages/Dashboard.tsx
Labels: ready for review

#2849 [TRA-13181] Correction de la documentation pour les Webhooks
  doc/docs/guides/good-practices.md
  doc/docs/guides/webhooks.md
Labels: ready for review

#2838 [TRA-12400] Ajout d'un bouton de déconnexion pour le protocole Oauth2
  doc/docs/guides/oauth2.md
  front/src/oauth/Oauth2Dialog.tsx
Labels: ready for review

#2848 [TRA-13111] Corrections diverses sur les operation modes
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/validation.ts
  back/src/bsffs/__tests__/validation.integration.ts
  back/src/bsvhu/__tests__/validation.integration.ts
  back/src/bsvhu/validation.ts
  back/src/common/validation/operationMode.ts
  back/src/forms/__tests__/validation.integration.ts
  front/src/common/components/OperationModeSelect.tsx
Labels: ready for review

#2840 [tra-13019]Modifier le statut par "En attente de signature transporteur" lorsque l'Annexe 1 vise un particulier comme émetteur du déchet
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  shared/constants/src/statuses.ts
Labels: ready for review

#2804 [TRA-12848] Defaults to the dashboard v2
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#2806 [TRA-12930 / TRA-12974] Prevents transporter from revising
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2850 [TRA-11095] Correction sur les quantités estimées dans les PDFs
  back/src/bsda/pdf/components/WasteDetails.tsx
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/forms/pdf/generateBsddPdf.tsx
Labels: ready for review

#2846 [tra-12963] Révisions - Fix d'affichage
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddApproveRevision.tsx
Labels: ready for review

#2847 [tra-12959] BSDD - Numéro d'échantillon éditable
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteTransportSummary.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#2844 [tra-12030] BSDA - améliorations sur le groupement
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/pdf/components/TraceabilityTable.tsx
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/dynamicRefinements.ts
  front/src/dashboard/detail/bsda/InitialBsdas.tsx
  front/src/form/bsda/components/bsdaPicker/BsdaPicker.tsx
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
Labels: ready for review, breaking change

#2851 Correction de la documentation: operationMode est obligatoire pour signer l'étape de traitement
  back/src/bsda/typeDefs/bsda.mutations.graphql
  back/src/bsdasris/typeDefs/bsdasri.mutations.graphql
  back/src/bsffs/typeDefs/bsff.mutations.graphql
  back/src/bsvhu/typeDefs/bsvhu.mutations.graphql
Labels: ready for review

#2821 [TRA-12931] Removes revision for BSD producer who can modify
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2839 [tra-13018]Enlever le CTA Ajouter une Annexe 1 si le premier enlèvement d'Annexe 1 a plus de 3 jours
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
Labels: ready for review

#2809 [tra-12085] BSDA - Correction sur la création re révision
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/index.ts
  back/src/bsda/validation/schema.ts
Labels: ready for review

#2854 [tra-12935] fix CTA incorrect
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2836 Rendre impossible la suppression d'un transporteur via la mutation `deleteFormTransporter` si celui-ci a déjà signé le BSDD
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/deleteFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/deleteFormTransporter.ts
Labels: ready for review

#2856 Deactivate old scripts
  back/prisma/scripts/addQuantityGrouped.ts
  back/prisma/scripts/fixGroupedFormsStatus.ts
  back/prisma/scripts/reindexBsddWithTrader.ts
Labels: ready for review

#2755 [TRA-12180] company selector front
  front/src/Apps/common/Components/CompanySelector/CompanySelector.stories.tsx
  front/src/Apps/common/Components/CompanySelector/CompanySelector.tsx
  front/src/Apps/common/Components/CompanySelector/CompanySelectorItem.stories.tsx
  front/src/Apps/common/Components/CompanySelector/CompanySelectorItem.tsx
  front/src/Apps/common/Components/CompanySelector/companySelector.scss
  front/src/Apps/common/Components/CompanySelector/companySelectorTypes.ts
  front/src/Apps/common/Components/Icons/Icons.tsx
  front/src/Apps/common/Components/Loader/Loader.module.scss
  front/src/Apps/common/Components/Loader/Loaders.tsx
  front/src/Apps/common/wordings/wordingsCommon.ts
  front/src/form/bsvhu/Emitter.tsx
  front/src/form/common/components/CompanySelectorWrapper/CompanySelectorWrapper.tsx
  front/src/form/common/components/company/CompanySelectorFields.tsx
Labels: ready for review

#2845 [TRA-12937] Corrections diverses dans les sous-resolvers des bordereaux sur la query `bsds`
  Changelog.md
  back/prisma/scripts/reindexGroupedBsdas.ts
  back/prisma/scripts/reindexTransporterInfo.ts
  back/src/__tests__/factories.ts
  back/src/bsda/converter.ts
  back/src/bsda/resolvers/Bsda.ts
  back/src/bsda/types.ts
  back/src/bsdasris/converter.ts
  back/src/bsdasris/elastic.ts
  back/src/bsdasris/resolvers/bsdasris/grouping.ts
  back/src/bsdasris/resolvers/bsdasris/synthesizing.ts
  back/src/bsdasris/resolvers/mutations/createSynthesisBsdasri.ts
  back/src/bsdasris/types.ts
  back/src/bsds/indexation/bulkIndexBsds.ts
  back/src/bsds/indexation/reindexBsdHelpers.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdasri.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsffs.integration.ts
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/bsffs/converter.ts
  back/src/bsffs/elastic.ts
  back/src/bsffs/resolvers/Bsff.ts
  back/src/bsffs/types.ts
  back/src/common/queries.ts
  back/src/forms/converter.ts
  back/src/forms/resolvers/Form.ts
  back/src/forms/resolvers/forms/transportSegments.ts
  back/src/queue/jobs/deleteBsd.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/__tests__/streams.integration.ts
  back/src/registry/__tests__/where.integration.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/incomingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/outgoingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/transportedWastes.integration.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/fragments/bsdasri.ts
Labels: ready for review

#2863 Fix toaster
  front/src/Apps/Dashboard/Components/DeleteModal/DeleteModal.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
  front/src/Apps/common/Components/layout/Layout.tsx
  front/src/account/AccountCompanyMember.tsx
  front/src/account/fields/forms/AccountFormCompanyInviteNewUser.tsx
  front/src/admin/verification/actions/CompanyVerifyModal.tsx
  front/src/admin/verification/actions/SendVerificationCodeLetterModal.tsx
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/MarkSegmentAsReadyToTakeOver.tsx
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/PublishBsda.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RoutePublishBsdasri.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/PublishBsvhu.tsx
Labels: ready for review

#2866 [TRA-13092] Fixes BSD freezes
  front/src/form/common/components/company/CompanySelector.tsx
  front/src/form/common/components/company/CompanySelectorFields.tsx
Labels: ready for review

#2819 [tra-12937]Corriger les statuts BSDA et BSFF initiaux, selon actions sur les BSD suite
  front/src/Apps/Dashboard/Components/Badge/Badge.tsx
  front/src/Apps/Dashboard/Components/Badge/badge.test.tsx
  front/src/Apps/Dashboard/Components/Badge/badgeTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsff.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review

#2860 [TRA-12704] Améliorations des performances et bugfix des filtres rapides
  back/prisma/scripts/index-bsdasris-indentificationNumbers.ts
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/Filters/Filters.tsx
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
Labels: ready for review

#2862 Fix bsdd update max weight validation
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/updateForm.ts
Labels: ready for review

#2867 [TRA-13188/recette] `Bsda.groupedIn` et `Bsda.forwardedIn` ne se mettent pas à jour sur le tableau de bord en cas de dissociation
  back/src/bsda/repository/bsda/create.ts
  back/src/bsda/repository/bsda/update.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/bsds/typeDefs/private/bsd.queries.graphql
Labels: ready for review

#2874 [TRA-12931] Fixes revision for appendix 2 destination
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2871 Fix toasts display durations
  front/src/Apps/Dashboard/Components/DeleteModal/DeleteModal.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
  front/src/account/AccountCompanyMember.tsx
  front/src/account/AccountMembershipRequest.tsx
  front/src/account/fields/forms/AccountFormCompanyInviteNewUser.tsx
  front/src/admin/anonymousCompany/CreateAnonymousCompany.tsx
  front/src/admin/reindex/Reindex.tsx
  front/src/admin/user/anonymizeUser.tsx
  front/src/admin/verification/actions/CompanyVerifyModal.tsx
  front/src/admin/verification/actions/SendVerificationCodeLetterModal.tsx
  front/src/common/config.ts
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/MarkSegmentAsReadyToTakeOver.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/PrepareSegment.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/TakeOverSegment.tsx
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/PublishBsda.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/RouteControlPdf.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RoutePublishBsdasri.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/PublishBsvhu.tsx
  front/src/dashboard/detail/bsdd/EditSegment.tsx
  front/src/form/bsdasri/BsdasriStepList.tsx
  front/src/form/bsdd/Recipient.tsx
  front/src/form/bsdd/appendix1Producer/form.tsx
  front/src/form/common/stepper/toaster.ts
Labels: ready for review

#2875 [tra-13191]Renommer 'Fluide frigorifique' par 'Fluide frigorigène'
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review

#2879 [tra-13018]ajout de la règle d'affichage du bouton d'ajout annexe1 dans la modale bsdd
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#2889 Affiche les toasts pour 6s contre 2s précédemment
  front/src/common/config.ts
Labels: ready for review

#2894 Update archi schema
  README.md
  archi-nov-2023.png
  stack.drawio
  stack.png
Labels: ready for review

#2897 [tra-13050]Afficher le nom du transporteur étranger au lieu de 'Particulier' sur le Tableau de bord pour un BSDD et BSDA
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
Labels: ready for review

#2900 [tra-13059]Supprimer la possibilité de Valider le traitement des BSDASRI synthétisés
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#2861 [TRA-13083] Vérifier la complétion des informations légales lors de l'ajout d'un transporteur via `createFormTransporter` et `updateFormTransporter`
  Changelog.md
  back/src/forms/recipify.ts
  back/src/forms/resolvers/mutations/__tests__/createFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/createFormTransporter.ts
  back/src/forms/resolvers/mutations/updateFormTransporter.ts
  back/src/forms/sirenify.ts
Labels: ready for review

#2905 [tra-13125] fix: refresh state when review CTA clicked
  front/src/Pages/Dashboard.tsx
Labels: ready for review

#2865 [TRA-13084] Rendre accessibles les champs `takenOverAt` et `takenOverAt` via l'objet `Transporter` (BSDD)
  Changelog.md
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/converter.ts
  back/src/forms/typeDefs/bsdd.objects.graphql
Labels: ready for review

#2907 [tra-13109]Une fois la révision validée/refusée, le statut du BSD dans l'onglet Révisions ne se met pas à jour automatiquement
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Pages/Dashboard.tsx
Labels: ready for review

#2909 [TRA-13263] Hotfix/primary secondary buttons
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: hotfix, ready for review

#2886 [TRA-11555] Les BSVHU signés par l'émetteur appraissent dans l'onglet "Suivi" du transporteur
  back/src/bsds/resolvers/queries/__tests__/bsds.bsvhu.integration.ts
  back/src/bsvhu/__tests__/elastic.integration.ts
  back/src/bsvhu/elastic.ts
Labels: ready for review

#2884 [TRA-13088] Ne pas dupliquer la quantité et le conditionnement lors de la duplication d'un BSDASRI
  back/src/bsdasris/resolvers/mutations/__tests__/duplicateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
Labels: ready for review
