Repository MTES-MCT/trackdechets, pull requests merged in 2024-10, with the labels that each got.

#3608 [TRA-15016] Lorsque le BSDD initial a eu une quantité refusé partiellement il reste toujours au statut Annexé à un BSD suite et ne passe jamais en Traité
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/updateAppendix2.ts
Labels: ready for review

#3624 [tra-14716]Ajouter l'immatriculation et le n° de CAP sur le tableau de bord général, pour tous les acteurs
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconTypes.ts
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconUtils.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/queries/fragments/bsff.ts
Labels: ready for review

#3631 [TRA-14702] Correction du poids d'une annexe 1 après la révision du poids d'un BSD enfant
  back/src/common/helpers.ts
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
Labels: hotfix, ready for review, ready to merge

#3640 Corrige l'indexation des annexe1 orphelines supprimées par le cron
  apps/cron/src/commands/appendix1.helpers.ts
  back/package.json
  back/src/scripts/bin/reindexDeletedOrphanAppendix1.ts
Labels: hotfix, ready to merge

#3626 [tra-14929]Ajouter des liens d'évitement Menu principal / secondaire / contenu (Aller à)
  front/src/App.tsx
  front/src/Apps/Account/Account.tsx
  front/src/Apps/Companies/CompaniesList/CompaniesList.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/common/Components/A11ySkipLinks/A11ySkipLinks.tsx
  front/src/Apps/common/Components/DropdownMenu/DropdownMenu.tsx
  front/src/Apps/common/Components/SideBar/SideBar.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/admin/Admin.tsx
  front/src/login/Signup.tsx
Labels: ready for review, ready to merge

#3641 Hotfix: permettre de mettre à jour l'Emport direct de DASRI quand l'email de contact est une chaîne vide
  back/src/companies/resolvers/mutations/__tests__/updateCompany.integration.ts
  back/src/companies/validation/schema.ts
  front/index.html
Labels: hotfix

#3610 BRGM / mirror push
  .github/workflows/brgm.yml
Labels: ready for review

#3643 Corrige le champ de recherche d'adresse chantier
  front/src/form/common/components/dsfr-work-site/DsfrfWorkSiteAddress.tsx
  front/src/form/common/components/work-site/WorkSiteAddress.tsx
  front/src/form/common/constants.ts
Labels: hotfix

#3638 Supprime le feature flag d'accès à la fiche établissements
  back/src/companydigest/developper_doc.md
  back/src/companydigest/resolvers/mutations/__tests__/companyDigestCreate.integration.ts
  back/src/companydigest/resolvers/mutations/create.ts
  front/index.html
  front/src/Apps/Companies/CompanyDetails.tsx
Labels: ready for review, ready to merge

#3636 FIX: résout problème de champ undefined sur BSVHU emitter
  back/src/bsvhu/converter.ts
  libs/back/prisma/src/migrations/20241003231226_set_bsvhu_emitter_defaults/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3619 [TRA 14644] - Ajout d'Eco-organisme sur BSVHU
  CONTRIBUTING.md
  Changelog.md
  back/src/__tests__/factories.ts
  back/src/__tests__/testWorkflow.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/sirenify.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriEcoOrganisme.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/sirenify.ts
  back/src/bsffs/validation/bsff/refinements.ts
  back/src/bsvhu/__tests__/bsvhuEdition.test.ts
  back/src/bsvhu/__tests__/elastic.integration.ts
  back/src/bsvhu/__tests__/factories.vhu.ts
  back/src/bsvhu/__tests__/registry.integration.ts
  back/src/bsvhu/converter.ts
  back/src/bsvhu/elastic.ts
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/bsvhu/permissions.ts
  back/src/bsvhu/registry.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhumetadata.integration.ts
  back/src/bsvhu/typeDefs/bsvhu.inputs.graphql
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/helpers.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/schema.ts
  back/src/bsvhu/validation/sirenify.ts
  back/src/bsvhu/validation/types.ts
  back/src/common/validation/zod/refinement.ts
  back/src/common/validation/zod/schema.ts
  back/src/companies/sirenify.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/forms/sirenify.ts
  libs/back/object-creator/.eslintrc.json
  libs/back/object-creator/project.json
  libs/back/object-creator/src/main.ts
  libs/back/object-creator/src/objects.ts
  libs/back/object-creator/tsconfig.app.json
  libs/back/object-creator/tsconfig.json
  libs/back/prisma/src/migrations/20240924172106_bsvhu_ecoorganisme/migration.sql
  libs/back/prisma/src/migrations/20240924183924_ecoorganisme_handle_bsvhu/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3648 Hotfix multiple revision management
  back/src/bsda/converter.ts
  back/src/bsdasris/converter.ts
  back/src/forms/converter.ts
  front/index.html
Labels: hotfix

#3602 [TRA-15153] Migrer sur le nouveau portail API de l'INSEE
  .env.model
  .github/workflows/e2e.yml
  Changelog.md
  back/src/companies/sirene/insee/client.ts
  back/src/companies/sirene/insee/token.ts
  libs/back/env/src/index.ts
  scripts/terraform/terraform.tfvars.model
Labels: ready for review, ready to merge

#3622 [TRA-6754] Doc tech - Ajouter un moteur de recherche sur la documentation développeur
  Changelog.md
  apps/doc/docusaurus.config.js
Labels: ready for review

#3616 [TRA-14731] Changer la référence du cerfa lors de l'ajout d'une fiche d'intervention
  Changelog.md
  front/src/form/bsff/FicheInterventionList.tsx
Labels: ready for review

#3561 [TRA-14824] Création d'une demande de délégation de déclaration RNDTS (back)
  back/src/__tests__/factories.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/permissions/permissions.ts
  back/src/registryDelegation/__tests__/factories.ts
  back/src/registryDelegation/permissions.ts
  back/src/registryDelegation/repository/index.ts
  back/src/registryDelegation/repository/registryDelegation/count.ts
  back/src/registryDelegation/repository/registryDelegation/create.ts
  back/src/registryDelegation/repository/registryDelegation/findFirst.ts
  back/src/registryDelegation/repository/registryDelegation/findMany.ts
  back/src/registryDelegation/repository/registryDelegation/update.ts
  back/src/registryDelegation/repository/types.ts
  back/src/registryDelegation/resolvers/Mutation.ts
  back/src/registryDelegation/resolvers/Query.ts
  back/src/registryDelegation/resolvers/__tests__/status.integration.ts
  back/src/registryDelegation/resolvers/index.ts
  back/src/registryDelegation/resolvers/mutations/__tests__/createRegistryDelegation.integration.ts
  back/src/registryDelegation/resolvers/mutations/__tests__/revokeRegistryDelegation.integration.ts
  back/src/registryDelegation/resolvers/mutations/createRegistryDelegation.ts
  back/src/registryDelegation/resolvers/mutations/revokeRegistryDelegation.ts
  back/src/registryDelegation/resolvers/mutations/utils/createRegistryDelegation.utils.ts
  back/src/registryDelegation/resolvers/mutations/utils/revokeRegistryDelegation.utils.ts
  back/src/registryDelegation/resolvers/queries/__tests__/registryDelegation.integration.ts
  back/src/registryDelegation/resolvers/queries/__tests__/registryDelegations.integration.ts
  back/src/registryDelegation/resolvers/queries/registryDelegation.ts
  back/src/registryDelegation/resolvers/queries/registryDelegations.ts
  back/src/registryDelegation/resolvers/queries/utils/registryDelegations.utils.ts
  back/src/registryDelegation/resolvers/subResolvers/RegistryDelegation.ts
  back/src/registryDelegation/resolvers/subResolvers/delegate.ts
  back/src/registryDelegation/resolvers/subResolvers/delegator.ts
  back/src/registryDelegation/resolvers/subResolvers/status.ts
  back/src/registryDelegation/resolvers/typing.ts
  back/src/registryDelegation/resolvers/utils.ts
  back/src/registryDelegation/typeDefs/private/registryDelegation.enums.graphql
  back/src/registryDelegation/typeDefs/private/registryDelegation.inputs.graphql
  back/src/registryDelegation/typeDefs/private/registryDelegation.mutations.graphql
  back/src/registryDelegation/typeDefs/private/registryDelegation.objects.graphql
  back/src/registryDelegation/typeDefs/private/registryDelegation.queries.graphql
  back/src/registryDelegation/validation/__tests__/index.test.ts
  back/src/registryDelegation/validation/index.ts
  back/src/registryDelegation/validation/schema.ts
  back/src/schema.ts
  back/src/users/typeDefs/user.enums.graphql
  back/src/utils.ts
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/registry-delegation-creation.html
  libs/back/prisma/src/migrations/20241010153237_add_registry_delegation/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3588 [TRA-15092] ETQ utilisateur je peux créer, révoquer et consulter mes demandes de délégation RNDTS
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CompanyRegistryDelegation.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CompanyRegistryDelegationAsDelegate.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CompanyRegistryDelegationAsDelegator.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CreateRegistryDelegationModal.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/RegistryDelegationsTable.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/RevokeRegistryDelegationModal.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/companyRegistryDelegation.scss
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
  front/src/Apps/common/queries/registryDelegation/queries.ts
Labels: ready for review, ready to merge

#3651 Mise à jour du logo
  front/index.html
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review, ready to merge

#3654 Ajoute quelques tests pour le security code des vhu
  back/src/bsvhu/resolvers/mutations/__tests__/signBsvhu.integration.ts
Labels: ready for review, ready to merge

#3652 Supprime le champ déprécié isRegistreNational
  Changelog.md
  back/prisma/scripts/createGovernementAccounts.ts
  libs/back/prisma/src/migrations/20241009214940_remove_is_registre_national/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3659 Disable code ql actions
  .github/workflows/codeql-analysis.yml
Labels: ready for review, ready to merge

#3644 [tra-15002]Permettre de viser un émetteur en situation irrégulière avec ou sans SIRET et retrait de la signature émetteur - FRONT
  front/src/Apps/Dashboard/Creation/bspaoh/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
  front/src/Apps/common/queries/fragments/bsvhu.ts
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
  front/src/form/common/components/dsfr-work-site/DsfrfWorkSiteAddress.tsx
Labels: ready for review, ready to merge

#3655 [tra-14931]Header - Corriger l'affichage des éléments de navigation principale et du tableau de bord lors d'un zoom texte à 200%
  front/src/Apps/common/Components/layout/Header.module.scss
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review, ready to merge

#3656 [tra-15219]Création / filtres - Corriger l'affichage des éléments de navigation principale et du tableau de bord lors d'un zoom texte à 200%
  front/src/Pages/dashboard.scss
Labels: ready for review, ready to merge

#3657 [TRA-15009] Retrait du bouton de revision dans l'UI sur les DASRI regroupés
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsdasri.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review, ready to merge

#3637 [TRA-15264] ETQ utilisateur je peux cloner un BSD
  .github/workflows/integration-tests.yml
  back/src/__tests__/factories.ts
  back/src/bsds/resolvers/Mutation.ts
  back/src/bsds/resolvers/mutations/__tests__/cloneBsd.integration.ts
  back/src/bsds/resolvers/mutations/clone.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsds/typeDefs/private/bsd.mutation.graphql
  back/src/bsds/typeDefs/private/bsd.objects.graphql
  back/src/common/helpers.ts
  back/src/forms/resolvers/queries/__tests__/forms.integration.ts
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/Clone/useCloneBsd.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review, ready to merge

#3658 [TRA-15070] Adds keyboard navigation to the dashboard
  front/index.html
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Pages/Dashboard.tsx
Labels: ready for review, ready to merge

#3647 [TRA-15218] Fixes sidebar on zoom 200%
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.scss
  front/src/Apps/common/Components/SideBar/sidebar.scss
Labels: ready for review, ready to merge

#3646 [TRA-15072] Adds h1 / h2 to pages
  front/src/Apps/Account/AccountContentWrapper.tsx
  front/src/Apps/Account/AccountMenu.tsx
  front/src/Apps/Companies/CompaniesMenu.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/common/Components/CompanySwitcher/CompanySwitcher.tsx
  front/src/Apps/common/Components/CompanySwitcher/companySwitcher.scss
  front/src/dashboard/exports/Registry.tsx
Labels: ready for review, ready to merge

#3642 [TRA-15217] Fixes Company Switcher for accessibility zoom
  front/index.html
  front/src/Apps/common/Components/CompanySwitcher/CompanySwitcher.tsx
  front/src/Apps/common/Components/CompanySwitcher/companySwitcher.scss
Labels: ready for review

#3661 [tra-15220]Card - Corriger l'affichage des éléments de navigation principale et du tableau de bord lors d'un zoom texte à 200%
  front/src/Apps/Dashboard/Components/Actors/actors.scss
Labels: ready for review, ready to merge

#3662 [tra-15002]fix recette vhu situation irregulière: conditionner l'affichage selon la checkbox cochée
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
Labels: ready for review, fix de recette

#3629 [TRA-12006] Adds a check for Annexe 1 CTA
  front/index.html
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, ready to merge

#3664 Nettoie les données de certificats amiante quand la sous section 3 est supprimée
  back/src/companies/resolvers/mutations/__tests__/updateWorkerCertification.integration.ts
  back/src/companies/resolvers/mutations/updateWorkerCertification.ts
Labels: hotfix, ready for review, ready to merge

#3639 [TRA-13729] Adds page titles
  front/index.html
  front/src/App.tsx
  front/src/Apps/common/Components/PageTitle/PageTitle.tsx
  front/src/Apps/common/Components/layout/Layout.tsx
  front/src/Apps/routes.ts
  front/src/login/Login.tsx
  front/src/login/Signup.tsx
  front/src/login/UserActivation.tsx
  package-lock.json
  package.json
Labels: ready for review, ready to merge

#3665 [TRA-15300] Solution for the icons hash issue in index.html
  front/index.html
  front/project.json
  front/src/index.tsx
  package-lock.json
  package.json
Labels: ready for review

#3673 Better typing for `ALL_NOTIFICATIONS` and `authorizedNotifications`
  back/src/common/authorizedNotifications.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/mutations/__tests__/createCompany.integration.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/users/database.ts
  back/src/users/notifications.ts
  back/src/users/resolvers/mutations/__tests__/acceptMembershipRequest.integration.ts
  back/src/users/resolvers/mutations/__tests__/changeUserRole.integration.ts
  back/src/users/resolvers/mutations/__tests__/setCompanyNotifications.integration.ts
  back/src/users/resolvers/mutations/changeUserRole.ts
  back/src/users/resolvers/mutations/setCompanyNotifications.ts
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateModal.tsx
  front/src/common/authorizedNotifications.ts
  front/src/common/notifications.ts
  libs/shared/constants/src/authorizedNotifications.ts
  libs/shared/constants/src/index.ts
Labels: ready to merge

#3635 [TRA-15037] Revoir le contenu de l'e-mail transactionnel Gestion de bordereau / suite-transmission-bsd.html
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/resolvers/mutations/markAsSealed.ts
  libs/back/mail/src/__tests__/sendInBlueBackends.test.ts
  libs/back/mail/src/backends/sendInBlueBackend.ts
  libs/back/mail/src/templates/__tests__/templates.test.ts
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/suite-transmission-bsd.html
  libs/back/mail/src/templates/mustache/your-company-is-identified-on-a-bsd.html
  libs/back/mail/src/types.ts
Labels: ready for review, ready to merge

#3674 [TRA-15072] Fixes h4 -> h3
  front/src/Apps/Account/AccountInfo/AccountInfoActionBar.tsx
  front/src/Apps/Account/AccountMembershipRequest.tsx
  front/src/Apps/Account/AccountNotifications/CompanyDisplay.tsx
  front/src/Apps/Companies/CompanyAdvanced/ApproveAdministrativeTransfer.tsx
  front/src/Apps/Companies/CompanyAdvanced/CompanyAdvanced.tsx
  front/src/Apps/Companies/CompanyAdvanced/RequestAdministrativeTransfer.tsx
  front/src/Apps/Companies/CompanyAdvanced/advanced.scss
  front/src/Apps/Companies/CompanyMembers/CompanyMembersInvite.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersList.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CompanyRegistryDelegationAsDelegate.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CompanyRegistryDelegationAsDelegator.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/CreateRegistryDelegationModal.tsx
  front/src/Apps/Companies/CompanyRegistryDelegation/RevokeRegistryDelegationModal.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureAutomation.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureCode.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureDasriDirectTakeOver.tsx
  front/src/Apps/Companies/common/Components/CompanyFormWrapper.tsx
  front/src/Apps/Companies/common/Components/companyFormWrapper.scss
Labels: ready for review, ready to merge, fix de recette

#3669 [TRA-14724] Ajout d'un nouvel onglet "Retours" pour les transporteurs
  .env.model
  .github/workflows/build-and-test.yml
  .github/workflows/e2e.yml
  Changelog.md
  apps/cron/src/cron.test.ts
  apps/cron/src/main.ts
  back/src/bsda/__tests__/elastic.integration.ts
  back/src/bsda/database.ts
  back/src/bsda/elastic.ts
  back/src/bsdasris/__tests__/elastic.integration.ts
  back/src/bsdasris/elastic.ts
  back/src/bsds/indexation/bulkIndexBsds.ts
  back/src/bsds/indexation/reindexBsdHelpers.ts
  back/src/bsds/resolvers/mutations/__tests__/createPdfAccessToken.integration.ts
  back/src/bsds/resolvers/mutations/createPdfAccessToken.ts
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/bsds/typeDefs/private/bsd.inputs.graphql
  back/src/bsds/validation.ts
  back/src/bsffs/__tests__/elastic.integration.ts
  back/src/bsffs/database.ts
  back/src/bsffs/elastic.ts
  back/src/bspaoh/__tests__/elastic.integration.ts
  back/src/bspaoh/converter.ts
  back/src/bspaoh/elastic.ts
  back/src/bsvhu/__tests__/elastic.integration.ts
  back/src/bsvhu/elastic.ts
  back/src/common/__tests__/elasticHelpers.integration.ts
  back/src/common/elastic.ts
  back/src/common/elasticHelpers.ts
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/database.ts
  back/src/forms/elastic.ts
  back/src/forms/elasticHelpers.ts
  back/src/index.ts
  back/src/scripts/bin/cleanUpIsReturnForTab.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/types/commonTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Apps/routes.ts
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
  libs/back/env/src/index.ts
Labels: ready to merge

#3675 [TRA-12006] Fixes annexe 1 CTA
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
Labels: ready for review, ready to merge, fix de recette

#3678 [tra-15022]fix recette
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Forms/Components/FormStepsTabs/FormStepsTabs.tsx
  front/src/Apps/common/queries/fragments/bsvhu.ts
Labels: ready for review, fix de recette

#3660 [tra-14716]fix recette display immat number
  front/src/Apps/Dashboard/bsdMapper.ts
Labels: ready for review, ready to merge, fix de recette

#3680 [tra-15071]fix recette : ajout alternative code signature
  front/src/Apps/common/Components/CompanySwitcher/CompanySwitcher.tsx
Labels: ready for review, fix de recette

#3681 [TRA-13729] Adds new title
  front/src/Apps/routes.ts
Labels: ready for review, fix de recette

#3679 [TRA-15300] Fixes favicon import
  front/index.html
  front/project.json
  front/src/index.tsx
Labels: ready for review, fix de recette

#3682 [tra-14931]fix recette
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review, fix de recette

#3684 Correctifs pour le clonage des BSD avec opérations finales
  back/src/__tests__/factories.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsdasris/__tests__/factories.ts
  back/src/bsds/resolvers/mutations/__tests__/cloneBsd.integration.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsffs/__tests__/factories.ts
Labels: ready for review

#3676 Fix BSVHU DSFR form
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/FormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Forms/Components/IdentificationNumbers/IdentificationNumber.tsx
  front/src/Apps/Forms/Components/IdentificationNumbers/identificationNumber.scss
Labels: ready for review, ready to merge

#3683 [fix recette] - Changement du wording d'installation irrégulière dans le PDF
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
Labels: ready for review, ready to merge

#3677 [TRA 14421] brouillons BSVHU non accessibles si pas auteur
  Changelog.md
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/permissions.ts
  back/src/bsda/repository/bsda/create.ts
  back/src/bsda/utils.ts
  back/src/bsds/indexation/__tests__/bulkIndexBsds.integration.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsvhu.integration.ts
  back/src/bsvhu/__tests__/factories.vhu.ts
  back/src/bsvhu/elastic.ts
  back/src/bsvhu/permissions.ts
  back/src/bsvhu/repository/bsvhu/create.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/publishBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/bsvhus.ts
  back/src/bsvhu/utils.ts
  back/src/registry/__tests__/streams.integration.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  libs/back/prisma/src/migrations/20241009180028_bsvhu_draft_access/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/scripts/20241009174516425_bsvhu_draft_restriction.ts
Labels: ready for review, ready to merge

#3532 Fix partial dump script
  libs/back/partial-backup/src/main.ts
  libs/back/partial-backup/src/pipelines.ts
  libs/back/partial-backup/src/traversals.ts
Labels: ready for review, ready to merge

#3697 Correctif pour empêcher les entreprises en sommeil de créer ou recevoir des demandes de délégation
  back/src/registryDelegation/resolvers/mutations/__tests__/createRegistryDelegation.integration.ts
  back/src/registryDelegation/resolvers/utils.ts
Labels: ready for review

#3695 [TRA-15218] Sidebar 200% layout
  front/src/Apps/common/Components/SideBar/sidebar.scss
Labels: ready for review, fix de recette

#3696 [TRA-14424] Updates TD banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3698 [TRA-15218] Fixes sidebar scroll
  front/src/Apps/common/Components/SideBar/sidebar.scss
Labels: ready for review, fix de recette

#3699 Amélioration du wording pour l'onglet Retours
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review, ready to merge

#3701 Corrige l'affichage des révisions
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
Labels: ready for review, fix de recette

#3700 [tra-15002]fix recette Vhu situation irregulière: permettre au transporteur de signer des le statut initial
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsvhuValidation.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsvhu.ts
Labels: ready for review, ready to merge, fix de recette

#3704 [TRA-13729] Fixes admin URLs and titles
  front/src/Apps/routes.ts
Labels: ready for review, fix de recette

#3694 Query pour la recherche Bsds dédiée à la fiche établissement
  Changelog.md
  back/src/bsds/resolvers/index.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.integration.ts
  back/src/bsds/resolvers/queries/__tests__/controlbsds.integration.ts
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/bsds/resolvers/queries/controlBsds.ts
  back/src/bsds/resolvers/queries/helpers.ts
  back/src/bsds/resolvers/queries/types.ts
  back/src/bsds/typeDefs/private/bsd.inputs.graphql
  back/src/bsds/typeDefs/private/bsd.queries.graphql
  back/src/bsds/validation.ts
Labels: ready for review, ready to merge

#3706 [tra-15002]vhu situation irregulière fix adresse manuelle
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
Labels: ready for review, ready to merge, fix de recette
