Repository MTES-MCT/trackdechets, pull requests merged in 2024-09, with the labels that each got.

#3541 [TRA-14904] Supprimer l'adresse tech dans la documentation API
  apps/doc/docs/intro.mdx
Labels: ready for review

#3557 Revert TRA-13421 : Le numéro de notification n'est plus requis
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/validation.ts
Labels: ready for review

#3564 [TRA-15079] Les infos de pagination sont absentes du résultat de la query `formsLifeCycle`
  back/src/forms/resolvers/queries/__tests__/formsLifeCycle.integration.ts
  back/src/forms/resolvers/queries/formsLifeCycle.ts
Labels: ready for review

#3536 [TRA-14919] Correction du poids affiché sur le tableau de bord en cas de refus total pour les BSDD
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
Labels: ready for review

#3546 [TRA-13899][BACK] ETQ destinataire, je peux spécifier le statut de rinçage de la citerne pour son retour à vide
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/compat.ts
  back/src/forms/converter.ts
  back/src/forms/edition.ts
  back/src/forms/helpers/citerneNotWashedOutReason.ts
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/forms/registry.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsAccepted.integration.ts
  back/src/forms/resolvers/mutations/markAsAccepted.ts
  back/src/forms/resolvers/queries/__tests__/form.integration.ts
  back/src/forms/typeDefs/bsdd.enums.graphql
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/types.ts
  back/src/forms/validation.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  libs/back/prisma/src/migrations/20240829090308_charte_citerne/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3554 Ajouter les Rubriques pour les sous-types de profils Installation de traitement et Déchetterie & Retours UI sur la création / modification d'un établissement
  back/src/companies/typeDefs/company.enums.graphql
  back/src/companies/validation/refinements.ts
  back/src/companies/validation/schema.ts
  e2e/src/plans/companies.spec.ts
  e2e/src/utils/company.ts
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeCheckbox.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/EcoOrganismeAgrementsForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/RhfCompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/WorkerCertificationForm.tsx
  front/src/Apps/Companies/common/utils.ts
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
  front/src/company/CompanyActivity.tsx
  libs/back/prisma/src/schema.prisma
  libs/shared/constants/src/VALIDATION.ts
Labels: ready for review

#3555 Rendre obligatoire le volume du contenant à la publication sur le BSFF
  Changelog.md
  back/src/bsffs/validation/bsff/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsff/refinements.ts
  front/src/form/bsff/components/packagings/Packagings.tsx
Labels: ready for review

#3558 [TRA-14583] Mettre à jour la page Documentation Rôle et permissions API
  apps/doc/docs/guides/registre.md
  apps/doc/docs/reference/permissions.md
  apps/doc/docs/reference/profils-etablissement.md
  apps/doc/docs/reference/statuts/bsdd.mdx
  apps/doc/sidebars.js
  package-lock.json
  package.json
Labels: ready for review

#3549 [TRA 14578 + TRA 15020] split chemins d'erreur Zod BSVHU/BSPAOH + champs scellés dans metadata
  Changelog.md
  back/src/bspaoh/dataloader.ts
  back/src/bspaoh/resolvers/BspaohMetadata.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/resolvers/queries/__tests__/bspaohmetadata.integration.ts
  back/src/bspaoh/typeDefs/bspaoh.objects.graphql
  back/src/bspaoh/validation/rules.ts
  back/src/bsvhu/dataloader.ts
  back/src/bsvhu/resolvers/Bsvhu.ts
  back/src/bsvhu/resolvers/BsvhuMetadata.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhumetadata.integration.ts
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/bsvhu/validation/helpers.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/rules.ts
  back/src/server.ts
  back/src/types.ts
  front/index.html
  front/src/Apps/Dashboard/Creation/bspaoh/FormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/queries.ts
  front/src/Apps/common/queries/fragments/bspaoh.ts
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
Labels: ready for review

#3476 [TRA-14399] Ajout d'un filtre par sous-type de bordereau
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/elastic.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/elastic.ts
  back/src/bsdasris/registry.ts
  back/src/bsds/__tests__/where.integration.ts
  back/src/bsds/typeDefs/private/bsd.inputs.graphql
  back/src/bsds/where.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/elastic.ts
  back/src/bsffs/registry.ts
  back/src/bspaoh/elastic.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/elastic.ts
  back/src/bsvhu/registry.ts
  back/src/common/__tests__/subTypes.integration.ts
  back/src/common/elastic.ts
  back/src/common/subTypes.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/elastic.ts
  back/src/forms/registry.ts
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/Filters/AdvancedFilters.tsx
  front/src/Apps/common/Components/Select/Select.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.stories.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.utils.test.ts
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.utils.ts
  front/src/Apps/common/Components/SelectWithSubOptions/selectWithSubOptions.scss
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
Labels: ready for review

#3572 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#3565 [TRA-14869] Mise à jour des profils et sous profils en masse
  Changelog.md
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/companies/resolvers/Mutation.ts
  back/src/companies/resolvers/mutations/__tests__/bulkUpdateCompaniesProfiles.integration.ts
  back/src/companies/resolvers/mutations/bulkUpdateCompaniesProfiles.ts
  back/src/companies/typeDefs/private/company.inputs.graphql
  back/src/companies/typeDefs/private/company.mutations.graphql
  back/src/companies/validation/schema.ts
  front/index.html
  front/src/Apps/routes.ts
  front/src/admin/Admin.tsx
  front/src/admin/bulkProfilesUpdate/BulkprofilesUpdateAdmin.tsx
Labels: ready for review

#3568 [TRA-15075 ]Création en masse - Ajout de colonnes pour permettre d'ajouter un ou plusieurs sous-profils à chaque établissement
  Changelog.md
  back/src/users/bulk-creation/__tests__/bulk-create.integration.ts
  back/src/users/bulk-creation/__tests__/csv/etablissements.csv
  back/src/users/bulk-creation/__tests__/loaders.test.ts
  back/src/users/bulk-creation/__tests__/validation.test.ts
  back/src/users/bulk-creation/index.ts
  back/src/users/bulk-creation/loaders.ts
  back/src/users/bulk-creation/validations.ts
  front/index.html
Labels: ready for review

#3182 Upgrades stories format
  front/src/Apps/Dashboard/Components/Actors/Actors.stories.tsx
  front/src/Apps/Dashboard/Components/Badge/Badge.stories.tsx
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.stories.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.stories.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/InfoWithIcon.stories.tsx
  front/src/Apps/Dashboard/Components/WasteDetails/WasteDetails.stories.tsx
  front/src/Apps/common/Components/DropdownMenu/DropdownMenu.stories.tsx
  front/src/Apps/common/Components/Filters/AdvancedFilters.stories.tsx
  front/src/Apps/common/Components/Filters/QuickFilters.stories.tsx
Labels: ready to merge

#3556 [TRA-14661] Génération de modèles de bsds vierges
  .env.model
  .github/workflows/e2e.yml
  CONTRIBUTING.md
  Changelog.md
  apps/Procfile.back
  back/package.json
  back/src/bsda/pdf/generator.tsx
  back/src/bsdasris/pdf/generator.tsx
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/bsffs/pdf/generator.tsx
  back/src/bsffs/resolvers/queries/bsffPdf.ts
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/bsvhu/pdf/generator.tsx
  back/src/common/pdf/emptypdf.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/scripts/bin/bsdTemplates/emptyPdfData.ts
  back/src/scripts/bin/bsdTemplates/generateBsdTemplates.ts
  back/src/scripts/bin/bsdTemplates/index.ts
  front/README.md
  libs/back/env/src/index.ts
Labels: ready for review

#3575 Erreur dans la documentation du workflow annexe 1
  back/src/forms/examples/steps/updateForm.ts
Labels: ready for review

#3550 [TRA-14959] Reworks oidc and oauth dialogs to DSFR
  Changelog.md
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/oauth/AuthDialog.tsx
  front/src/oauth/Dialog.module.scss
  front/src/oauth/Oauth2Dialog.tsx
  front/src/oauth/OidcDialog.tsx
  front/src/oauth/use-oidc.ts
Labels: ready for review

#3574 [TRA-14234] Updates banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3542 [TRA-14936] Fixes a link in company creation
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAdd.tsx
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAddForeign.tsx
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAddProducer.tsx
Labels: ready for review

#3562 [TRA-14962] Reworks my applications to DSFR
  Changelog.md
  front/src/Apps/Account/Account.tsx
  front/src/Apps/Account/AccountApplications/AccountApplications.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplications.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplicationsCreateUpdate.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplicationsDelete.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/queries.ts
  front/src/Apps/Account/AccountMenu.tsx
  front/src/Apps/Account/oauth2/AccountOauth2App.module.scss
  front/src/Apps/Account/oauth2/AccountOauth2App.tsx
  front/src/Apps/Account/oauth2/AccountOauth2AppCreateUpdate.module.scss
  front/src/Apps/Account/oauth2/AccountOauth2AppCreateUpdate.tsx
  front/src/Apps/Account/oauth2/AccountOauth2AppList.tsx
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review

#3566 [tra-14625 & tra-14691] Mise en sommeil d'un établissement & transfert de bordereaux
  back/src/bsdasris/validation.ts
  back/src/common/validation.ts
  back/src/common/validation/zod/refinement.ts
  back/src/companies/__tests__/search.test.ts
  back/src/companies/resolvers/AdministrativeTransfer.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/companies/resolvers/Mutation.ts
  back/src/companies/resolvers/index.ts
  back/src/companies/resolvers/mutations/__tests__/cancelAdministrativeTransfer.integration.ts
  back/src/companies/resolvers/mutations/__tests__/createAdministrativeTransfer.integration.ts
  back/src/companies/resolvers/mutations/__tests__/toggleDormantCompany.integration.ts
  back/src/companies/resolvers/mutations/cancelAdministrativeTransfer.ts
  back/src/companies/resolvers/mutations/createAdministrativeTransfer.ts
  back/src/companies/resolvers/mutations/submitAdministrativeTransferApproval.ts
  back/src/companies/resolvers/mutations/toggleDormantCompany.ts
  back/src/companies/resolvers/queries/__tests__/companyInfos.test.ts
  back/src/companies/resolvers/queries/companyInfos.ts
  back/src/companies/search.ts
  back/src/companies/sirenify.ts
  back/src/companies/typeDefs/company.enums.graphql
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.inputs.graphql
  back/src/companies/typeDefs/private/company.mutations.graphql
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/companies/types.ts
  back/src/forms/validation.ts
  back/src/queue/jobs/administrativeTransfer.ts
  back/src/queue/jobs/index.ts
  back/src/queue/producers/administrativeTransfer.ts
  front/src/Apps/Companies/CompanyAdvanced/ApproveAdministrativeTransfer.tsx
  front/src/Apps/Companies/CompanyAdvanced/CompanyAdvanced.tsx
  front/src/Apps/Companies/CompanyAdvanced/RequestAdministrativeTransfer.tsx
  front/src/Apps/Companies/CompanyAdvanced/advanced.scss
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  libs/back/prisma/src/migrations/20240909195445_add_isdormant_company/migration.sql
  libs/back/prisma/src/migrations/20240910085927_add_administrative_transfer/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3577 Fix env variable validation
  libs/back/env/src/index.ts
Labels: ready for review

#3411 [tra-13295] Retirer la dépendance avec MongoDB pour les révisions
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/BsdaRevisionRequest.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsdasris/repository/revisionRequest/accept.ts
  back/src/bsdasris/resolvers/BsdasriRevisionRequest.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/forms/resolvers/FormRevisionRequest.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/index.ts
  libs/back/prisma/src/migrations/20240819163725_revisions_history/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/runner.ts
  libs/back/scripts/src/scripts/20240619121123325_fill_revisions_history.ts
Labels: ready for review

#3576 [TRA-14958] Add empty return ADR to reception
  Changelog.md
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
  front/src/Apps/common/utils/adrBsddSummary.ts
Labels: ready for review

#3573 [TRA-14957] Ajout de la charte citerne aux BSDD
  Changelog.md
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
  front/src/Apps/common/utils/citerneBsddSummary.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#3578 [TRA-15114] - L'entreposage provisoire ne devrait pas pouvoir valider le traitement à la place du destinataire
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#3545 [tra-15026]Griser les champs lorsqu'ils sont scellés - FRONT
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/isStepDisabled.ts
Labels: ready for review

#3538 [tra-14949]Modifier l'aspect des onglets lorsqu'une erreur est présente dans celui-ci au clic sur Publier
  front/src/Apps/Dashboard/Creation/FormContainer.tsx
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/FormSteps.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/schema.ts
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Dashboard/Validation/workflow/Draft/DraftValidation.tsx
  front/src/Apps/Forms/Components/FormStepsTabs/FormStepsTabs.tsx
  front/src/Apps/Forms/Components/FormStepsTabs/formStepsTabs.scss
  front/src/Apps/Forms/Components/FormStepsTabs/utils.ts
  front/src/Apps/Forms/Components/RhfCompanyContactInfo/RhfCompanyContactInfo.tsx
Labels: ready for review

#3582 [TRA-14962] Fixes my applications layout
  front/index.html
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplications.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplicationsCreateUpdate.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplicationsDelete.tsx
Labels: ready for review, fix de recette

#3583 [TRA-14957] Fixes reception / acceptation citerne status
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, fix de recette

#3584 [TRA-14958] Fixes reception / acceptation ADR conditions
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
Labels: ready for review, fix de recette

#3587 [TRA-14517] Correctifs front sur l'affichage du mode de transport
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteTransportSummary.tsx
Labels: ready for review

#3590 [TRA-14957] Fixes var name
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
Labels: ready for review, fix de recette

#3592 [tra-14949]fix recette
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/schema.ts
  front/src/Apps/Forms/Components/FormStepsTabs/formStepsTabs.scss
Labels: ready for review, fix de recette

#3589 [TRA-14959] Fixes oauth page and header
  front/index.html
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/oauth/AuthDialog.tsx
Labels: ready for review, fix de recette

#3594 Correctifs sur le filtre avancé par type / sous-type de bordereau
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.tsx
Labels: ready for review

#3598 Correctifs CSS sur le filtre avancé par types / sous-types de bordereaux
  front/src/Apps/common/Components/Filters/AdvancedFilters.stories.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/selectWithSubOptions.scss
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/dashboard/components/BSDList/BSDTypeFilter.tsx
Labels: ready for review

#3599 [tra-14703]fix recette - prise en compte des erreurs sans path
  front/src/Apps/Dashboard/Creation/utils.ts
Labels: ready for review, fix de recette

#3591 Recette - tra-14625 & tra-13295
  back/src/bsda/validation/refinements.ts
  back/src/bsdasris/validation.ts
  back/src/bsffs/validation/bsff/refinements.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/common/validation/zod/refinement.ts
  back/src/companies/resolvers/mutations/__tests__/createAdministrativeTransfer.integration.ts
  back/src/companies/resolvers/mutations/createAdministrativeTransfer.ts
  back/src/forms/validation.ts
  back/src/queue/bull-board.ts
  front/src/Apps/Companies/CompanyAdvanced/ApproveAdministrativeTransfer.tsx
  front/src/Apps/Companies/CompanyAdvanced/RequestAdministrativeTransfer.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionModal.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
Labels: ready for review

#3596 Correctifs sur les DASRI pour le nouveau mode de transport obligatoire
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriTransport.integration.ts
  back/src/bsdasris/validation.ts
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
Labels: ready for review

#3603 Fixes temp storage ADR and citerne status
  front/index.html
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, fix de recette

#3605 [Fix] Fixes blurry modals
  front/src/Apps/common/Components/Modal/modal.scss
Labels: ready for review, fix de recette

#3581 Corrige la checkbox et la date du template bsda
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/pdf/components/WasteDetails.tsx
  back/src/bsda/pdf/generator.tsx
  back/src/scripts/bin/bsdTemplates/generateBsdTemplates.ts
Labels: ready for review, fix de recette

#3593 Corrige la validation des données de la mise à jour en masse
  front/src/admin/bulkProfilesUpdate/BulkprofilesUpdateAdmin.tsx
Labels: ready for review, fix de recette

#3609 [TRA-15064] Ajout d'un encart réglementaire pour éviter un usage abusif de l'absence d'entreprise de travaux BSDA
  Changelog.md
  front/src/form/bsda/components/NoWorkerAlert.tsx
  front/src/form/bsda/stepper/steps/Worker.tsx
Labels: ready for review

#3530 Relocalisation de l'action de compte de review dans le repo
  .github/workflows/add-ready-to-merge-label.yml
  scripts/gh-get-review-counts.js
Labels: ready for review, ready to merge

#3617 Hotfix/bsvhu signature
  front/index.html
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
Labels: hotfix, ready for review, ready to merge

#3620 [TRA-15172] HOTFIX - Impossible de publier/modifier un BSFF de regroupement dont les BSFF initiaux ont un "Volume du contenant en L" à 0
  back/src/bsffs/validation/bsff/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsff/refinements.ts
  front/src/form/bsff/components/packagings/Packagings.tsx
Labels: hotfix, ready for review

#3621 [TRA-8327] - Documentation API Developers : Page Not Found, si on n'y accède pas via l'arborescence
  Changelog.md
  apps/doc/docs/guides/playground.md
  apps/doc/docs/guides/registre.md
  apps/doc/docs/guides/sirene.md
  apps/doc/docs/guides/webhooks.md
  apps/doc/docs/reference/authentification.md
  apps/doc/docs/reference/statuts/bsda.mdx
  apps/doc/docs/reference/statuts/bsdasri.mdx
  apps/doc/docs/reference/statuts/bsdd.mdx
  apps/doc/docs/reference/statuts/bsff.mdx
  apps/doc/docs/reference/statuts/bspaoh.mdx
  apps/doc/docs/tutoriels/courant/query-bordereaux.md
  apps/doc/docs/tutoriels/quickstart/first-query.md
  apps/doc/docs/tutoriels/quickstart/introduction.md
Labels: ready for review, ready to merge

#3625 Fix erreur 404 à la suppression de label
  .github/workflows/add-ready-to-merge-label.yml
Labels: ready for review
