Repository MTES-MCT/trackdechets, pull requests merged in 2024-12, with the labels that each got.

#3778 [TRA-15342] Le champ destinationCap du BSDA est scellé à partir de l'étape de transport (ou émission si pas d'entreprise de travaux)
  back/src/bsda/validation/rules.ts
Labels: ready for review

#3784 [tra-15096][tra-14783] - Refacto de la fonction `canReviewBsd`
  Changelog.md
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActions.test.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3777 [TRA-15230] Les BSDA sont désormais inclus dans les transferts de bordereaux d'un SIRET mis en sommeil vers un autre SIRET
  back/src/queue/jobs/__tests__/administrativeTransfer.integration.ts
  back/src/queue/jobs/administrativeTransfer.ts
  front/src/Apps/Companies/CompanyAdvanced/RequestAdministrativeTransfer.tsx
Labels: ready for review

#3773 [tra-15089]Retirer le bouton d'action Contrôle Routier présent pour les Annexes 1 sur l'onglet Collectés ou Retours
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3774 [tra-12007]Ajouter le CAP sur l'aperçu du BSDD de tournée dédiée
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, ready to merge

#3782 prendre en compte le transporteur étranger
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
Labels: ready for review, ready to merge

#3800 HOTFIX : Révison BSDD et BSDA : "Le déchet contient des polluants organiques persistants" impossible de sélectionner non
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
Labels: ready for review, ready to merge

#3786 [tra-15398]Mettre au DSFR la modale de signature de l'émetteur
  front/src/Apps/Dashboard/Components/Journey/Journey.module.scss
  front/src/Apps/Dashboard/Components/Journey/Journey.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/BsvhuJourneySummary.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuEmission.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/WasteVhuSummary.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsvhuValidation.tsx
  front/src/common/components/index.ts
  front/src/common/datetime.ts
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/BsvhuSummary.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
Labels: ready for review

#3790 [TRA-15516] Permettre aux éco-organismes de réviser un BSDA
  Changelog.md
  back/src/bsda/permissions.ts
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  front/src/Apps/Dashboard/Components/Revision/revisionServices.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/reviews/BsdaReviewQuery.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
Labels: ready for review, ready to merge

#3804 [tra-15576] - Impossible de changer de destination finale sur un BSDD avec entreposage provisoire si la destination finale initialement renseignée a été mise en sommeil
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/resolvers/mutations/markAsResealed.ts
  back/src/forms/resolvers/mutations/markAsResent.ts
  back/src/forms/resolvers/mutations/markAsSealed.ts
  back/src/forms/validation.ts
Labels: ready for review, ready to merge

#3780 [TRA-15393] ETQ que producteur d'un BSDA, je suis alerté par mail si le destinationCap est modifié
  back/src/__tests__/factories.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/update.ts
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllModal.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateModal.tsx
  front/src/Apps/Account/AccountNotifications/utils.ts
  front/src/form/bsda/stepper/steps/Destination.tsx
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/bsda-destinationCap-modification-email.html
Labels: ready for review, ready to merge

#3796 [TRA-15571] Les intermédiaires n'apparaissent pas sur le récépissé PDF du BSDA
  Changelog.md
  back/src/bsda/mails/refused.ts
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/pdf/generator.tsx
  back/src/bsda/resolvers/mutations/sign.ts
  libs/shared/constants/src/index.ts
  libs/shared/constants/src/pluralize.ts
Labels: ready for review, ready to merge

#3803 [TRA-15572] Registre : les colonnes de l'opération finale n'apparaissent pas sur un BSDD avec entreposage provisoire
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/registry.ts
Labels: ready for review, ready to merge

#3792 [TRA 15352] Remonter le VHU en situation irrégulière (sans émetteur TD) dans l'onglet À collecter
  Changelog.md
  back/src/bsda/validation/schema.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsffs/validation/bsffPackaging/schema.ts
  back/src/bspaoh/validation/schema.ts
  back/src/bsvhu/elastic.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/schema.ts
  back/src/bsvhu/validation/sirenify.ts
  back/src/companies/sirenify.ts
  back/src/companies/validation/schema.ts
  libs/back/prisma/src/migrations/20241128180833_bsvhu_emitter_not_on_td/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/scripts/20241128182942148_bsvhu_emitter_not_on_td.ts
Labels: ready for review, ready to merge

#3813 Fix vhu e2e tests
  e2e/src/utils/bsvhu.ts
Labels: ready for review

#3793 Ne pas permettre d'accéder aux brouillons des autres acteurs sur le BSFF
  Changelog.md
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsffs/__tests__/bsff.factories.integration.ts
  back/src/bsffs/__tests__/elastic.integration.ts
  back/src/bsffs/__tests__/factories.ts
  back/src/bsffs/elastic.ts
  back/src/bsffs/permissions.ts
  back/src/bsffs/repository/bsff/create.ts
  back/src/bsffs/repository/bsff/update.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/createDraftBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/deleteBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/duplicateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/publishBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/queries/__tests__/bsff.integration.ts
  back/src/bsffs/resolvers/queries/__tests__/bsffPackagings.integration.ts
  back/src/bsffs/resolvers/queries/__tests__/bsffs.integration.ts
  back/src/bsffs/resolvers/queries/bsffs.ts
  back/src/bsffs/utils.ts
  libs/back/prisma/src/migrations/20241130085509_add_bsff_can_access_draft_orgid/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/scripts/20241130173645420_bsff_draft_restrictions.ts
Labels: ready for review, ready to merge

#3802 Correction d'une erreur dans le fichier de définition GraphQL
  back/src/registry/typeDefs/registry.objects.graphql
Labels: ready for review, ready to merge

#3797 [TRA-15389] Fixes asbestos organization in company creation
  Changelog.md
  front/src/Apps/Companies/common/Components/CompanyTypeForm/FormikCompanyTypeForm.tsx
Labels: ready for review

#3785 [TRA-14470] : Permettre de faire une demande de révision BSDD lorsque le l'émetteur est un particulier ou un navire étranger
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
Labels: ready for review

#3799 [TRA-15402] Fixes company switchers cache issues
  Changelog.md
  front/src/Apps/common/Components/CompanySwitcher/CompanySwitcher.tsx
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
Labels: ready for review, ready to merge

#3798 [TRA-15489] Fixes companies width
  Changelog.md
  front/src/Apps/Companies/CompaniesRoutes.tsx
Labels: ready for review

#3795 [TRA-15377] Adds actors to BSVHU
  Changelog.md
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/ActorsList.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/OtherActors.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
  front/src/Apps/common/queries/fragments/bsvhu.ts
Labels: ready for review, ready to merge

#3809 [TRA-15399] Adds VHU DSFR sign transport
  Changelog.md
  front/src/Apps/Dashboard/Components/Journey/Journey.module.scss
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuTransport.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsvhuValidation.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
Labels: ready for review, ready to merge

#3814 [TRA-14874] Updates banner message
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3815 Upgrade to Prisma 6
  back/src/bsda/resolvers/mutations/revisionRequest/submitRevisionRequestApproval.ts
  back/src/bsda/where.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/submitRevisionRequestApproval.ts
  back/src/companies/resolvers/mutations/__tests__/cancelAdministrativeTransfer.integration.ts
  back/src/companies/resolvers/mutations/__tests__/submitAdministrativeTransferApproval.integration.ts
  back/src/forms/repository/form/findUnique.ts
  back/src/forms/resolvers/mutations/multiModal.ts
  back/src/forms/resolvers/mutations/submitFormRevisionRequestApproval.ts
  libs/back/prisma/src/migrations/20241210105335_prisma_6_migrate/migration.sql
  package-lock.json
  package.json
Labels: ready for review, ready to merge

#3820 Correction des typos "vérouillé" > "verrouillé"
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/rules.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffPackaging.integration.ts
  back/src/bsffs/validation/bsff/rules.ts
  back/src/bsffs/validation/bsffPackaging/rules.ts
  back/src/bsvhu/errors.ts
Labels: ready for review, ready to merge

#3821 Mise à jour du Changelog
  Changelog.md
Labels: ready for review, ready to merge

#3824 [tra-15398][tra-15399]fix recette modale signature VHU dsfr
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuEmission.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuTransport.tsx
Labels: ready for review, fix de recette

#3827 [TRA-15342][Fix recette] Nouvelles règles pour les champs destinationCap & destinationOperationNextDestinationCap
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/update.ts
  back/src/bsda/validation/rules.ts
  front/src/form/bsda/stepper/steps/Destination.tsx
Labels: ready for review, ready to merge, fix de recette

#3831 [tra-15627]Vhu fix affichage courtier, négociant et autres intermédiaires
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
Labels: ready for review

#3829 [TRA-15377] Fixes VHU actors
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/ActorsList.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
  front/src/Apps/Forms/Components/RhfCompanyContactInfo/RhfCompanyContactInfo.tsx
Labels: ready for review, ready to merge, fix de recette

#3839 [TRA 15377] Fixes error messages
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/ActorsList.tsx
  front/src/Apps/Forms/Components/RhfCompanyContactInfo/RhfCompanyContactInfo.tsx
Labels: ready for review, fix de recette

#3840 [TRA 15377] Fixes VHU payload
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
Labels: ready for review, ready to merge, fix de recette

#3835 [TRA-15624] Correction du CSS pour la section "Signature automatique (annexe 1)"
  front/src/Apps/Companies/CompanySignature/CompanySignatureAutomation.tsx
Labels: ready for review, ready to merge

#3830 Proposition de nouveau template pour les PR GH
  .github/pull_request_template.md
Labels: ready for review, ready to merge
