Repository MTES-MCT/trackdechets, pull requests merged in 2024-05, with the labels that each got.

#3286 [tra-13918] Fix bsdasri registry
  back/src/bsdasris/registry.ts
Labels: ready for review

#3282 [tra-14074]fix recette: remove eco org prefix
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconTypes.ts
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconUtils.ts
Labels: ready for review

#3277 [tra-14035]Mise à jour DSFR Mes établissements - Onglet Informations
  e2e/src/utils/company.ts
  front/src/Apps/Account/fields/AccountFieldCompanyBrokerReceipt.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyGerepId.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyGivenName.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyTraderReceipt.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyTransporterReceipt.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyTypes.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyVhuAgrementBroyeur.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyVhuAgrementDemolisseur.tsx
  front/src/Apps/Account/fields/AccountFieldCompanyWorkerCertification.tsx
  front/src/Apps/Account/fields/AccountInfoAutoUpdate.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyAddVhuAgrementBroyeur.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyAddVhuAgrementDemolisseur.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyBrokerReceipt.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyTraderReceipt.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyTransporterReceipt.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyTypes.tsx
  front/src/Apps/Companies/AccountCompanyInfo.tsx
  front/src/Apps/Companies/CompanyContact/CompanyContactForm.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyIdentificationForm.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyInfo.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileInformation.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileSubForm.tsx
  front/src/Apps/Companies/CompanyInfo/companyInfo.scss
  front/src/Apps/Companies/common/Components/CompanyFormCtaFragment.tsx
  front/src/Apps/Companies/common/Components/CompanyFormWrapper.tsx
  front/src/Apps/Companies/common/Components/companyFormWrapper.scss
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  front/src/Apps/Companies/common/utils.ts
  front/src/Apps/common/Components/Icons/Icons.tsx
  front/src/common/components/Tooltip.tsx
  front/src/company/CompanyRegistration.tsx
  front/src/login/CompanyType.tsx
Labels: ready for review

#3270 [tra-13613]Mettre au DSFR la modification de la plaque d'immatriculation et du champs libre transporteur
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/InfoWithIcon.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/Apps/Dashboard/Components/Pdf/useDownloadPdf.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditForm.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditModal.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/transporterInfoEditForm.scss
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsffValidation.test.tsx
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/Apps/common/Components/Icons/Icons.tsx
  front/src/Apps/common/Components/Modal/Modal.module.scss
  front/src/Apps/common/Components/Modal/Modal.tsx
  front/src/Apps/common/queries/bsda/queries.ts
  front/src/Apps/common/queries/bsdasri/queries.ts
  front/src/Apps/common/queries/bsdd/queries.ts
  front/src/Apps/common/queries/bsff/queries.ts
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignBsdaModal.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignWork.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterInfo.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasriSecretCode.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterCustomInfo.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/useDownloadPdf.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignAcceptation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignBsff.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignPackagings.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignReception.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/request/RouteBsdaRequestRevision.tsx
  front/src/dashboard/detail/bsda/RouteBSDasView.tsx
  front/src/dashboard/detail/bsff/RouteBsffsView.tsx
  front/src/form/bsda/components/bsdaPicker/BsdaPicker.tsx
  front/src/form/bsda/stepper/BsdaStepList.tsx
  front/src/form/bsdasri/BsdasriStepList.tsx
  front/src/form/bsff/BsffStepList.tsx
  front/src/form/bsff/components/PreviousPackagingsPicker.tsx
Labels: ready for review

#3266 [Tra-13356] Révision sur les annexes 1
  back/src/forms/converter.ts
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  front/src/dashboard/components/RevisionRequestList/bsdd/BsddRequestRevisionCancelationInput.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  libs/back/prisma/src/migrations/20240417141300_bsdd_revision_appendix1/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/shared/constants/src/WASTES.ts
  package.json
Labels: ready for review

#3254 [tra-12745] Ajouter l'information du traitement final sur le registre sortant et exhaustif pour les BSD ayant un BSD suite
  Changelog.md
  apps/queues-runner/src/main.ts
  back/src/bsda/__tests__/operationHook.integration.ts
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/operationHook.ts
  back/src/bsda/registry.ts
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsdasris/__tests__/operationHook.integration.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/edition.ts
  back/src/bsdasris/operationHook.ts
  back/src/bsdasris/registry.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriOperation.integration.ts
  back/src/bsdasris/resolvers/mutations/signBsdasri.ts
  back/src/bsffs/__tests__/operationHook.integration.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/edition/bsffPackagingEdition.ts
  back/src/bsffs/operationHook.ts
  back/src/bsffs/registry.ts
  back/src/bsffs/resolvers/mutations/__tests__/signBsff.integration.ts
  back/src/bsffs/resolvers/mutations/signBsff.ts
  back/src/common/operationCodes.ts
  back/src/forms/__tests__/operationHook.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/edition.ts
  back/src/forms/operationHook.ts
  back/src/forms/registry.ts
  back/src/forms/repository/form/__tests__/delete.integration.ts
  back/src/forms/repository/form/delete.ts
  back/src/forms/repository/form/update.ts
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  back/src/forms/resolvers/mutations/markAsProcessed.ts
  back/src/queue/jobs/__tests__/operationHook.integration.ts
  back/src/queue/jobs/operationHook.ts
  back/src/queue/producers/operationHook.ts
  back/src/registry/columns.ts
  back/src/registry/elastic.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/outgoingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/queries.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  back/src/scripts/bin/addOperationHookJobs.ts
  libs/back/prisma/src/migrations/20240419121739_update_final_operation_model/migration.sql
  libs/back/prisma/src/migrations/20240422092938_create_final_operations_models/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3272 [TRA-9367] Prevents BSDA final destination from revising
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsda.ts
Labels: ready for review

#3280 [tra-10310] fix date de prise en charge initiale dans table Annexe 2
  Changelog.md
  back/src/forms/pdf/generateBsddPdf.tsx
Labels: ready for review

#3298 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#3289 PAOH - corrections recette
  back/src/bsda/validation/refinements.ts
  back/src/bspaoh/converter.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/duplicateBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/publishBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/duplicate.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/schema.ts
  back/src/common/__tests__/datatypes.test.ts
  back/src/common/dataTypes.ts
  back/src/forms/workflow/__tests__/diff.test.ts
  back/src/forms/workflow/diff.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/DeleteModal/DeleteModal.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/form/bspaoh/components/Packagings.module.scss
  front/src/form/bspaoh/components/Packagings.tsx
  front/src/form/bspaoh/steps/Waste.tsx
Labels: ready for review

#3294 [TRA-13500] Updates banner
  Changelog.md
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3297 [TRA-14082] FIX RECETTE: Updates dashboard notifications via notifier
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/hooks/useShowTransportTabs.ts
Labels: ready for review

#3302 Correctif registre paoh
  back/src/registry/converters.ts
  back/src/registry/elastic.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/incomingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/outgoingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/transportedWastes.integration.ts
Labels: ready for review

#3291 Fix infinite rendering in BSDASRI form due to useEffect dependencies list
  front/src/form/bsdasri/components/grouping/BsdasriTableGrouping.tsx
Labels: ready for review

#3287 [TRA-14219] fix status lorsque l'émetteur est un particulier dans les annexes
  Changelog.md
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#3290 [TRA-13089] Ajout update immatriculation dans modale de signature bordereau de synthèse BSDASRI
  Changelog.md
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
Labels: ready for review

#3292 [TRA-14327] Fix redirection après signature BSDASRI groupement par émetteur
  Changelog.md
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasriSecretCode.tsx
Labels: ready for review

#3311 [TRA-10659] Inverser les options de téléchargement du registre .csv et .xls pour éviter les erreurs
  front/src/dashboard/exports/ExportsForm.tsx
Labels: ready for review

#3310 [TRA-14056] Cacher liens PDF sur Annexes/Suite si le bordereau est un brouillon
  Changelog.md
  front/src/Apps/Forms/Components/query.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#3314 Ajout de favicon manquante sur les docs
  apps/doc/static/img/trackdechets.png
Labels: ready for review

#3333 HOTFIX - Fixes companies verification button
  front/src/Apps/Companies/CompanyInfo/CompanyInfo.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
Labels: hotfix

#3312 [TRA-10101] Retirer la possibilité de filtrer le registre par code déchet via le sélecteur
  front/src/dashboard/exports/ExportsForm.tsx
Labels: ready for review

#3334 [TRA-10659] Inverser les options de téléchargement du registre .csv et .xls pour les admins
  front/src/admin/registry/Registry.tsx
Labels: ready for review

#3335 Fix annexe2 grouping issues
  back/src/forms/repository/form/updateAppendix2Forms.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
Labels: hotfix

#3329 [TRA-13944] Permettre un export .xls ou .csv de la liste des établissements avec les membres rattachés
  .gitignore
  Changelog.md
  back/src/common/fileDownload.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryXls.integration.ts
  back/src/routers/downloadRouter.ts
  back/src/users/export/columns.ts
  back/src/users/export/filename.ts
  back/src/users/export/stream.ts
  back/src/users/export/types.ts
  back/src/users/resolvers/Query.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesCsv.integration.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesXls.integration.ts
  back/src/users/resolvers/queries/myCompaniesCsv.ts
  back/src/users/resolvers/queries/myCompaniesXls.ts
  back/src/users/typeDefs/user.queries.graphql
  front/src/Apps/Companies/CompaniesList/CompaniesList.tsx
  front/src/Apps/Companies/common/hooks/useDownloadCompanies.ts
  front/src/Apps/common/Components/DropdownMenu/DropdownMenu.tsx
  front/src/Apps/common/Components/DropdownMenu/dropdownMenuTypes.ts
Labels: ready for review

#3328 Fixes companies layout
  front/src/Apps/Companies/CompaniesRoutes.tsx
Labels: ready for review

#3336 [TRA-14343] Au refus total d'un VHU, ne pas demander de compléter le code / mode de traitement
  Changelog.md
  back/src/bsvhu/typeDefs/bsvhu.mutations.graphql
  back/src/bsvhu/validation.ts
  front/src/common/components/OperationModeSelect.tsx
  front/src/form/bsvhu/Operation.tsx
Labels: ready for review

#3331 [BSDA] L'installation de destination ne peut pas signer l'opération du BSDA si un transporteur N>1 n'a pas signé et a des infos incomplètes
  Changelog.md
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/validation/refinements.ts
Labels: ready for review

#3319 [TRA-12646] Incohérence entre les dates affichées dans l'Aperçu et les dates affichées dans le registre
  back/src/registry/columns.ts
Labels: ready for review

#3354 [TRA-14036] Adds company signature DSFR
  e2e/src/utils/company.ts
  front/src/Apps/Account/fields/AccountFieldCompanyDasriDirectTakeOver.tsx
  front/src/Apps/Account/fields/AccountFieldCompanySecurityCode.tsx
  front/src/Apps/Account/fields/AccountFieldCompanySignatureAutomation.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanySecurityCode.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanySignatureAutomation.tsx
  front/src/Apps/Companies/AccountCompanySecurity.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignature.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureAutomation.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureCode.tsx
  front/src/Apps/Companies/CompanySignature/CompanySignatureDasriDirectTakeOver.tsx
  front/src/Apps/Companies/CompanySignature/companySignature.scss
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
Labels: ready for review

#3353 [tra-14400]Ne pas afficher les pastilles d'alertes pour le profil Lecteur
  Changelog.md
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
Labels: ready for review

#3352 [tra-14401]Renommer Regroupement par Annexe 2 (sous-type de BSDD)
  Changelog.md
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review

#3351 [tra-14397]Renommer Transit par Réexpédition (sous-type de BSDA)
  Changelog.md
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review

#3306 [TRA-13965] Incrémenter les registres Exhaustif, Sortant, Transport, Gestion dès la signature transporteur et le registre entrant dès la signature réception
  back/src/bsda/registry.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/registry.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/registry.ts
  back/src/common/elastic.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/elastic.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/typeDefs/registry.enums.graphql
  back/src/registry/typeDefs/registry.queries.graphql
  back/src/registry/types.ts
Labels: ready for review

#3350 [tra-12994] Ajouter des profils et sous-types de profils (TTR et Installation de traitement) FRONT - T1
  Changelog.md
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAdd.tsx
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/AccountCompanyAddCollector.tsx
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/AccountCompanyAddWasteProcessor.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileInformation.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileSubForm.tsx
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  front/src/Apps/Companies/common/utils.ts
Labels: ready for review

#3345 [TRA-14037] Adds company members DSFR
  e2e/src/utils/roles.ts
  front/src/Apps/Account/fields/forms/AccountFormCompanyInviteNewUser.tsx
  front/src/Apps/Companies/AccountCompanyMember.module.scss
  front/src/Apps/Companies/AccountCompanyMember.tsx
  front/src/Apps/Companies/AccountCompanyMemberList.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembers.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersInvite.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersList.tsx
  front/src/Apps/Companies/CompanyMembers/ContactFormCtaFragment.tsx
  front/src/Apps/Companies/CompanyMembers/companyMembers.scss
  front/src/Apps/Companies/common/queries.ts
Labels: ready for review

#3339 [TRA-13926] Ajout d'une colonne "sous-type" de bordereau dans tous les registres
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/registry.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/registry.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/forms/types.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.enums.graphql
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review

#3357 Updates changelog
  Changelog.md
Labels: ready for review

#3308 Retrait de la possibilité de sélectionner un mode de traitement pour le code non final D9
  Changelog.md
  apps/doc/docs/reference/operationModes.md
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/__tests__/workflow.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriOperation.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/bsvhu/__tests__/validation.integration.ts
  back/src/common/__tests__/operationModes.test.ts
  back/src/common/operationModes.ts
  back/src/common/typeDefs/common.enums.graphql
  back/src/forms/__tests__/validation.integration.ts
  front/src/common/__tests__/operationModes.test.ts
  front/src/common/operationModes.ts
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/runner.ts
  libs/back/scripts/src/scripts/.gitkeep
  libs/back/scripts/src/scripts/20240527094034108_update-d9-operation-code.ts
Labels: ready for review

#3346 [tra-14072] Annexe1: l'émetteur doit être inscrit sur TD
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/validation.ts
Labels: ready for review

#3358 [TRA-14036] Fixes typo
  front/src/Apps/Companies/CompanySignature/CompanySignatureDasriDirectTakeOver.tsx
Labels: ready for review

#3359 Correction du flaky test E2E company.ts
  e2e/src/utils/company.ts
Labels: ready for review

#3347 Ajout d'une action Github pour ajouter un label "ready for merge" après 2 approvals
  .github/workflows/add-ready-to-merge-label.yml
Labels: ready for review, ready to merge

#3344 [TRA-14393] Réinitialiser correctement emitterCompany lors du switch en tre privateIndividual/foreignShip/company
  Changelog.md
  front/src/form/bsdd/Emitter.tsx
Labels: ready for review

#3342 [TRA-14394] Rendre les liens FAQ clickable dans les messages d'erreur
  Changelog.md
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/AccountCompanyAddSiret.tsx
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/anonymous/InvalidSirenePDFError.tsx
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/anonymous/InvalidSirenePDFFormatError.tsx
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/anonymous/InvalidSirenePDFSizeError.tsx
Labels: ready for review, ready to merge

#3315 [TRA-14208] Faire remonter BSD dans dashboard à la création de demande de révision
  Changelog.md
  back/src/bsda/repository/revisionRequest/create.ts
  back/src/forms/repository/formRevisionRequest/createRevisionRequest.ts
Labels: ready for review, ready to merge

#3309 [TRA-14055] Modification des infos transporteur affichées sur BsdCard + leur mise à jour
  Changelog.md
  back/src/bsdasris/typeDefs/bsdasri.objects.graphql
  back/src/forms/repository/form/update.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditForm.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditModal.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/bsda/queries.ts
  front/src/Apps/common/queries/bsdd/queries.ts
  front/src/Apps/common/queries/bspaoh/queries.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/fragments/bsdasri.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/queries/fragments/bsff.ts
  front/src/Apps/common/queries/fragments/bspaoh.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review, ready to merge

#3360 [TRA-13501] Updates banner for the release
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: MEP 4 Juin, ready for review

#3361 [TRA-14036] Fixes company signature
  front/src/Apps/Companies/CompanySignature/CompanySignatureAutomation.tsx
Labels: MEP 4 Juin, ready for review

#3332 [TRA-13421] Rendre obligatoire le champ "Numéro de notification" lorsque la destination ultérieure renseignée est étrangère
  Changelog.md
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/markAsProcessed.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/validation.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
Labels: MEP 4 Juin, ready for review, ready to merge

#3337 [TRA-14282] Ajout du producteur initial dans les bordereaux suite
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/registry.ts
  back/src/registry/resolvers/queries/__tests__/incomingWastes.integration.ts
Labels: MEP 4 Juin, ready for review, ready to merge

#3362 [TRA-14036] Fixes mailing for signature code renewal
  libs/back/mail/src/templates/mustache/notification-renouvellement-code-signature.html
Labels: MEP 4 Juin, ready for review

#3363 [tra-12994]fix bug selection/deselection de sous types
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
Labels: ready for review

#3365 Correctifs révisions bsdasris
  back/src/bsdasris/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/dashboard/components/RevisionRequestList/bsdasri/RhfReviewableField.tsx
  front/src/dashboard/components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/form/bsdasri/components/packagings/RhfPackagings.tsx
  libs/back/mail/src/templates/mustache/pending-revision-request-admin-details.html
Labels: MEP 4 Juin, ready for review, ready to merge
