Repository MTES-MCT/trackdechets, pull requests merged in 2024-07, with the labels that each got.

#3433 [tra-13502]Mise à jour du texte présent dans le bandeau
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3434 [TRA-14348] Corrections de recette: wording & règles de révision sur le DASRI de sythèse
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/dashboard/components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
Labels: ready to merge

#3436 [TRA-11334] Une déchetterie (WASTE_CENTER) non vérifiée devrait pouvoir créer un BSDA COLLECTION_2710
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/createDraft.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/common/validation/zod/refinement.ts
Labels: ready to merge

#3437 Recette validation BSFF
  back/src/bsffs/database.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/publishBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/signBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/updateBsff.ts
  back/src/bsffs/validation/bsff/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsff/refinements.ts
  back/src/bsffs/validation/bsff/rules.ts
  back/src/bsffs/validation/bsff/schema.ts
Labels: ready for review

#3440 HOTFIX - les poids et volumes ne peuvent être 0 dès la création
  back/src/bsffs/converter.ts
  back/src/bsffs/database.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/queries/__tests__/bsff.integration.ts
Labels: hotfix, ready for review

#3442 HOTFIX - Pagination infinie sur l'export des établissements lorsque plus de 100 établissements
  back/src/users/export/stream.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesCsv.integration.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesXls.integration.ts
  back/src/users/resolvers/queries/myCompaniesCsv.ts
  back/src/users/resolvers/queries/myCompaniesXls.ts
Labels: hotfix, ready for review, ready to merge

#3448 [tra-14358]Mise à jour DSFR de la modale de révision BSDA
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/BsdaRequestRevisionCancelationInput.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.module.scss
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/RhfPackagings.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
Labels: ready for review

#3452 [TRA-14520] Ajout de la date et de l'heure d'édition dans les PDFs
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/bspaoh/pdf/components/BspaohPdf.tsx
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/common/__tests__/helpers.test.ts
  back/src/common/helpers.ts
  back/src/forms/pdf/generateBsddPdf.tsx
Labels: ready for review, ready to merge

#3446 [TRA-13879] Suppression de colonnes dans les registres
  back/src/__tests__/factories.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/__tests__/factories.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/registry.ts
  back/src/bspaoh/__tests__/registry.integration.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/__tests__/registry.integration.ts
  back/src/bsvhu/registry.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/resolvers/queries/__tests__/queries.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review, breaking change, ready to merge

#3455 HOTFIX: Ajoute wasteProcessorTypes and collectorTypes à la query companyPrivateInfos
  back/src/companies/resolvers/queries/__tests__/companyInfos.test.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/resolvers/queries/companyInfos.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.objects.graphql
Labels: hotfix, ready to merge

#3449 [tra-14547]Renommer le profil TTR par Installation de Tri, transit regroupement de déchets y compris non classée et supprimer les sous-titres Déchets concernés et traités à la création ET modification d'un établissement
  e2e/src/plans/companies.spec.ts
  e2e/src/utils/company.ts
  front/src/Apps/Companies/CompanyInfo/CompanyProfileSubForm.tsx
  front/src/Apps/Companies/common/utils.ts
Labels: ready for review

#3458 [tra-14386]Améliorer l'affichage d'une révision par 0
  front/src/Apps/Dashboard/Components/Revision/RevisionDetail/RevisionDetail.tsx
Labels: ready for review

#3460 [tra-14391]Demande d'annulation : ajouter les statuts demandeurs et à approuver sur le BSDD, BSDA et DASRI
  front/src/Apps/Dashboard/Components/Revision/RevisionList/RevisionList.tsx
Labels: ready for review

#3462 [tra-14093]Ajouter la possibilité de Supprimer le VHU après signature de l'émetteur, pour le producteur uniquement
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#3467 [tra-14237]Rendre sticky le menu de navigation principale en haut et le menu de gauche
  front/src/Apps/common/Components/SideBar/sidebar.scss
  front/src/Apps/common/Components/layout/Header.module.scss
Labels: ready for review

#3454 [tra-14456] design fixes
  front/src/Apps/Dashboard/Components/Badge/badge.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/RouteControlPdf.tsx
Labels: ready for review

#3466 [tra-14506]Transmettre le n° de TVA intracommunautaire au backend lors d'une destination ultérieure manuelle
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
  front/src/form/common/components/company/ExtraEuropeanCompanyManualInput.tsx
Labels: ready for review

#3469 [tra-14386]fix recette : enlever le 0 qui apparait sous le champ poids lorsque l'on y renseigne 0
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
Labels: ready for review

#3470 [tra-14237]fix recette: fix z-index on sticky header
  front/src/Apps/common/Components/layout/Header.module.scss
Labels: ready for review

#3472 [tra-14456]fix recette design
  front/src/Apps/Dashboard/Components/Badge/badge.scss
Labels: ready for review

#3450 [tra-12475]Vider le Company Selector du SIRET / Raison sociale qui a été renseigné après autorisation pour la délégation de signature automatique Annexe 1
  front/src/Apps/common/Components/CompanySelector/CompanySelector.tsx
Labels: ready for review, ready to merge

#3468 [TRA_14492] Supprimer le type de profil Crémation et ne conserver que le sous-type de l'Installation de traitement
  Changelog.md
  back/src/__tests__/factories.integration.ts
  back/src/__tests__/factories.ts
  back/src/__tests__/oidc.integration.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bspaoh.integration.ts
  back/src/bspaoh/__tests__/factories.integration.ts
  back/src/bspaoh/__tests__/factories.ts
  back/src/bspaoh/examples/workflows/acheminementDirect.ts
  back/src/bspaoh/examples/workflows/acheminementDirectAvecDepot.ts
  back/src/bspaoh/examples/workflows/acheminementDirectDepuisBrouillon.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createDraftBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/duplicateBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/signBspaohOperation.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/signBspaohReception.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/updateBspaoh.integration.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/dynamicRefinements.ts
  back/src/companies/resolvers/mutations/__tests__/createCompany.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateCompany.integration.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/mutations/updateCompany.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/typeDefs/company.enums.graphql
  back/src/companies/validation.ts
  e2e/src/plans/companies.spec.ts
  e2e/src/utils/company.ts
  front/src/Apps/Companies/common/utils.ts
  front/src/form/bspaoh/steps/Destination.tsx
  libs/back/scripts/src/scripts/20240717071507541_crematoriums-to-subtype-cremation.ts
Labels: ready for review, ready to merge

#3465 Bsds - status check
  back/src/bsda/repository/bsda/update.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsdasris/repository/bsdasri/update.ts
  back/src/bsdasris/resolvers/mutations/signBsdasri.ts
  back/src/bsffs/resolvers/mutations/signBsff.ts
  back/src/bspaoh/repository/bspaoh/update.ts
  back/src/bspaoh/resolvers/mutations/sign.ts
  back/src/bsvhu/repository/bsvhu/update.ts
  back/src/bsvhu/resolvers/mutations/sign.ts
  back/src/forms/repository/form/update.ts
  back/src/forms/resolvers/mutations/importPaperForm.ts
  back/src/forms/resolvers/mutations/markAsAccepted.ts
  back/src/forms/resolvers/mutations/markAsProcessed.ts
  back/src/forms/resolvers/mutations/markAsReceived.ts
  back/src/forms/resolvers/mutations/markAsResealed.ts
  back/src/forms/resolvers/mutations/markAsResent.ts
  back/src/forms/resolvers/mutations/markAsSealed.ts
  back/src/forms/resolvers/mutations/markAsTempStored.ts
  back/src/forms/resolvers/mutations/markAsTempStorerAccepted.ts
  back/src/forms/resolvers/mutations/signEmissionForm.ts
  back/src/forms/resolvers/mutations/signTransportForm.ts
  back/src/forms/resolvers/mutations/signedByTransporter.ts
Labels: ready for review, ready to merge

#3447 Registre - corrections et améliorations relatives aux informations de traitement final
  Changelog.md
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/registry.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/elastic.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review, ready to merge

#3370 Partial dump script
  CONTRIBUTING.md
  libs/back/partial-backup/.eslintrc.json
  libs/back/partial-backup/project.json
  libs/back/partial-backup/src/main.ts
  libs/back/partial-backup/src/pipelines.ts
  libs/back/partial-backup/src/traversals.ts
  libs/back/partial-backup/tsconfig.app.json
  libs/back/partial-backup/tsconfig.json
Labels: ready for review, ready to merge

#3477 [TRA-14480] refacto validation VHU
  Changelog.md
  back/src/bsda/resolvers/mutations/__tests__/createBsdaTransporter.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/updateBsdaTransporter.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsvhu.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsffTransporter.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffTransporter.integration.ts
  back/src/bsffs/validation/bsff/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsff/rules.ts
  back/src/bsffs/validation/bsff/schema.ts
  back/src/bsffs/validation/bsffPackaging/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsffPackaging/schema.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/schema.ts
  back/src/bsvhu/__tests__/recipify.integration.ts
  back/src/bsvhu/__tests__/sirenify.integration.ts
  back/src/bsvhu/__tests__/validation.integration.ts
  back/src/bsvhu/converter.ts
  back/src/bsvhu/recipify.ts
  back/src/bsvhu/resolvers/BsvhuMetadata.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createDraftBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/publishBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/signBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/create.ts
  back/src/bsvhu/resolvers/mutations/duplicate.ts
  back/src/bsvhu/resolvers/mutations/publish.ts
  back/src/bsvhu/resolvers/mutations/sign.ts
  back/src/bsvhu/resolvers/mutations/update.ts
  back/src/bsvhu/sirenify.ts
  back/src/bsvhu/validation.ts
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/constants.ts
  back/src/bsvhu/validation/helpers.ts
  back/src/bsvhu/validation/index.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/schema.ts
  back/src/bsvhu/validation/sirenify.ts
  back/src/bsvhu/validation/types.ts
  back/src/common/validation/intermediaries.ts
  back/src/common/validation/zod/refinement.ts
  back/src/common/validation/zod/schema.ts
  back/src/common/validation/zod/transformers.ts
  e2e/src/utils/bsvhu.ts
  e2e/src/utils/time.ts
  front/src/Apps/Companies/common/utils.ts
  libs/shared/constants/src/WASTES.ts
Labels: ready for review, ready to merge

#3418 [TRA-14477] Feat/reception acceptation modal
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/FormSummary.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/FormWasteSummary.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignForm.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignFormModal.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
  front/src/Apps/common/queries/bsdd/queries.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/common/helper.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsAccepted.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsProcessed.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsReceived.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsTempStored.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsTempStorerAccepted.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSDD/index.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/dashboard/detail/common/Components.tsx
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/appendix1Producer/form.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
  front/src/form/bsdd/utils/queries.ts
Labels: ready for review, ready to merge

#3456 [TRA-14464] Séparation des adresses des registres en 4 champs: Libellé, Code postal, Commune, Pays
  back/src/__tests__/factories.ts
  back/src/__tests__/utils.test.ts
  back/src/bsda/__tests__/elastic.integration.ts
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/elastic.integration.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/__tests__/elastic.integration.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/bsffs/registry.ts
  back/src/bspaoh/__tests__/elastic.integration.ts
  back/src/bspaoh/__tests__/registry.integration.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/__tests__/elastic.integration.ts
  back/src/bsvhu/__tests__/registry.integration.ts
  back/src/bsvhu/registry.ts
  back/src/common/__tests__/addresses.test.ts
  back/src/common/addresses.ts
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/converter.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  back/src/utils.ts
Labels: ready for review, ready to merge

#3441 Admin BSD
  back/src/bsds/resolvers/index.ts
  back/src/bsds/resolvers/queries/__tests__/bsd.integration.ts
  back/src/bsds/resolvers/queries/bsd.ts
  back/src/bsds/typeDefs/private/bsd.queries.graphql
  back/src/forms/resolvers/queries/formPdf.ts
  front/src/Apps/routes.ts
  front/src/admin/Admin.tsx
  front/src/admin/bsd/BsdAdmin.tsx
  front/src/admin/bsd/BsdDetailContent.tsx
  front/src/common/contexts/PermissionsContext.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, ready to merge

#3464 [TRA-13961] Ajout des noms usuels de l'expéditeur, des transporteurs ainsi que de la destination sur le registre exhaustif
  back/src/registry/__tests__/wastes.integration.ts
  back/src/registry/columns.ts
  back/src/registry/converters.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  back/src/registry/wastes.ts
Labels: ready for review

#3481 [tra-14358]fix recette: révision bsda - le code de l'operation n'était plus sélectionnable
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
Labels: ready to merge, fix de recette

#3471 [tra-14730]Retours sur le composant Modale
  front/src/Apps/Dashboard/Components/DeleteModal/DeleteModal.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsdSuiteValidation.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignFormModal.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/common/Components/DataList/DsfrDataList.module.scss
  front/src/Apps/common/Components/Modal/DsfrModal.tsx
  front/src/Apps/common/Components/Modal/Modal.module.scss
  front/src/Apps/common/Components/Modal/Modal.tsx
  front/src/Apps/common/Components/Modal/modal.scss
  front/src/Apps/common/Components/search/WasteTreeModal.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignBsdaModal.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignBsff.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignPackagings.tsx
  front/src/dashboard/components/BSDList/BSPaoh/WorkflowAction/SignBspaohModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignBsvhuModal.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bspaoh/FormContainer.tsx
Labels: ready for review, ready to merge

#3484 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#3483 [TRA-14634] Correctifs de recette sur les quantités refusées
  back/src/bsda/mails/__tests__/refused.integration.ts
  back/src/bspaoh/mails/__tests__/refused.integration.ts
  back/src/bspaoh/mails/refused.ts
  back/src/common/helpers.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/mail/__tests__/renderFormRefusedEmail.integration.ts
  back/src/forms/mail/renderFormRefusedEmail.ts
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/forms/resolvers/mutations/__tests__/markAsTempStored.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsTempStorerAccepted.integration.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/utils.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/dashboard/detail/common/Components.tsx
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/refus-partiel-dechet.html
  libs/back/mail/src/templates/mustache/refus-total-dechet.html
Labels: ready for review, ready to merge

#3486 [tra-14730]quick fix design
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
  front/src/dashboard/detail/common/BSDDetailContent.module.scss
Labels: fix de recette

#3487 [TRA-14634] Correctifs sur les quantités refusées
  back/src/companies/resolvers/queries/searchCompanies.ts
  back/src/forms/converter.ts
  back/src/forms/mail/__tests__/renderFormRefusedEmail.integration.ts
  back/src/forms/mail/renderFormRefusedEmail.ts
  back/src/forms/resolvers/forms/__tests__/stateSummary.integration.ts
  back/src/forms/resolvers/forms/stateSummary.ts
  back/src/forms/resolvers/mutations/__tests__/markAsReceived.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/resolvers/mutations/markAsReceived.ts
  back/src/forms/resolvers/mutations/markAsResealed.ts
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
Labels: ready for review

#3488 [tra-14363] FIX - les champs doivent être requis
  back/src/bsda/validation/rules.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
Labels: ready for review

#3485 [TRA-14634] Fixes quantity refused preview / form
  front/src/Apps/Dashboard/Components/Validation/BSDD/FormWasteSummary.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, ready to merge

#3490 [TRA-14634] Fix dashboard displayed weight
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
Labels: ready for review, fix de recette

#3491 [TRA-14634] Fixes overflow of tables
  front/src/scss/Tables.scss
Labels: ready for review, fix de recette

#3457 [TRA-13845] Correction de la dénomination du code de traitement non final D12 par D13
  Changelog.md
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/examples/fixtures.ts
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriGrouping.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createDraftBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriOperation.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasriSynthesis.integration.ts
  back/src/bsdasris/resolvers/mutations/utils.ts
  back/src/bsdasris/typeDefs/bsdasri.enums.graphql
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  back/src/bsdasris/typeDefs/bsdasri.objects.graphql
  back/src/bsdasris/validation.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/company/query.ts
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
  front/src/form/bsdasri/components/grouping/BsdasriTableGrouping.tsx
  front/src/form/bsdasri/steps/Operation.tsx
  libs/back/scripts/src/scripts/20240711141357215_dasri-D12-D13.ts
  libs/shared/constants/src/DASRI_CONSTANTS.ts
Labels: ready for review, ready to merge

#3494 [tra-14357_14358]revisions fix (useNavigate en trop)
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
Labels: fix de recette

#3496 [TRA 14865] Hotfix - revision quantity decimal
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
Labels: hotfix, ready for review
