Repository MTES-MCT/trackdechets, pull requests merged in 2024-02, with the labels that each got.

#3055 [TRA-12092][BSDA] Migrer les données transporteur dans une table à part (refacto interne du code)
  Changelog.md
  back/src/activity-events/bsda/reducer.ts
  back/src/bsda/__tests__/elastic.integration.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/converter.ts
  back/src/bsda/database.ts
  back/src/bsda/elastic.ts
  back/src/bsda/mails/refused.ts
  back/src/bsda/pdf/generator.tsx
  back/src/bsda/permissions.ts
  back/src/bsda/registry.ts
  back/src/bsda/repository/bsda/create.ts
  back/src/bsda/repository/bsda/delete.ts
  back/src/bsda/repository/bsda/findUnique.ts
  back/src/bsda/repository/bsda/update.ts
  back/src/bsda/resolvers/Bsda.ts
  back/src/bsda/resolvers/BsdaMetadata.ts
  back/src/bsda/resolvers/BsdaRevisionRequest.ts
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  back/src/bsda/resolvers/mutations/delete.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/resolvers/mutations/publish.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsda/resolvers/mutations/update.ts
  back/src/bsda/resolvers/queries/__tests__/bsdas.integration.ts
  back/src/bsda/resolvers/queries/bsda.ts
  back/src/bsda/resolvers/queries/bsdaPdf.ts
  back/src/bsda/resolvers/queries/bsdas.ts
  back/src/bsda/types.ts
  back/src/bsda/validation/__tests__/transformers.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/helpers.ts
  back/src/bsda/validation/index.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsda/validation/sirenify.ts
  back/src/bsda/where.ts
  back/src/bsds/resolvers/mutations/__tests__/createPdfAccessToken.integration.ts
  back/src/bsds/resolvers/mutations/createPdfAccessToken.ts
  back/src/companies/recipify.ts
  back/src/forms/converter.ts
  back/src/forms/resolvers/mutations/markAsResent.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/__tests__/where.dates.integration.ts
  back/src/registry/__tests__/where.transporter.integration.ts
  back/src/registry/elastic.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/incomingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/managedWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/outgoingWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/transportedWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryCsv.integration.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryXls.integration.ts
  libs/back/prisma/src/migrate/migrations/165_migrate_to_bsda_transporter.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#2986 [TRA-10472] Correctifs sur un BSD qui est révisé pour un code de traitement final
  back/src/common/__tests__/operationModes.test.ts
  back/src/common/operationCodes.ts
  back/src/common/operationModes.ts
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  libs/back/prisma/src/migrate/migrations/166_update_bsdd_with_final_operation_code.sql
Labels: ready for review

#3054 [tra-13346]Implémenter les Révisions FRONT
  front/src/Apps/Dashboard/Components/Badge/Badge.tsx
  front/src/Apps/Dashboard/Components/Badge/badgeTypes.ts
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/Components/Revision/ActorStatus/ActorSatus.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionApproveFragment.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionCancelFragment.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionDetail/RevisionDetail.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionDetail/RevisionDetailList.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionDetail/TraderAndBrokerDetail.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionList/RevisionList.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionList/revisionList.scss
  front/src/Apps/Dashboard/Components/Revision/RevisionModal.tsx
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/Components/Revision/revisionModal.scss
  front/src/Apps/Dashboard/Components/Revision/revisionServices.ts
  front/src/Apps/Dashboard/Components/Revision/wordingsRevision.ts
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/Icons/Icons.tsx
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/queries/reviews/BsdaReviewQuery.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/Apps/common/types/commonTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Apps/routes.ts
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
  front/src/dashboard/Dashboard.tsx
  front/src/dashboard/DashboardTabs.tsx
  front/src/dashboard/bsds/review/RouteBsdsReview.tsx
  front/src/dashboard/bsds/review/index.ts
  front/src/dashboard/components/RevisionRequestList/bsda/BsdaRevisionRequestList.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/BsdaRevisionRequestTable.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaCancelRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaConsultRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaRevisionAction.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaRevisionStatus.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/index.ts
  front/src/dashboard/components/RevisionRequestList/bsdd/BsddRevisionRequestList.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/BsddRevisionRequestTable.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddCancelRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddConsultRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddRevisionAction.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddRevisionStatus.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/RevisionField.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/index.ts
  front/src/dashboard/components/RevisionRequestList/bsdd/index.ts
Labels: ready for review

#3061 [tra-13808] BSDA - 160305*
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  libs/shared/constants/src/WASTES.ts
Labels: ready for review

#3060 [tra-13313] BSDA - Flexibilisation de règles
  back/src/bsda/validation/rules.ts
  front/src/form/bsda/FormContainer.tsx
Labels: ready for review

#3057 [TRA-13753] Retirer la possibilité de faire du multimodal pour le BSD de tournée dédiée
  front/src/form/bsdd/Emitter.tsx
  front/src/form/bsdd/Transporter.tsx
Labels: ready for review

#3062 [tra-13354] BSDA - eco organisme
  back/prisma/scripts/add-bsda-ecoorganisme.ts
  back/src/bsda/elastic.ts
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/permissions.ts
  back/src/bsda/validation/dynamicRefinements.ts
  back/src/common/validation/siret.ts
  back/src/companies/typeDefs/company.objects.graphql
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  front/src/form/bsda/components/eco-organismes/EcoOrganismes.tsx
  front/src/form/bsda/stepper/initial-state.ts
  front/src/form/bsda/stepper/steps/Emitter.tsx
  libs/back/prisma/src/migrate/migrations/165_ecoorganisme_bsda.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3066 [TRA-8968] Adds Header V2
  Changelog.md
  e2e/src/plans/roles.spec.ts
  e2e/src/utils/user.ts
  front/public/marianne.svg
  front/public/trackdechets-small.png
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/common/Components/SideBar/sidebar.scss
  front/src/Apps/common/Components/layout/Header.module.scss
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Apps/routes.ts
  front/src/account/Account.tsx
  front/src/account/AccountCompanyAdd.tsx
  front/src/account/AccountCompanyAdvanced.tsx
  front/src/account/AccountCompanyList.tsx
  front/src/account/AccountCompanyOrientation.tsx
  front/src/account/AccountMenu.tsx
  front/src/account/CompaniesMenu.tsx
  front/src/account/CompaniesRoutes.tsx
  front/src/admin/Admin.tsx
  front/src/common/config.ts
  front/src/dashboard/Dashboard.tsx
  front/src/scss/Constants.scss
  package-lock.json
  package.json
Labels: ready for review

#3071 Fixes header V2
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review

#3059 DIVERS - Améliorations de performance
  back/src/bsda/dataloader.ts
  back/src/bsda/resolvers/BsdaMetadata.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/dynamicRefinements.ts
  back/src/bsda/validation/helpers.ts
  back/src/bsda/validation/index.ts
  back/src/bsda/validation/schema.ts
  back/src/common/validation/intermediaries.ts
  back/src/forms/dataloader.ts
  back/src/forms/mail/renderFormRefusedEmail.ts
  back/src/forms/pdf/generateBsddPdf.tsx
  back/src/forms/permissions.ts
  back/src/forms/repository/form/delete.ts
  back/src/forms/repository/form/update.ts
  back/src/forms/resolvers/InitialForm.ts
  back/src/forms/resolvers/forms/grouping.ts
  back/src/forms/resolvers/queries/formPdf.ts
  back/src/permissions.ts
  back/src/queue/jobs/deleteBsd.ts
  back/src/registry/resolvers/queries/wastesRegistryCsv.ts
  back/src/registry/resolvers/queries/wastesRegistryXls.ts
  back/src/server.ts
  back/src/types.ts
  back/src/users/dataloaders.ts
  scripts/deploy-db.sh
Labels: ready for review

#3064 [TRA-13679] Unplug dash v1
  front/src/dashboard/Dashboard.scss
  front/src/dashboard/Dashboard.tsx
  front/src/dashboard/DashboardTabs.scss
  front/src/dashboard/DashboardTabs.tsx
  front/src/dashboard/bsds/act/RouteBsdsAct.tsx
  front/src/dashboard/bsds/act/assets/blankslateAct.svg
  front/src/dashboard/bsds/act/index.ts
  front/src/dashboard/bsds/drafts/RouteBsdsDrafts.tsx
  front/src/dashboard/bsds/drafts/assets/blankslateDrafts.svg
  front/src/dashboard/bsds/drafts/index.ts
  front/src/dashboard/bsds/follow/RouteBsdsFollow.tsx
  front/src/dashboard/bsds/follow/assets/blankslateFollow.svg
  front/src/dashboard/bsds/follow/index.ts
  front/src/dashboard/bsds/history/RouteBsdsHistory.tsx
  front/src/dashboard/bsds/history/assets/blankslateHistory.svg
  front/src/dashboard/bsds/history/index.ts
  front/src/dashboard/bsds/index.ts
  front/src/dashboard/components/BSDList/BSDActions.module.scss
  front/src/dashboard/components/BSDList/BSDCards/BSDCards.module.scss
  front/src/dashboard/components/BSDList/BSDCards/BSDCards.tsx
  front/src/dashboard/components/BSDList/BSDCards/index.ts
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/BSDDActions.tsx
  front/src/dashboard/components/BSDList/BSDD/index.tsx
  front/src/dashboard/components/BSDList/BSDDropdown.tsx
  front/src/dashboard/components/BSDList/BSDList.module.scss
  front/src/dashboard/components/BSDList/BSDList.tsx
  front/src/dashboard/components/BSDList/BSDTable/BSDTable.tsx
  front/src/dashboard/components/BSDList/BSDTable/index.ts
  front/src/dashboard/components/BSDList/BSDTypeFilter.scss
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/BSDaActions.tsx
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/PublishBsda.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/index.ts
  front/src/dashboard/components/BSDList/BSDa/index.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/BSDasriActions.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/index.ts
  front/src/dashboard/components/BSDList/BSDasri/index.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/BsffActions.tsx
  front/src/dashboard/components/BSDList/BSFF/index.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/BSVhuActions.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/PublishBsvhu.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/index.ts
  front/src/dashboard/components/BSDList/BSVhu/index.tsx
  front/src/dashboard/components/BSDList/TextInputFilter.tsx
  front/src/dashboard/components/BSDList/columns.tsx
  front/src/dashboard/components/BSDList/index.ts
  front/src/dashboard/transport/collected/RouteTransportCollected.tsx
  front/src/dashboard/transport/collected/assets/blankslateCollected.svg
  front/src/dashboard/transport/collected/index.ts
  front/src/dashboard/transport/index.ts
  front/src/dashboard/transport/to-collect/RouteTransportToCollect.tsx
  front/src/dashboard/transport/to-collect/assets/blankslateToCollect.svg
  front/src/dashboard/transport/to-collect/index.ts
Labels: ready for review

#3077 Fixes a refresh on BSDA creation / update
  front/src/Apps/Dashboard/Components/DeleteModal/DeleteModal.tsx
  front/src/Apps/Dashboard/Components/Duplicate/useDuplicate.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSDD/BSDDActions/useDuplicate.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsAccepted.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsProcessedModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsResealedModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsSealed.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsTempStorerAccepted.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ReceivedInfo.tsx
  front/src/dashboard/components/BSDList/BSDa/BSDaActions/useDuplicate.ts
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignWork.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/useDuplicate.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RoutePublishBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/DeleteModal.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/useDuplicate.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/PublishBsff.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignAcceptation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignReception.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/useDuplicate.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
  front/src/form/bsda/stepper/BsdaStepList.tsx
  front/src/form/bsdd/StepList.tsx
Labels: ready for review

#3069 Changelog
  Changelog.md
Labels: ready for review

#3082 [TRA-13612] Fixes actors name ellipsis
  front/src/Apps/Dashboard/Components/Actors/Actors.tsx
  front/src/Apps/Dashboard/Components/Actors/actors.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/WasteDetails/wasteDetails.scss
Labels: ready for review

#3090 [TRA-13612] Design fixes
  front/src/Apps/Dashboard/Components/Actors/Actors.tsx
  front/src/Apps/Dashboard/Components/Actors/actors.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
Labels: ready for review

#3089 Correction de la réindexation admin: parsing des BSD legacy en "TD-"
  back/src/bsds/indexation/__tests__/reindexBsdsUtils.test.ts
  back/src/bsds/indexation/reindexBsdsUtils.ts
Labels: ready for review

#3088 add -1 index on mongodb createdAt events
  back/src/events/mongodb.ts
Labels: ready for review

#3079 Améliorations diverses dans la vérification des entreprises (admin)
  back/src/companies/resolvers/mutations/__tests__/createCompany.integration.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/mutations/verifyCompany.ts
  back/src/companies/resolvers/mutations/verifyCompanyByAdmin.ts
  back/src/companies/typeDefs/private/company.enums.graphql
  back/src/companies/validation.ts
  front/src/admin/reindex/Reindex.tsx
  front/src/admin/verification/CompaniesVerificationTable.tsx
  front/src/admin/verification/actions/CompanyVerificationActions.tsx
  front/src/admin/verification/actions/CompanyVerifyModal.tsx
  front/src/admin/verification/actions/SendVerificationCodeLetterModal.tsx
  libs/back/prisma/src/migrate/migrations/168_auto_verification_mode.sql
  libs/back/prisma/src/schema.prisma
  libs/shared/constants/src/COMPANY_CONSTANTS.ts
Labels: ready for review

#3092 [TRA-13833] Renommer le filtre rapide "N° de BSD / contenant" par "N° libre / BSD / contenant", et corriger le CSS
  e2e/src/plans/quickFilters.spec.ts
  e2e/src/utils/dashboardFilters.ts
  front/src/Apps/common/Components/Filters/QuickFilter.tsx
  front/src/Apps/common/Components/Filters/QuickFilters.tsx
  front/src/Apps/common/Components/Filters/quickFilter.scss
  front/src/Apps/common/Components/Filters/quickFilters.scss
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review

#3093 [TRA-13642] Adds the possibility to view members for non-admin
  front/src/account/AccountCompany.tsx
  front/src/account/AccountCompanyMember.tsx
  front/src/account/AccountCompanyMemberList.tsx
Labels: ready for review

#3095 Hotfix release 2024.2.1 Bsda Transporters
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/queries/__tests__/bsdas.integration.ts
  back/src/bsda/resolvers/queries/bsdas.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsda/where.ts
  libs/back/prisma/src/migrate/migrations/168_add_bsda_transporterOrgIds.sql
  libs/back/prisma/src/schema.prisma
Labels: hotfix

#3097 Hotfix query Bsdas transporter
  back/src/bsda/resolvers/queries/__tests__/bsdas.integration.ts
  back/src/bsda/resolvers/queries/bsdas.ts
Labels: hotfix

#3087 [TRA-13891] Refacto & documentation validation BSDA
  Changelog.md
  back/src/activity-events/bsda/reducer.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/resolvers/BsdaMetadata.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/resolvers/mutations/publish.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsda/resolvers/mutations/update.ts
  back/src/bsda/types.ts
  back/src/bsda/validation/__tests__/helpers.integration.ts
  back/src/bsda/validation/__tests__/rules.integration.ts
  back/src/bsda/validation/__tests__/sirenify.integration.ts
  back/src/bsda/validation/__tests__/transformers.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/dynamicRefinements.ts
  back/src/bsda/validation/helpers.ts
  back/src/bsda/validation/index.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsda/validation/sirenify.ts
  back/src/bsda/validation/transformers.ts
  back/src/bsda/validation/types.ts
  back/src/common/validation/intermediaries.ts
  back/src/common/validation/siret.ts
Labels: ready for review

#3109 [tra-13924/tra-13793]Ajouter la possibilité de Réviser le BSDD aprèssignature du transporteur / Ajouter la possibilité de Supprimer le BSDD après signature de l'émetteur, pour le producteur
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: hotfix, ready for review

#3111 [tra-13924/tra-13793]Ajouter la possibilité de Réviser le BSDD après signature du transporteur / Ajouter la possibilité de Supprimer le BSDD après signature de l'émetteur, pour le producteur
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: hotfix

#3102 [TRA-13642] Fixes myCompanies not returning every members
  back/src/companies/resolvers/CompanyPrivate.ts
Labels: ready for review

#3094 [TRA-13277] Nouveau statut STANDBY pour les entreprises qui n'ont pas pu être vérifiées
  back/src/companies/resolvers/Mutation.ts
  back/src/companies/resolvers/mutations/__tests__/standbyCompanyByAdmin.integration.ts
  back/src/companies/resolvers/mutations/standbyCompanyByAdmin.ts
  back/src/companies/typeDefs/company.enums.graphql
  back/src/companies/typeDefs/private/company.inputs.graphql
  back/src/companies/typeDefs/private/company.mutations.graphql
  front/src/admin/Admin.tsx
  front/src/admin/reindex/Reindex.tsx
  front/src/admin/user/anonymizeUser.tsx
  front/src/admin/verification/CompaniesVerificationTable.scss
  front/src/admin/verification/CompaniesVerificationTable.tsx
  front/src/admin/verification/actions/CompanyVerificationActions.tsx
  front/src/admin/verification/actions/CompanyVerifyModal.module.scss
  libs/back/prisma/src/migrate/migrations/169_standby_verification_status.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3110 [TRA-13714] Removes sign button for producer of BSDA
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#3106 [TRA-13921] Adds permissions check on detail views
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  front/src/dashboard/detail/bsdasri/BsdasriDetailContent.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/dashboard/detail/bsff/BsffDetailContent.tsx
Labels: ready for review

#3112 Renommage du script de migration
  libs/back/prisma/src/migrate/migrations/170_standby_verification_status.sql
Labels: ready for review

#3105 [TRA-13874] Adds help sections on the help menu
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review

#3101 [tra-11634]Retirer le champ 'Numéro de notification ou de document' lorsque l'entreprise est française
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
Labels: ready for review

#3120 [tra-13411]Afficher le statut avec rupture de traçabilité lorsque mentionné lors du traitement
  front/src/Apps/Dashboard/Components/Badge/badge.test.tsx
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/queries/fragments/bsff.ts
Labels: ready for review

#3121 [tra-11634]déplacer le champs en dessous de email, afficher le champ lorsqu'un vatNumber est saisi
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
Labels: ready for review

#3116 [tra-13799]Vider les champs Tél & Mail de l'émetteur lorsque je sélectionne Particulier sur un BSDD
  front/src/form/bsdd/Emitter.tsx
Labels: ready for review

#3123 [TRA-13921] Fixes some reader permissions
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#3126 [tra-13774] fix bouton supprimer uniquement pour producteur (point 1) + fix bouton secondaire faire signer (point 2)
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: bug, ready for review

#3127 [tra-13504]Remonter le numéro d'agrément démolisseur lors de la sélection de l'émetteur à la création d'un BSVHU
  front/src/Apps/common/queries/company/query.ts
Labels: ready for review

#3129 [tra-11678]Afficher le conditionnement précisé dans la révision lorsque le conditionnement Autres est sélectionné
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
Labels: ready for review
