Repository MTES-MCT/trackdechets, pull requests merged in 2024-11, with the labels that each got.

#3708 [TRA-15241] Fixes companies layout
  front/src/Apps/Companies/CompaniesRoutes.tsx
Labels: ready for review

#3710 [TRA-15325] Updates sign reception text
  front/src/Apps/Dashboard/Validation/BSDD/SignReception.tsx
Labels: ready for review

#3702 [TRA-15350] Fix favicons / style imports from react-dsfr library
  front/index.html
  front/project.json
  front/public/android-chrome-192x192.png
  front/public/android-chrome-512x512.png
  front/public/apple-touch-icon.png
  front/public/favicon.ico
  front/public/favicon.svg
  front/public/manifest.json
  front/public/manifest.webmanifest
Labels: dependencies, ready for review, ready to merge

#3712 [tra-13234]Ajouter des mentions lors des choix transit et groupement
  front/src/form/bsda/stepper/steps/Type.tsx
Labels: ready for review, ready to merge

#3715 [TRA-15371] Affichage de l'icône d'immatriculation dans l'onglet "A Collecter"
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
Labels: ready for review, ready to merge

#3703 [TRA-14961] La mention ADR d'un BSDD n'est plus dupliquée
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
Labels: ready for review

#3711 [tra-15297]display generic alert error on paoh/vhu tabs
  back/src/bspaoh/permissions.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createDraftBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/publishBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/updateBspaoh.integration.ts
  back/src/bsvhu/permissions.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createDraftBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/publishBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/FormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Forms/Components/FormStepsTabs/FormStepsTabs.tsx
Labels: ready for review, ready to merge

#3714 [TRA-14818] Création d'un nouveau champ pour distinguer la mention ADR de la "Mention au titre des règlements RID, ADNR, IMDG"
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/__tests__/form-converter.test.ts
  back/src/forms/compat.ts
  back/src/forms/converter.ts
  back/src/forms/edition.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/registry.ts
  back/src/forms/resolvers/forms/stateSummary.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/mutations.ts
  back/src/forms/resolvers/mutations/__tests__/signEmissionForm.integration.ts
  back/src/forms/resolvers/mutations/markAsResealed.ts
  back/src/forms/resolvers/mutations/markAsResent.ts
  back/src/forms/resolvers/mutations/markAsTempStored.ts
  back/src/forms/resolvers/mutations/markAsTempStorerAccepted.ts
  back/src/forms/resolvers/mutations/signEmissionForm.ts
  back/src/forms/resolvers/mutations/signedByTransporter.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/types.ts
  back/src/forms/validation.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  front/src/Apps/Dashboard/Validation/BSDD/FormWasteSummary.tsx
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteEmissionSummary.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bsdd/WasteInfo.tsx
  libs/back/prisma/src/migrations/20241024141206_add_non_adr_mention_field/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3732 [TRA-15423] Un intermédiaire peut créer un BSDA
  back/src/bsda/permissions.ts
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
Labels: bug, ready for review

#3724 [TRA-14820] Correction des conditions d'affichage de la référence à l'ADR pour la quantité estimée
  back/src/forms/pdf/components/BsddPdf.tsx
  front/src/common/components/EstimatedQuantityTooltip.tsx
Labels: ready for review, ready to merge

#3709 Correctifs pour la fonction de clonage et les BSFF
  back/src/bsds/resolvers/mutations/__tests__/cloneBsd.integration.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
Labels: bug, ready for review

#3719 Rendre obligatoire le champ "Numéro de notification" lorsque la destination ultérieure renseignée est étrangère
  Changelog.md
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/validation.ts
Labels: ready for review, ready to merge

#3720 TRA-15240 La présence d'une quantité reçue est requise pour passer du statut SENT à ACCEPTED via la mutation markAsReceived
  Changelog.md
  back/src/common/validation.ts
  back/src/forms/resolvers/mutations/__tests__/markAsReceived.integration.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  package.json
Labels: ready for review, ready to merge

#3735 [TRA-15142] Amélioration admin
  Changelog.md
  back/src/bsda/permissions.ts
  back/src/bsda/resolvers/queries/__tests__/bsda.integration.ts
  back/src/bsdasris/permissions.ts
  back/src/bsdasris/resolvers/queries/__tests__/bsdasri.integration.ts
  back/src/bsffs/database.ts
  back/src/bsffs/permissions.ts
  back/src/bsffs/resolvers/queries/__tests__/bsff.integration.ts
  back/src/bspaoh/permissions.ts
  back/src/bspaoh/resolvers/queries/__tests__/bspaoh.integration.ts
  back/src/bsvhu/permissions.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhu.integration.ts
  back/src/forms/permissions.ts
  back/src/forms/resolvers/queries/__tests__/form.integration.ts
  back/src/routers/auth-router.ts
  front/src/Apps/Dashboard/Creation/bspaoh/FormSteps.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/utils/queries.ts
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignBspaohModal.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignDelivery.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignEmission.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignOperation.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignReception.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignTransport.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsvhuValidation.test.tsx
  front/src/Apps/common/queries/bspaoh/queries.ts
  front/src/Apps/common/queries/bsvhu/queries.ts
  front/src/admin/bsd/BsdAdmin.tsx
  front/src/admin/bsd/BsdDetailContent.tsx
  front/src/admin/user/impersonate.tsx
  front/src/dashboard/components/BSDList/BSVhu/BSVhuActions/useDownloadPdf.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignBsvhu.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignBsvhuModal.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
  front/src/dashboard/detail/bsff/BsffDetailContent.tsx
  front/src/dashboard/detail/bspaoh/RouteBSPaohView.tsx
  front/src/dashboard/detail/bsvhu/RouteBsvhusView.tsx
Labels: ready for review, ready to merge

#3734 [TRA-15424] ETQ utilisateur je peux faire une révision sur un bordereau en attente de regroupement
  back/src/bsdasris/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsdasris/zodSchema.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/rules.ts
Labels: bug, ready for review, ready to merge

#3737 [TRA-14818] Correction de la "Mention au titre des règlements RID, ADNR, IMDG (optionnel)" dans le formulaire de création du BSDD
  front/src/form/bsdd/utils/initial-state.ts
Labels: bug, ready for review, ready to merge

#3726 [TRA-15404] Correction du formulaire de sélection de type d'entreprise
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeCheckbox.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/FormikCompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/RhfCompanyTypeForm.tsx
Labels: bug, ready for review

#3721 Corrige l'indexation des annexes 1 orphelines et draft
  Changelog.md
  back/src/bsds/indexation/reindexBsdHelpers.ts
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/elastic.ts
  back/src/forms/resolvers/queries/__tests__/appendixforms.integration.ts
  back/src/forms/types.ts
  back/src/scripts/bin/reindexDeletedOrphanAppendix1.ts
  e2e/playwright.config.ts
  e2e/src/plans/quickFilters.spec.ts
Labels: ready for review, ready to merge

#3725 [TRA-13971] Restreindre les TTR et Installations de traitement à être visés sur un BSDD selon leur type de profil
  .env.model
  .github/workflows/integration-tests.yml
  Changelog.md
  back/src/__tests__/factories.ts
  back/src/__tests__/testWorkflow.ts
  back/src/activity-events/bsdd/__tests__/bsdd.integration.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/bspaoh/__tests__/factories.ts
  back/src/common/validation.ts
  back/src/common/workflow.d.ts
  back/src/companies/companyProfilesRules.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/examples/workflows/acheminementDirect.ts
  back/src/forms/examples/workflows/acheminementDirectTransporteurEtranger.ts
  back/src/forms/examples/workflows/annexe1.ts
  back/src/forms/examples/workflows/entreposageProvisoire.ts
  back/src/forms/examples/workflows/entreposageProvisoireTransporteurEtranger.ts
  back/src/forms/examples/workflows/importBsdPapier.ts
  back/src/forms/examples/workflows/multiModal.ts
  back/src/forms/examples/workflows/multiModalTransporteurEtranger.ts
  back/src/forms/examples/workflows/multiModalv2.ts
  back/src/forms/examples/workflows/regroupement.ts
  back/src/forms/examples/workflows/regroupementTransporteurEtranger.ts
  back/src/forms/resolvers/mutations/__tests__/companyProfiles.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/importPaperForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResent.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
  back/src/forms/resolvers/queries/__tests__/appendixforms.integration.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/validation.ts
  libs/back/env/src/index.ts
Labels: ready for review, ready to merge

#3688 [tra-15289 | tra-15290] : Permettre à l'utilisateur de gérer les alertes de tous ses établissements & afficher le nombre d'inscrits par type d'alertes au sein d'un établissement
  Changelog.md
  apps/cron/src/commands/__tests__/onboarding.helpers.integration.ts
  apps/cron/src/commands/__tests__/sendmails.integration.ts
  apps/cron/src/commands/onboarding.helpers.ts
  back/src/__tests__/factories.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/companies/__tests__/database.test.ts
  back/src/companies/converters.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/companies/resolvers/mutations/__tests__/createCompany.integration.ts
  back/src/companies/resolvers/mutations/__tests__/renewSecurityCode.test.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/mutations/renewSecurityCodeService.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/forms/mail/renderFormRefusedEmail.ts
  back/src/forms/resolvers/mutations/__tests__/markAsAccepted.integration.ts
  back/src/index.ts
  back/src/users/__tests__/database.integration.ts
  back/src/users/__tests__/notifications.test.ts
  back/src/users/database.ts
  back/src/users/notifications.ts
  back/src/users/resolvers/Mutation.ts
  back/src/users/resolvers/mutations/__tests__/acceptMembershipRequest.integration.ts
  back/src/users/resolvers/mutations/__tests__/changeUserRole.integration.ts
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.integration.ts
  back/src/users/resolvers/mutations/__tests__/joinWithInvite.integration.ts
  back/src/users/resolvers/mutations/__tests__/sendMembershipRequest.integration.ts
  back/src/users/resolvers/mutations/__tests__/setCompanyNotifications.integration.ts
  back/src/users/resolvers/mutations/__tests__/subscribeToCompanyNotifications.integration.ts
  back/src/users/resolvers/mutations/__tests__/subscribeToNotifications.integration.ts
  back/src/users/resolvers/mutations/changeUserRole.ts
  back/src/users/resolvers/mutations/sendMembershipRequest.ts
  back/src/users/resolvers/mutations/subscribeToCompanyNotifications.ts
  back/src/users/resolvers/mutations/subscribeToNotifications.ts
  back/src/users/resolvers/queries/__tests__/myCompanies.integration.ts
  back/src/users/typeDefs/private/user.inputs.graphql
  back/src/users/typeDefs/private/user.mutations.graphql
  back/src/users/typeDefs/user.enums.graphql
  back/src/users/typeDefs/user.objects.graphql
  front/src/Apps/Account/Account.tsx
  front/src/Apps/Account/AccountNotifications/AccountNotifications.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsDisplay.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllButton.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllModal.module.scss
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllModal.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateButton.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateModal.tsx
  front/src/Apps/Account/AccountNotifications/SubscribersCountBadge.tsx
  front/src/Apps/Account/AccountNotifications/queries.ts
  front/src/Apps/Account/AccountNotifications/utils.ts
  front/src/Apps/Companies/CompaniesList/CompaniesList.tsx
  front/src/Apps/Companies/CompaniesList/SearchableCompaniesList.tsx
  front/src/Apps/Companies/CompaniesList/queries.ts
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  front/src/common/notifications.ts
  libs/back/prisma/src/migrations/20241017145500_update_notifications_schema/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3740 [TRA-15418] ETQ Transporteur je peux réviser une annexe 1 même après réception
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: bug, ready for review

#3723 [TRA-14898] Retrait du logoUrl de l'objet Application
  back/src/__tests__/oauth2.integration.ts
  back/src/__tests__/oidc.integration.ts
  back/src/applications/__tests__/validation.test.ts
  back/src/applications/resolvers/mutations/__tests__/createApplication.integration.ts
  back/src/applications/resolvers/mutations/createApplication.ts
  back/src/applications/typeDefs/private/application.inputs.graphql
  back/src/applications/typeDefs/private/application.objects.graphql
  back/src/applications/validation.ts
  back/src/routers/oauth2-router.ts
  back/src/routers/oidc-router.ts
  back/src/users/resolvers/mutations/revokeAuthorizedApplication.ts
  back/src/users/resolvers/queries/authorizedApplications.ts
  back/src/users/typeDefs/private/user.objects.graphql
  front/src/Apps/Account/AccountApplications/AutorizedApplications/AccountApplicationsAuthorizedApplications.tsx
  front/src/Apps/Account/AccountApplications/AutorizedApplications/queries.ts
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplications.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/AccountApplicationsMyApplicationsCreateUpdate.tsx
  front/src/Apps/Account/AccountApplications/MyApplications/queries.ts
  libs/back/prisma/src/migrations/20241104091219_remove_application_logo_url/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3738 [TRA-15331] Ajouter un lien "Gérer mes préférences e-mails" dans les e-mails transactionnels auquel l'utilisateur est en capacité de s'inscrire / désinscrire
  Changelog.md
  apps/cron/src/commands/__tests__/sendmails.integration.ts
  back/src/forms/resolvers/mutations/markAsSealed.ts
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/renderers.ts
  libs/back/mail/src/types.ts
Labels: ready for review

#3731 [tra-14930]Corriger les éléments de la modale de création / modification du PAOH lors d'une navigation clavier et d'un zoom texte à 200%
  front/src/Apps/Dashboard/Creation/FormStepsContent.tsx
  front/src/Apps/Forms/Components/FormStepsTabs/FormStepsTabs.tsx
  front/src/Apps/Forms/Components/FormStepsTabs/formStepsTabs.scss
  front/src/Apps/common/Components/Modal/Modal.tsx
  front/src/scss/Inputs.scss
Labels: ready for review

#3741 [tra-13234]fix recette: Mettre à jour les message en alerte type info DSFR + fix typo excutoire
  front/src/form/bsda/stepper/steps/Type.tsx
Labels: ready for review, fix de recette

#3722 [tra-15378] Permettre l'ajout d'un éco-organisme sur un VHU - FRONT
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/EcoOrganism.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/OtherActors.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/common/queries/fragments/bsvhu.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
Labels: ready for review

#3743 [tra-14930]fix focus trap issue on radio and check box inputs
  front/src/Apps/common/Components/Modal/Modal.tsx
Labels: ready for review, ready to merge, fix de recette

#3745 Correction de la documentation sur le champ quantityReceived
  back/src/forms/typeDefs/bsdd.inputs.graphql
Labels: ready for review

#3742 Mise à jour du message d'erreur pour les destinataires sans sous-profils adéquats
  back/src/common/validation.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
Labels: ready for review, ready to merge, fix de recette

#3746 [TRA-14818] Corrections de wording & CSS sur le champ de la mention ADR
  front/src/form/bsdd/WasteInfo.tsx
Labels: ready for review, ready to merge, fix de recette

#3747 Corrige le nom d'un index
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge, fix de recette

#3744 Registre - Schema improvements
  back/src/queue/jobs/__tests__/processRegistryImport.integration.ts
  back/src/registry/resolvers/queries/registryImports.ts
  back/src/registry/typeDefs/registry.objects.graphql
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/dashboard/registry/ImportModal.tsx
  front/src/dashboard/registry/MyImports.tsx
  libs/back/registry/src/import.ts
  libs/back/registry/src/shared/__tests__/schemas.test.ts
  libs/back/registry/src/shared/refinement.ts
  libs/back/registry/src/shared/schemas.ts
  libs/back/registry/src/ssd/validation/refinement.ts
  libs/back/registry/src/ssd/validation/schema.ts
  libs/back/registry/src/transformers.ts
  libs/back/registry/src/zodErrors.ts
Labels: ready for review

#3748 Corrige les updates et signature du paoh depuis l'ui
  front/src/Apps/common/queries/bspaoh/queries.ts
Labels: ready for review, ready to merge, fix de recette

#3749 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#3752 Exlude france from next destination countries select
  front/src/form/common/components/company/CountrySelector.tsx
  front/src/form/common/components/company/ExtraEuropeanCompanyManualInput.tsx
Labels: fix de recette

#3753 [TRA-15272] Correctifs pour le formulaire ADR + PDF
  back/src/forms/pdf/components/BsddPdf.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/components/waste-code/WasteCode.tsx
  front/src/form/bsdd/utils/initial-state.ts
Labels: bug, ready for review

#3756 [TRA-15422] A sa création, une annexe 1 reprend les informations ADR du bordereau chapeau
  back/src/forms/repository/form/setAppendix1.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
Labels: ready for review, ready to merge

#3757 [TRA-15451] Correction d'une typo dans le PDF du BSDD, dans les cadres 7, 10, 11 et 12 d'une annexe 1
  back/src/forms/pdf/components/BsddPdf.tsx
Labels: ready for review, ready to merge

#3750 [TRA-14426] Updates banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3751 [TRA-15073] Fixes scroll in input number
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/Appendix1ProducerRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/RhfPackagings.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/components/Packagings.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignReception.tsx
  front/src/form/common/components/custom-inputs/NumberInput.tsx
Labels: ready for review

#3762 Display multiple banner messages and update content
  front/src/Apps/common/Components/SurveyBanner/SurveyBanner.tsx
  front/src/Apps/common/Components/SurveyBanner/surveyBannerTypes.ts
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review, ready to merge

#3765 [TRA-15487] ETQ Admin je peux impersoner un email sans me préoccuper des majuscules ni des espaces
  back/src/routers/auth-router.ts
Labels: ready for review

#3775 [TRA-15500] Impossible de viser un transporteur étranger sur un BSVHU
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
Labels: ready for review, ready to merge

#3771 [TRA-15271] ETQ utilisateur je peux m'inscrire / me désinscrire aux alertes e-mails en lien avec les délégations registre
  back/src/__tests__/factories.ts
  back/src/companies/converters.ts
  back/src/registryDelegation/resolvers/mutations/__tests__/createRegistryDelegation.integration.ts
  back/src/registryDelegation/resolvers/mutations/utils/createRegistryDelegation.utils.ts
  back/src/users/__tests__/notifications.test.ts
  back/src/users/notifications.ts
  back/src/users/resolvers/mutations/__tests__/subscribeToCompanyNotifications.integration.ts
  back/src/users/resolvers/mutations/__tests__/subscribeToNotifications.integration.ts
  back/src/users/resolvers/mutations/subscribeToCompanyNotifications.ts
  back/src/users/typeDefs/private/user.inputs.graphql
  back/src/users/typeDefs/user.objects.graphql
  front/src/Apps/Account/AccountNotifications/AccountNotifications.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsDisplay.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllModal.tsx
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateModal.tsx
  front/src/Apps/Account/AccountNotifications/queries.ts
  front/src/Apps/Account/AccountNotifications/utils.ts
  libs/back/prisma/src/migrations/20241122093411_add_registry_delegation_notification/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3760 [TRA-tra-8351] Ne pas doubler les quantités restantes à regrouper lorsqu'on modifie un bordereau de groupement
  Changelog.md
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.test.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelectWrapper.tsx
Labels: ready for review, ready to merge

#3781 [tra-15515]Modifier un BSVHU : exemption de récépissé non prise en compte
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
Labels: hotfix, ready for review

#3770 [TRA-15098] - Permettre au transporteur étranger d'avoir les mêmes droits qu'un transporteur FR concernant la révision sur une Annexe 1
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/forms/resolvers/mutations/submitFormRevisionRequestApproval.ts
  back/src/forms/resolvers/queries/__tests__/formRevisionRequests.integration.ts
  back/src/forms/resolvers/queries/formRevisionRequests.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.queries.graphql
  front/src/Apps/Dashboard/Components/Revision/ActorStatus/ActorSatus.tsx
  front/src/Apps/Dashboard/Components/Revision/revisionServices.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
Labels: ready for review, ready to merge

#3787 [HOTFIX][TRA-15503] : Ne pas désactiver l'interrupteur Soumis à l'ADR lors de la duplication d'un BSDD
  back/src/__tests__/factories.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/signedByTransporter.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
Labels: hotfix, ready for review, ready to merge

#3791 Remove duplicate component CompanySelectorWrapper
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/common/Components/CompanySelectorWrapper/CompanySelectorWrapper.tsx
  front/src/Apps/common/Components/CompanySelectorWrapper/RhfCompanySelectorWrapper.test.tsx
  front/src/Apps/common/Components/CompanySelectorWrapper/RhfCompanySelectorWrapper.tsx
Labels: ready for review

#3779 Otel - Fix service name
  libs/back/tracer/src/index.ts
  libs/back/tracer/src/pkg.ts
  libs/back/tracer/src/utils.ts
Labels: ready for review, ready to merge
