Repository MTES-MCT/trackdechets, pull requests merged in 2024-06, with the labels that each got.

#3371 [Fix TRA-13926] Ajout d'un sous-type "Regroupement" pour le BSFF dans le registre
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.enums.graphql
Labels: MEP 4 Juin, ready for review, fix de recette

#3369 Correction post recette relative au numéro de notification
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
Labels: ready for review, ready to merge

#3374 Merge Master -> Dev
  back/src/forms/repository/form/updateAppendix2Forms.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  front/src/Apps/Companies/CompanyInfo/CompanyInfo.tsx
Labels: ready for review, ready to merge

#3375 Increase script timeout
  libs/back/scripts/src/runner.ts
Labels: ready for review, ready to merge

#3376 En-têtes de colonnes plus explicites pour l'export des établissements
  back/src/users/export/columns.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesCsv.integration.ts
  back/src/users/resolvers/queries/__tests__/myCompaniesXls.integration.ts
Labels: ready for review, fix de recette

#3366 [TRA-13844] Fix après recette (rendre possible changement de BSDASRIs groupés après signature producteur)
  back/src/bsdasris/resolvers/mutations/updateSimpleBsdasri.ts
Labels: ready for review, ready to merge, fix de recette

#3368 Fix recette annexe 1
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/validation.ts
Labels: fix de recette

#3382 [TRA-14516] Hotfix : Hide sensitive informations in companyPrivateInfos query
  back/src/companies/resolvers/CompanySearchPrivate.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/resolvers/queries/companyPrivateInfos.ts
Labels: hotfix, ready for review, ready to merge

#3400 [BUG | TRA-14549] ETQ utilisateur je dois pouvoir renseigner un nombre négatif dans les champs "coordonnée longitude" ou dans "Coordonnée latitude"
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/validation.ts
Labels: hotfix, ready for review, ready to merge

#3381 [tra-14460]Ajouter un tooltip concernant la diffusion du nom usuel pour prévenir les utilisateurs que l'information sera accessible pour d'autres acteurs
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAdd.tsx
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAddProducer.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyIdentificationForm.tsx
  front/src/Apps/Companies/common/Components/GivenNameNotice/GivenNameNotice.tsx
  front/src/Apps/Companies/common/Components/GivenNameNotice/givenNameNotice.scss
Labels: ready for review

#3385 [tra-14478] Renommer Transit par Réexpédition (sous-type de BSFF) + fix some missing arguments in unit test
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review

#3389 [tra-14474] Ajouter la Quantité refusée et la Quantité traitée sur l'Aperçu des différents BSDD
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review

#3398 [BUG | TRA-14543] Le volume total d'un DASRI devrait être un Float, et déprécié
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
Labels: ready for review

#3399 [BUG | TRA-14545] Le champ allowBsdasriTakeOverWithoutSignature devrait être retourné par la requête companyInfos même pour des entreprises non-diffusibles
  back/src/companies/resolvers/queries/__tests__/companyInfos.integration.ts
  back/src/companies/resolvers/queries/companyInfos.ts
Labels: ready for review

#3392 [TRA-14325] Ajout d'une colonne avec l'adresse email du destinataire, négociant & courtier dans tous les registres
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/registry.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/registry.ts
  back/src/bspaoh/__tests__/registry.integration.ts
  back/src/bspaoh/registry.ts
  back/src/bsvhu/__tests__/registry.integration.ts
  back/src/bsvhu/registry.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/registry.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review

#3390 [TRA-14407] Page blanche lorsque je souhaite "Mettre à jour le bordereau pour le publier" sur un PAOH
  Changelog.md
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
Labels: ready for review, ready to merge

#3403 [tra-14179] - Retirer la possibilité d'ajouter une Annexe 1 sur un BSD de tournée dédiée avant que celui-ci ne soit publié via API
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/validation.ts
Labels: ready for review, ready to merge

#3401 [tra-14435] Revoir les messages d'erreur à l'ajout d'un Crématorium non inscrit / n'ayant pas le bon profil
  Changelog.md
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/common/validation/siret.ts
  back/src/companies/__tests__/search.test.ts
  back/src/companies/search.ts
  back/src/companies/sirene/trackdechets/client.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/validation.ts
  front/src/Apps/common/queries/company/query.ts
  front/src/form/bspaoh/steps/Destination.tsx
Labels: ready for review, ready to merge

#3349 [TRA-8355] Ajouter les informations relatives à l'installation de destination post-entreposage provisoire sur le registre sortant et exhaustif
  back/src/__tests__/utils.test.ts
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/columns.ts
  back/src/registry/elastic.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  back/src/utils.ts
Labels: ready for review

#3417 Revoir la taille de la modale en 1099px
  front/src/Apps/common/Components/Modal/DsfrModal.tsx
  front/src/form/bspaoh/FormContainer.tsx
  front/src/form/bspaoh/components/Packagings.tsx
  front/src/form/bspaoh/steps/Transporter.tsx
  front/src/form/bspaoh/steps/Waste.tsx
  front/src/scss/Modals.scss
Labels: ready for review, ready to merge

#3367 [TRA-8392] Ajout du SIRET et de la Raison sociale des 3 intermédiaires sur le registre exhaustif
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/columns.ts
  back/src/registry/elastic.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review

#3409 [TRA-11099] - Modifier les informations relatives au transport sur l'ensemble des registres
  Changelog.md
  back/src/bsda/registry.ts
  back/src/bsdasris/registry.ts
  back/src/bsds/typeDefs/bsd.enums.graphql
  back/src/bsffs/registry.ts
  back/src/bspaoh/registry.ts
  back/src/common/typeDefs/common.enums.graphql
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/forms/types.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review, ready to merge

#3410 [TRA 9139] - localisation des terres (parcelles) dans les registres
  Changelog.md
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/forms/types.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review, ready to merge

#3420 [Hotfix] Dupliquer un VHU ou DASRI ne devrait pas dupliquer les destinationOperationCode & Mode
  back/src/bsdasris/resolvers/mutations/__tests__/duplicateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/duplicate.ts
Labels: hotfix, ready for review

#3384 [TRA-13275/TRA-14461] Mettre à jour le rôle d'un utilisateur depuis la liste de membres (page entreprise + TD Admin)
  Changelog.md
  back/src/companies/__tests__/database.test.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/companies/resolvers/CompanySearchPrivate.ts
  back/src/companies/resolvers/queries/companyPrivateInfos.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/permissions.ts
  back/src/users/database.ts
  back/src/users/resolvers/Mutation.ts
  back/src/users/resolvers/mutations/__tests__/changeUserRole.integration.ts
  back/src/users/resolvers/mutations/__tests__/deleteInvitation.integration.ts
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.integration.ts
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.test.ts
  back/src/users/resolvers/mutations/__tests__/removeUserFromCompany.integration.ts
  back/src/users/resolvers/mutations/__tests__/resendInvitation.integration.ts
  back/src/users/resolvers/mutations/changeUserRole.ts
  back/src/users/resolvers/mutations/deleteInvitation.ts
  back/src/users/resolvers/mutations/inviteUserToCompany.ts
  back/src/users/resolvers/mutations/inviteUserToCompanyService.ts
  back/src/users/resolvers/mutations/removeUserFromCompany.ts
  back/src/users/resolvers/mutations/resendInvitation.ts
  back/src/users/typeDefs/private/user.mutations.graphql
  front/src/Apps/Companies/CompanyMembers/CompanyMembers.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersInvite.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersList.tsx
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  front/src/Apps/routes.ts
  front/src/admin/Admin.tsx
  front/src/admin/company/MembersAdmin.tsx
  front/src/admin/user/impersonate.tsx
  front/src/form/common/components/company/CompanyResults.tsx
  front/src/graphql-client.ts
Labels: ready for review, ready to merge

#3402 [TRA-14042] Appliquer le traitement Annexe 2 récursivement
  Changelog.md
  back/src/forms/repository/form/updateAppendix2Forms.ts
Labels: ready for review

#3405 [tra-14471] - Inversion de l'ordre des boutons sur l'annexe 1
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
Labels: ready for review, ready to merge

#3404 [tra-14285] - Corretion sur le takenOverAt des chapeaux
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/signTransportForm.ts
Labels: ready for review

#3415 Enhance logger
  back/src/common/middlewares/__tests__/loggingMiddleware.test.ts
  back/src/common/middlewares/loggingMiddleware.ts
  back/src/common/middlewares/timeout.ts
  back/src/server.ts
  libs/back/logger/src/correlationId.ts
  libs/back/logger/src/format.ts
  libs/back/logger/src/index.ts
  libs/back/logger/src/logger.ts
Labels: ready for review, ready to merge

#3372 [TRA-14278] Ajout des informations relatives à l'envoi à l'étranger sur les registres Entrant, Sortant, Exhaustif & Gestion, pour les BSDD & BSDA
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/registry.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/forms/types.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review

#3406 [tra-14488] - Permettre l'activation / désactivation de la Signature automatique de l'Annexe 1
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/companies/resolvers/CompanySearchPrivate.ts
  back/src/companies/resolvers/mutations/addSignatureAutomation.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/mutations/updateCompanyService.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/typeDefs/company.mutations.graphql
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.inputs.graphql
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/forms/permissions.ts
  back/src/forms/resolvers/mutations/__tests__/signTransportForm.integration.ts
  e2e/src/utils/company.ts
  front/src/Apps/Companies/CompanySignature/CompanySignatureAutomation.tsx
  front/src/Apps/Companies/common/fragments.ts
  front/src/Apps/Companies/common/queries.ts
  libs/back/prisma/project.json
  libs/back/prisma/src/migrations/20240617125200_add_company_allow_signature_automation/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/scripts/20240617145944537_set_company_allow_signature_automation.ts
Labels: ready for review, ready to merge

#3407 [tra-14348][tra-14349] Révision des dasris de groupement et synthèse
  Changelog.md
  back/src/bsdasris/converter.ts
  back/src/bsdasris/repository/revisionRequest/accept.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  back/src/bsdasris/zodSchema.ts
  front/src/dashboard/components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
Labels: ready for review

#3416 [tra-14215] Téléchargement des fiches établissement
  .env.model
  .github/workflows/e2e.yml
  .github/workflows/integration-tests.yml
  apps/queues-gerico/.eslintrc.json
  apps/queues-gerico/jest.config.ts
  apps/queues-gerico/project.json
  apps/queues-gerico/src/main.ts
  apps/queues-gerico/tsconfig.app.json
  apps/queues-gerico/tsconfig.json
  apps/queues-gerico/tsconfig.spec.json
  back/src/common/post/backends/gerico/index.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companydigest/__tests__/factories.companydigest.ts
  back/src/companydigest/database.ts
  back/src/companydigest/developper_doc.md
  back/src/companydigest/errors.ts
  back/src/companydigest/resolvers/Mutation.ts
  back/src/companydigest/resolvers/Query.ts
  back/src/companydigest/resolvers/index.ts
  back/src/companydigest/resolvers/mutations/__tests__/companyDigestCreate.integration.ts
  back/src/companydigest/resolvers/mutations/create.ts
  back/src/companydigest/resolvers/queries/__tests__/companyDigestPdf.integration.ts
  back/src/companydigest/resolvers/queries/__tests__/companydIgest.integration.ts
  back/src/companydigest/resolvers/queries/companyDigestPdf.ts
  back/src/companydigest/resolvers/queries/companyDigests.ts
  back/src/companydigest/typeDefs/private/companydigest.enums.graphql
  back/src/companydigest/typeDefs/private/companydigest.inputs.graphql
  back/src/companydigest/typeDefs/private/companydigest.mutations.graphql
  back/src/companydigest/typeDefs/private/companydigest.objects.graphql
  back/src/companydigest/typeDefs/private/companydigest.queries.graphql
  back/src/companydigest/validation.ts
  back/src/index.ts
  back/src/queue/bull-board.ts
  back/src/queue/jobs/__tests__/sendHook.integration.ts
  back/src/queue/jobs/gerico.ts
  back/src/queue/jobs/index.ts
  back/src/queue/jobs/sendHook.ts
  back/src/queue/producers/gerico.ts
  back/src/queue/producers/index.ts
  back/src/queue/producers/jobNames.ts
  back/src/routers/__tests__/gerico.integration.ts
  back/src/routers/downloadRouter.ts
  back/src/routers/gericoWebhookRouter.ts
  back/src/schema.ts
  back/src/server.ts
  back/src/webhooks/typeDefs/webhooks.objects.graphql
  e2e/src/utils/company.ts
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyDigestSheet/CompanyDigestSheet.tsx
  front/src/Apps/Companies/CompanyDigestSheet/queries.ts
  front/src/Apps/Companies/common/fragments.ts
  front/src/scss/Spinner.scss
  front/src/scss/index.scss
  libs/back/env/src/index.ts
  libs/back/prisma/src/migrations/20240618130754_add_company_digest/migration.sql
  libs/back/prisma/src/migrations/20240618145537_company_feature_flags/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, ready to merge

#3387 [TRA-14501] Changement du wording sur les quantités dans le tableau des annexes 2
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
Labels: ready for review, ready to merge

#3423 Fix company digest download token cache
  front/src/Apps/Companies/CompanyDigestSheet/CompanyDigestSheet.tsx
Labels: ready for review

#3424 Rappatriement des hotfix de master sur dev
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/duplicateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasriSynthesis.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
  back/src/bsdasris/validation.ts
  back/src/bsvhu/__tests__/validation.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/duplicate.ts
  back/src/bsvhu/validation.ts
  back/src/common/plugins/graphiql/index.ts
  back/src/common/validation/operationMode.ts
  back/src/forms/edition.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
Labels: ready to merge

#3425 Corrige le message d'erreur des destinations non inscrites en crématorium
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/dynamicRefinements.ts
  front/src/Apps/common/Components/Modal/DsfrModal.tsx
  front/src/form/bspaoh/FormContainer.tsx
Labels: ready for review, fix de recette

#3427 Ajoute la migration pour créer l' index du companyDigest distantId
  libs/back/prisma/src/migrations/20240627132043_add_companydigest_distantid_idx/migration.sql
  libs/back/prisma/src/schema.prisma
Labels: ready for review, fix de recette

#3428 [Bugfix] Correction de la tâche "npx nx dev"
  package.json
Labels: bug, ready for review

#3293 Script de nettoyage des évènements Mongo
  back/src/activity-events/data.ts
  back/src/events/mongodb.ts
  back/src/scripts/bin/__tests__/cleanMongoEvents.integration.ts
  back/src/scripts/bin/cleanMongoEvents.helper.ts
  back/src/scripts/bin/cleanMongoEvents.ts
Labels: ready for review, ready to merge

#3426 [fix TRA-14461] fix mauvais param sur changeUserRole
  front/src/Apps/Companies/common/queries.ts
  package.json
Labels: ready for review, ready to merge

#3429 [TRA-11099 fix] Ajout de champs manquants + utilisation de n° de TVA sur transporteur étrangers
  back/src/bsda/registry.ts
  back/src/bsffs/registry.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registry.ts
  back/src/registry/__tests__/columns.test.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
Labels: ready for review

#3430 [TRA-14633] Ajout d'un outil de visualisation des données entreprise pour les admins
  back/src/companies/resolvers/Query.ts
  back/src/companies/resolvers/queries/companyExhaustive.ts
  back/src/companies/sirene/insee/client.ts
  back/src/companies/sirene/trackdechets/client.ts
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/companies/typeDefs/private/company.queries.graphql
  front/src/Apps/routes.ts
  front/src/admin/Admin.tsx
  front/src/admin/companies/CompaniesDashboard.tsx
  front/src/admin/companies/CompanyTable.tsx
Labels: ready for review

#3431 Ajoute un espace ertical sur formulaire paoh
  front/src/form/bspaoh/components/Packagings.tsx
Labels: ready for review, fix de recette
