Repository MTES-MCT/trackdechets, pull requests merged in 2024-01, with the labels that each got.

#2997 Renvoie les champs transporteurs sur la requête bspaohs
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/duplicateBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/publishBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/signBspaohEmission.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/updateBspaoh.integration.ts
  back/src/bspaoh/resolvers/queries/__tests__/bspaoh.integration.ts
  back/src/bspaoh/resolvers/queries/__tests__/bspaohs.integration.ts
  back/src/bspaoh/resolvers/queries/bspaohs.ts
Labels: ready for review

#2996 [tra-13471]Problème d'affichage sur la page d'inscription et de connexion au niveau de la case à cocher qui permet d'afficher le mot de passe
  front/src/scss/Inputs.scss
Labels: ready for review

#2935 [tra-13172] Recepisse transporteur optionnel si le transport n'est pas par route
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsffs/__tests__/validation.integration.ts
  back/src/common/validation.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/validation.ts
Labels: ready for review

#2998 Mise à jour des messages d'erreur paoh
  back/src/bspaoh/resolvers/mutations/__tests__/signBspaohEmission.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/signBspaohTransport.integration.ts
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/rules.ts
Labels: ready for review

#2979 [tra-13327] - Annexe 1: 5 jours pour signer
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/validation.ts
Labels: ready for review

#2977 [tra-13401] Type text pour le BSVHU
  back/prisma/migrations/163_bsvhu_mode_text.sql
Labels: ready for review

#2988 [tra-13172] FRONT - Recepisse transporteur optionnel si le transport n'est pas par route
  front/src/form/common/components/company/CompanySelector.tsx
Labels: ready for review

#2978 [tra-13317] - Labels d'erreur BSDA
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/rules.ts
Labels: ready for review

#2974 [TRA-12096] Multimodal v2 - FRONT
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/elasticHelpers.ts
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.scss
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.stories.tsx
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.test.tsx
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.tsx
  front/src/Apps/Forms/Components/TransporterDisplay/TransporterDisplay.scss
  front/src/Apps/Forms/Components/TransporterDisplay/TransporterDisplay.tsx
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.test.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.tsx
  front/src/Apps/common/Components/CompanySelector/CompanySelector.tsx
  front/src/Apps/common/Components/CompanySelector/companySelectorTypes.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormJourneySummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/MarkSegmentAsReadyToTakeOver.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/PrepareSegment.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/TakeOverSegment.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/segments/index.ts
  front/src/dashboard/components/BSDList/BSDD/index.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/dashboard/detail/bsdd/EditSegment.tsx
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/Transporter.tsx
  front/src/form/bsdd/utils/initial-state.ts
  front/src/form/bsvhu/Emitter.tsx
  front/src/form/common/components/CompanySelectorWrapper/CompanySelectorWrapper.test.tsx
  front/src/form/common/components/CompanySelectorWrapper/CompanySelectorWrapper.tsx
Labels: ready for review

#2973 Changement valeurs INSEE: remplace "N" par "P"
  apps/doc/docs/guides/sirene.md
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/companies/__tests__/sirenify.test.ts
  back/src/companies/resolvers/queries/__tests__/companyInfos.integration.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/resolvers/queries/companyInfos.ts
  back/src/companies/search.ts
  back/src/companies/sirene/insee/__tests__/client.test.ts
  back/src/companies/sirene/insee/client.ts
  back/src/companies/sirene/trackdechets/__tests__/client.test.ts
  back/src/companies/sirene/trackdechets/client.ts
  back/src/companies/sirene/trackdechets/types.ts
  back/src/companies/sirene/types.ts
  back/src/companies/sirenify.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.objects.graphql
  back/src/companies/vat/vies/types.ts
  back/src/forms/__tests__/sirenify.integration.ts
  back/src/forms/resolvers/queries/__tests__/formsRegister.integration.ts
  back/src/queue/jobs/indexFavorites.ts
  back/src/registry/resolvers/queries/__tests__/wastesRegistryXls.integration.ts
  front/src/account/accountCompanyAdd/AccountCompanyAddSiret.tsx
  front/src/company/Company.tsx
Labels: ready for review, breaking change

#3005 Fix appendix1
  apps/cron/src/commands/appendix1.helpers.ts
Labels: ready for review

#3000 Améliorations pdf paoh
  back/src/bspaoh/pdf/components/BspaohPdf.tsx
  back/src/bspaoh/pdf/components/PackagingInfosTable.tsx
  back/src/bspaoh/pdf/components/Signature.tsx
Labels: ready for review

#2981 [TRA-13439] Hotfix/temporarily removes v2 banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: hotfix, ready for review

#3008 Montée de version Prisma
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  package-lock.json
  package.json
Labels: ready for review

#2999 [tra-13215] Implémentation Back pour l'affichage des Révisions
  back/src/bsda/converter.ts
  back/src/bsda/elastic.ts
  back/src/bsda/resolvers/Bsda.ts
  back/src/bsda/resolvers/BsdaMetadata.ts
  back/src/bsda/resolvers/queries/__tests__/bsdas.integration.ts
  back/src/bsda/typeDefs/bsda.objects.graphql
  back/src/bsda/types.ts
  back/src/bsda/validation/rules.ts
  back/src/bsdasris/elastic.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/bsffs/elastic.ts
  back/src/bspaoh/elastic.ts
  back/src/bsvhu/elastic.ts
  back/src/common/elastic.ts
  back/src/forms/converter.ts
  back/src/forms/elastic.ts
  back/src/forms/resolvers/Form.ts
  back/src/forms/resolvers/forms/metadata.ts
  back/src/forms/resolvers/index.ts
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/prisma.ts
  libs/back/prisma/src/schema.prisma
  package.json
Labels: ready for review

#2992 [TRA-13057] Adds new roles to the frontend
  back/src/__tests__/factories.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/CompanyPrivate.ts
  back/src/companies/vat/vies/checkVatService.wsdl
  back/src/forms/resolvers/mutations/__tests__/markAsReceived.integration.ts
  back/src/forms/resolvers/queries/__tests__/formsLifeCycle.integration.ts
  back/src/users/resolvers/User.ts
  back/src/users/resolvers/queries/invitation.ts
  back/src/users/typeDefs/user.enums.graphql
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/account/AccountCompanyMember.tsx
  front/src/account/AccountMembershipRequest.tsx
  front/src/account/fields/forms/AccountFormCompanyInviteNewUser.tsx
  front/src/admin/Admin.tsx
  front/src/common/contexts/PermissionsContext.tsx
  front/src/dashboard/DashboardCompanySelector.tsx
Labels: ready for review

#3009 [TRA-12847] Hide dashboard v1
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsdaValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsvhuValidation.test.tsx
  front/src/Apps/Dashboard/Components/Validation/Draft/DraftValidation.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Apps/routes.ts
  front/src/Pages/Dashboard.tsx
  front/src/account/AccountCompanyAdd.tsx
  front/src/dashboard/components/BSDList/BSDD/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/SignWork.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterInfo.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasriSecretCode.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterCustomInfo.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignEmission.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsda/approve/BsdaConsultRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddApproveRevision.tsx
  front/src/dashboard/components/RevisionRequestList/bsdd/approve/BsddConsultRevision.tsx
Labels: ready for review

#3010 Recette multi modal v2
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/database.ts
  back/src/forms/elasticHelpers.ts
  back/src/forms/resolvers/mutations/__tests__/deleteFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/deleteFormTransporter.ts
  back/src/forms/resolvers/mutations/updateFormTransporter.ts
  front/src/Apps/Dashboard/Components/Validation/Act/ActBsddValidation.tsx
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.test.tsx
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.test.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormJourneySummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bsdd/StepList.tsx
Labels: ready for review

#3015 [TRA-13060] Adds news banner
  front/src/Apps/common/Components/SurveyBanner/surveyBanner.scss
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3019 Fix recette - modal récépissé transporteur
  front/src/form/common/components/company/TransporterRecepisseWrapper.tsx
Labels: ready for review

#3022 Fix vhu duplication
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3016 Forcer la saisie d'un transporteur après entreposage provisoire dans "Compléter le BSD suite"
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsResealedModalContent.tsx
Labels: ready for review

#3025 Corrige l'affichage des champs scellés sur le PAOH et corrige la documentation
  apps/doc/docs/reference/statuts/bspaoh.mdx
  back/src/bspaoh/resolvers/queries/__tests__/bspaoh.integration.ts
  back/src/bspaoh/resolvers/queries/__tests__/bspaohmetadata.integration.ts
  back/src/bspaoh/validation/rules.ts
Labels: ready for review

#3024 [TRA-13057] Fix recette : Redirects drivers to the to Collect dashboard
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Pages/Dashboard.tsx
Labels: ready for review

#3027 [TRA-13683] Fixes annexe 2 wording
  front/src/dashboard/constants.tsx
Labels: ready for review

#3029 [TRA-13057] Fixes primary buttons for transporters
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#3037 Améliorationss script d'indexation en masse
  .github/workflows/integration-tests.yml
  CONTRIBUTING.md
  apps/Procfile.back
  apps/queues-bulk-indexation-master/.eslintrc.json
  apps/queues-bulk-indexation-master/jest.config.ts
  apps/queues-bulk-indexation-master/project.json
  apps/queues-bulk-indexation-master/src/main.ts
  apps/queues-bulk-indexation-master/tsconfig.app.json
  apps/queues-bulk-indexation-master/tsconfig.json
  apps/queues-bulk-indexation-master/tsconfig.spec.json
  apps/queues-bulk-indexation/.eslintrc.json
  apps/queues-bulk-indexation/jest.config.ts
  apps/queues-bulk-indexation/project.json
  apps/queues-bulk-indexation/src/main.ts
  apps/queues-bulk-indexation/tsconfig.app.json
  apps/queues-bulk-indexation/tsconfig.json
  apps/queues-bulk-indexation/tsconfig.spec.json
  apps/queues-indexation/src/main.ts
  back/src/bsds/indexation/bulkIndexBsds.ts
  back/src/index.ts
  back/src/queue/bull-board.ts
  back/src/queue/producers/elastic.ts
  back/src/scripts/bin/reindexAllInBulk.ts
Labels: ready for review

#3044 [TRA-13700] Correction du wording pour le mode de traitement 'Elimination'
  back/src/common/operationModes.ts
  front/src/common/operationModes.ts
Labels: ready for review

#3048 Fix searchCompanies quand VIES down, ne pas afficher "aucun établissement trouvé"
  back/src/companies/__tests__/search.test.ts
  back/src/companies/search.ts
Labels: ready for review

#3013 [tra-13388]Suppression définitive de l'écran d'introduction à la connexion
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/dashboard/Dashboard.tsx
  front/src/dashboard/components/OnboardingSlideshow/OnboardingSlideshow.module.scss
  front/src/dashboard/components/OnboardingSlideshow/OnboardingSlideshow.tsx
  front/src/dashboard/components/OnboardingSlideshow/assets/download.svg
  front/src/dashboard/components/OnboardingSlideshow/assets/follow.svg
  front/src/dashboard/components/OnboardingSlideshow/assets/prepare.svg
  front/src/dashboard/components/OnboardingSlideshow/assets/sign.svg
  front/src/dashboard/components/OnboardingSlideshow/assets/slide1.gif
  front/src/dashboard/components/OnboardingSlideshow/assets/slide2.gif
  front/src/dashboard/components/OnboardingSlideshow/assets/slide3.gif
  front/src/dashboard/components/OnboardingSlideshow/assets/slide4.gif
  front/src/dashboard/components/OnboardingSlideshow/assets/slide6.svg
  front/src/dashboard/components/OnboardingSlideshow/index.ts
Labels: ready for review

#3049 [TRA-13691] Test E2E - Création d'établissements
  .github/workflows/e2e.yml
  CONTRIBUTING.md
  back/src/companies/resolvers/mutations/__tests__/createTestCompany.integration.ts
  back/src/companies/resolvers/mutations/createTestCompany.ts
  back/src/index.ts
  e2e/playwright.config.ts
  e2e/project.json
  e2e/src/testPlans/account.spec.ts
  e2e/src/testPlans/companies.spec.ts
  e2e/src/utils/company.ts
  e2e/src/utils/time.ts
  e2e/src/utils/user.ts
  front/src/account/fields/AccountFieldCompanyBrokerReceipt.tsx
  front/src/account/fields/AccountFieldCompanyTraderReceipt.tsx
  front/src/account/fields/AccountFieldCompanyTransporterReceipt.tsx
  front/src/account/fields/AccountFieldCompanyVhuAgrementBroyeur.tsx
  front/src/account/fields/AccountFieldCompanyVhuAgrementDemolisseur.tsx
  front/src/account/fields/AccountFieldCompanyWorkerCertification.tsx
Labels: ready for review

#3050 [tra-13330]Ajouter le numéro libre BSDD sur le tableau de bord V2
  front/public/icons/dashboard/icon-custom-id.svg
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconTypes.ts
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIconUtils.ts
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/common/types/bsdTypes.ts
Labels: ready for review

#3017 [tra-13612]recette ui
  front/public/icons/dashboard/pencil.svg
  front/src/Apps/Dashboard/Components/Actors/Actors.tsx
  front/src/Apps/Dashboard/Components/Actors/actors.scss
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/InfoWithIcon.tsx
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
  front/src/Apps/Dashboard/Components/WasteDetails/wasteDetails.scss
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
Labels: ready for review

#3051 [Tra-13453] Corrections bugs registre exhaustif d'un BSDD avec entreposage provisoire
  Changelog.md
  back/src/__tests__/factories.ts
  back/src/forms/compat.ts
  back/src/registry/__tests__/elastic.integration.ts
  back/src/registry/elastic.ts
  back/src/registry/resolvers/queries/__tests__/allWastes.integration.ts
  back/src/registry/resolvers/queries/__tests__/queries.ts
  back/src/registry/wastes.ts
Labels: ready for review

#3056 Hotfix Company.name pour les entreprises individuelles
  back/src/companies/sirene/trackdechets/client.ts
Labels: ready for review
