Repository MTES-MCT/trackdechets, pull requests merged in 2024-08, with the labels that each got.

#3500 [TRA 14881] HOTFIX tempstorage reception
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
Labels: hotfix, ready for review

#3502 [TRA-14899] Fixes BSDA revision quantity
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
Labels: hotfix, ready for review, ready to merge

#3504 [TRA-14900] Adds reception field on acceptation modal
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
Labels: hotfix, ready for review

#3506 HOTFIX Adds reception field on acceptation modal (#3504)
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
Labels: hotfix, ready for review

#3478 [tra-14782]Retours sur le formulaire PAOH
  front/src/Apps/Forms/Components/FormStepsTabs/FormStepsTabs.tsx
  front/src/Apps/Forms/Components/FormStepsTabs/formStepsTabs.scss
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/Apps/Forms/Components/TagsInput/TagsInputWrapper.tsx
  front/src/form/bspaoh/FormSteps.tsx
  front/src/form/bspaoh/components/Packagings.tsx
  front/src/form/bspaoh/steps/Transporter.tsx
  front/src/form/bspaoh/steps/Waste.tsx
Labels: ready for review, ready to merge

#3508 [hotfix][tra-14865]Fixes appendix1 revision not accepting decimal values for the estimated quantity
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/Appendix1ProducerRequestRevision.tsx
Labels: hotfix

#3511 [hotfix][tra-14922]Révision BSDA : impossible de saisir un numéro de scellé déjà renseigné sur le bordereau
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
Labels: hotfix, ready to merge

#3514 [hotfix][tra-14902]BSFF : problème d'affichage de la modale > impossible de gérer les contenants
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignPackagings.tsx
Labels: hotfix, ready to merge

#3512 Hotfix bsvhu sign errors
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignTransport.tsx
Labels: hotfix, ready for review, ready to merge

#3507 [tra-14695]Ajouter la possibilité de Réviser l'Annexe 1 pour le transporteur lorsqu'il vient de signer l'enlèvement
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3515 [tra-14897]Migrer Mes paramètres de Mon compte au DSFR
  e2e/src/plans/account.spec.ts
  e2e/src/utils/user.ts
  front/src/Apps/Account/Account.tsx
  front/src/Apps/Account/AccountInfo.tsx
  front/src/Apps/Account/AccountInfo/AccountFormChangePassword.tsx
  front/src/Apps/Account/AccountInfo/AccountInfo.tsx
  front/src/Apps/Account/AccountInfo/AccountInfoActionBar.tsx
  front/src/Apps/Account/AccountInfo/accountInfoActionBar.scss
  front/src/Apps/Account/AccountMenu.tsx
  front/src/Apps/Account/accountSchema.ts
  front/src/Apps/Account/fields/AccountFieldName.tsx
  front/src/Apps/Account/fields/AccountFieldPassword.tsx
  front/src/Apps/Account/fields/AccountFieldPhone.tsx
  front/src/Apps/Account/fields/forms/AccountFormChangePassword.tsx
  front/src/Apps/Companies/common/queries.ts
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review, ready to merge

#3499 [TRA 14684] Changes BSDD to BSD in PDF
  back/src/forms/pdf/generateBsddPdf.tsx
Labels: ready for review, ready to merge

#3520 [TRA-14705] Migrates my account tokens and applications to the DSFR
  front/index.html
  front/src/Apps/Account/Account.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokenRevoke.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokens.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokensCreate.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokensRevokeAll.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/queries.ts
  front/src/Apps/Account/AccountApplications/AccountApplications.tsx
  front/src/Apps/Account/AccountApplications/AutorizedApplications/AccountApplicationsAuthorizedApplications.tsx
  front/src/Apps/Account/AccountApplications/AutorizedApplications/AccountApplicationsAuthorizedApplicationsRevoke.tsx
  front/src/Apps/Account/AccountApplications/AutorizedApplications/queries.ts
  front/src/Apps/Account/AccountMenu.tsx
  front/src/Apps/Account/accessTokens/AccountAccessToken.module.scss
  front/src/Apps/Account/accessTokens/AccountAccessToken.tsx
  front/src/Apps/Account/accessTokens/AccountAccessTokenCreate.tsx
  front/src/Apps/Account/accessTokens/AccountAccessTokenList.tsx
  front/src/Apps/Account/accessTokens/AccountNewAccessToken.tsx
  front/src/Apps/Account/apps/AccountAuthorizedApp.module.scss
  front/src/Apps/Account/apps/AccountAuthorizedApp.tsx
  front/src/Apps/Account/apps/AccountAuthorizedAppList.tsx
  front/src/Apps/Account/oauth2/AccountOauth2AppList.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/RhfPackagings.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/routes.ts
  front/src/form/bspaoh/components/Packagings.tsx
Labels: ready for review, ready to merge

#3498 [TRA-14684] Fixes DASRI revision button
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#3524 [TRA-14974] - Fix registre entrant qui ne se télécharge pas
  back/src/bsda/registry.ts
Labels: hotfix, ready for review

#3523 [tra-14897]fix recette Mon compte dsfr : Changer le wording du bouton en 'Valider' lorqu'on est en mode edition
  front/src/Apps/Account/AccountInfo/AccountInfoActionBar.tsx
Labels: ready for review, fix de recette

#3522 [tra-14989]Fix recette - BSDD Multimodal: le bouton réviser ne devrait pas apparaitre non plus pour les autres transporteurs
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, fix de recette

#3528 [tra-14705]fix recette mes applications : maj doc api + fix wording + delete entrée menu sur mobile
  apps/doc/docs/tutoriels/quickstart/access-token.md
  apps/doc/static/img/access-token-copy.png
  apps/doc/static/img/access-token-description.png
  apps/doc/static/img/access-token-generate.png
  apps/doc/static/img/access-token-list.png
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokens.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokensCreate.tsx
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review, fix de recette

#3503 [TRA 14360] Rendre BSDA en brouillon inaccessibles pour les autres entreprises
  Changelog.md
  back/src/activity-events/bsda/reducer.ts
  back/src/bsda/__tests__/factories.ts
  back/src/bsda/elastic.ts
  back/src/bsda/permissions.ts
  back/src/bsda/repository/bsda/create.ts
  back/src/bsda/resolvers/mutations/__tests__/delete.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/publish.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  back/src/bsda/resolvers/queries/bsdas.ts
  back/src/bsds/indexation/__tests__/bulkIndexBsds.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/registry/__tests__/streams.integration.ts
  libs/back/prisma/src/migrations/20240730143503_add_draft_access_bsda/migration.sql
  libs/back/prisma/src/schema.prisma
  libs/back/scripts/src/scripts/20240802142645389_bsda_draft_restriction.ts
Labels: ready for review

#3529 Ajoute les sourcemaps pour Sentry
  .github/workflows/deploy-recette.yml
  .github/workflows/deploy.yml
  apps/api/project.json
  front/vite.config.ts
Labels: ready for review

#3527 [TRA 15005] - Ajoute la possibilité de réviser la quantité du destinataire si entreposage provisoire
  Changelog.md
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
Labels: ready for review

#3526 [TRA-15007] - Accepter une demande de rattachement lorsque l'utilisateur ayant fait la demande est invité dans l'entreprise
  Changelog.md
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.integration.ts
  back/src/users/resolvers/mutations/__tests__/inviteUserToCompany.test.ts
  back/src/users/resolvers/mutations/inviteUserToCompany.ts
  back/src/users/resolvers/mutations/inviteUserToCompanyService.ts
Labels: ready for review

#3509 tra-14553 Bsdasri suppression du champ volume de BsdasriReceptionInput
  Changelog.md
  back/src/bsdasris/__tests__/factories.integration.ts
  back/src/bsdasris/__tests__/factories.ts
  back/src/bsdasris/examples/fixtures.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  back/src/bsdasris/typeDefs/bsdasri.objects.graphql
  libs/back/prisma/src/schema.prisma
Labels: ready for review

#3533 [TRA-15014] ETQ utilisateur je peux signer la réception ET l'acceptation de l'entreposage provisoire en même temps
  front/src/Apps/Dashboard/Components/Validation/BSDD/SignReception.tsx
Labels: ready for review, ready to merge

#3535 [TRA-14705] Changes labels
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokenRevoke.tsx
  front/src/Apps/Account/AccountApplications/AccessTokens/AccountApplicationsAccessTokensRevokeAll.tsx
  front/src/Apps/Account/AccountApplications/AutorizedApplications/AccountApplicationsAuthorizedApplicationsRevoke.tsx
Labels: ready for review, fix de recette

#3543 Résoudre problème de permissions à la suppression BSDA en status initial
  back/src/bsda/permissions.ts
Labels: hotfix, ready for review

#3544 [TRA 15033] Visibilité du bouton Signer en cas d'entreprise de travaux
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: hotfix, ready for review
