Repository MTES-MCT/trackdechets, pull requests merged in 2025-04, with the labels that each got.

#4076 [TRA-16055] Adds new DSFR tooltips
  e2e/src/utils/company.ts
  front/src/Apps/Account/fields/AccountBooleanField.tsx
  front/src/Apps/Account/fields/AccountField.tsx
  front/src/Apps/Account/fields/AccountFieldNotEditable.tsx
  front/src/Apps/Account/fields/forms/AccountFormCompanyWorkerCertification.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeCheckbox.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/WorkerCertificationForm.tsx
  front/src/Apps/Forms/Components/IdentificationNumbers/IdentificationNumber.tsx
  front/src/Apps/common/Components/OperationModeSelect/RhfOperationModeSelect.tsx
  front/src/Apps/common/Components/Tooltip/Tooltip.tsx
  front/src/common/components/EstimatedQuantityTooltip.tsx
  front/src/common/components/OperationModeSelect.tsx
  front/src/common/components/Tooltip.module.scss
  front/src/common/components/Tooltip.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterPlates.tsx
  front/src/dashboard/detail/common/Components.tsx
  front/src/form/bsda/stepper/steps/Transport.tsx
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
  front/src/form/bsdasri/steps/Destination.tsx
  front/src/form/bsdasri/steps/Emitter.tsx
  front/src/form/bsdasri/steps/Transport.tsx
  front/src/form/bsdasri/steps/Type.tsx
  front/src/form/bsdd/Emitter.tsx
  front/src/form/bsdd/Recipient.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/components/parcel-number/ParcelNumber.tsx
  front/src/form/bsdd/components/temporaryStorage/TemporaryStorage.tsx
  front/src/form/bsff/BsffTypeSelector.tsx
  package-lock.json
  package.json
Labels: ready for review

#4077 [TRA-16170] Correction des champs d'adresse splittée incorrects
  back/src/companies/__tests__/companyUtils.integration.ts
  back/src/companies/companyUtils.ts
  back/src/scripts/bin/fixCompaniesSplittedAdresses.ts
Labels: ready for review

#4081 [TRA-16220] ETQ utilisateur de l'import registre par API, je souhaite recevoir en retour les déclarations par statut (ajoutées, modifiées, ignorées, annulées)
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToManagedRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToSsdRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToTransportedRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/genericAddToRegistry.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
Labels: ready for review

#4058 [tra-16056]Remplacer 'N°:' par une icône de copier coller sur le tableau de bord sur les bordereaux + copier au clic
  e2e/src/utils/bsvhu.ts
  e2e/src/utils/dashboardFilters.ts
  front/jest.config.js
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
Labels: ready for review, ready to merge

#4083 [tra-16108]fix recette
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/login/Signup.tsx
Labels: ready for review, fix de recette

#4087 [TRA-15529] Fix aperçu vhu
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewContent.tsx
  front/src/Apps/common/queries/fragments/bsvhu.ts
Labels: ready for review, fix de recette

#4088 [TRA 16212] - Correction de l'affichage de la liste d'établissements pour les registres
  Changelog.md
  front/src/Apps/common/Components/Combobox/Combobox.tsx
  front/src/Apps/common/hooks/useOnClickOutsideRefTarget.ts
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/companyImport/FileImportsTable.tsx
Labels: ready for review, ready to merge

#4085 [tra-14734]fix recette
  front/src/Apps/Dashboard/Components/Revision/wordingsRevision.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
Labels: ready for review, fix de recette

#4084 [tra-16107] fix recette
  front/src/Apps/Companies/AccountCompanyOrientation.tsx
  front/src/Apps/Companies/common/utils.ts
  front/src/Apps/common/types/bsdTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/form/bsda/stepper/steps/Destination.tsx
  front/src/form/bsda/stepper/steps/Transporter.tsx
  front/src/form/bsda/stepper/steps/Worker.tsx
Labels: ready for review, fix de recette

#4090 [tra-16056]fix recette
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
Labels: ready for review, fix de recette

#4075 [TRA-16207] Fix Erreur serveur lors de la suppression d'un utilisateur via le panneau d'admin
  back/src/scripts/prisma/hardDeleteUser.ts
  back/src/users/resolvers/mutations/__tests__/anonymizeUser.integration.ts
  back/src/users/resolvers/mutations/anonymizeUser.ts
Labels: ready for review, ready to merge

#4089 [tra-16240]Ne pas permettre de valider une révision si pas de changement dans les conditionnements
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
Labels: ready for review, ready to merge, fix de recette

#4092 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#4093 [tra-16089]fix recette
  front/src/dashboard/detail/bsff/BsffDetailContent.tsx
Labels: ready for review, fix de recette

#4095 [tra-16108] fix recette : Corriger les endroits où il n'y a pas d'espace avant ':'
  front/src/Apps/Account/accountSchema.ts
  front/src/Apps/Companies/AccountCompanyOrientation.tsx
  front/src/Apps/Companies/common/utils.ts
  front/src/admin/registry/Registry.tsx
Labels: ready for review, fix de recette

#4094 Updates changelog
  Changelog.md
Labels: ready for review

#4099 [tra-9990] fix regression : Compléter automatiquement les champs de contact de la destination à la création d'un BSDA de collecte en déchetterie avec ceux de l'établissement
  front/src/Apps/common/queries/company/query.ts
Labels: ready for review, fix de recette

#4106 [hotfix][tra-16240]Ne pas permettre de valider une révision si pas de changement dans les conditionnements
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
Labels: bug, hotfix

#4108 [tra-16199] Déplacer le registre exhaustif dans l'onglet Mes registres (beta) / Exports (1ère partie) + fix accessibilité (lien évitement + combobox navigable)
  front/src/Apps/common/Components/A11ySkipLinks/A11ySkipLinks.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Apps/routes.ts
  front/src/dashboard/exports/ExportsForm.tsx
  front/src/dashboard/exports/Registry.tsx
  front/src/dashboard/exports/RegistryMenu.tsx
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/RegistryMenu.tsx
  front/src/dashboard/registry/RegistryRoutes.tsx
Labels: ready for review

#4096 [TRA-13446] Sur le PDF du BSD de tournée dédiée, ajout de la phrase "Liste des producteurs initiaux en annexe" au-dessus du titre "1.2 Point de collecte/chantier"
  back/src/forms/pdf/components/BsddPdf.tsx
Labels: ready for review

#4117 [TRA-16302] Hotfix: correction des délimiters dans les templates Registre V2, "," > ";"
  libs/back/registry/src/scripts/generateModels.ts
Labels: ready for review

#4118 Merge des hotfix sur dev
  back/src/common/post/index.ts
  back/src/common/post/templates/adminRequestVerificationCodeLetter.html
  libs/back/registry/src/scripts/generateModels.ts
Labels: ready for review

#4121 [TRA-16314] Hotfix - Correction de la documentation sur le BSDA
  back/src/bsda/typeDefs/bsda.inputs.graphql
Labels: ready for review, ready to merge

#4098 [TRA-15993] Mise à jour des modes d'opération
  back/src/common/__tests__/operationModes.test.ts
  back/src/common/operationModes.ts
  front/src/Apps/common/operationModes.test.ts
  front/src/Apps/common/operationModes.ts
  front/src/common/components/OperationModeSelect.tsx
Labels: ready for review, ready to merge

#4124 Get a name for all middlewares
  back/src/common/middlewares/correlationId.ts
  back/src/common/middlewares/namedMiddleware.ts
  back/src/server.ts
Labels: ready for review

#4128 [TRA-16337] Hotfix: Correction du parseur de numéro de TVA pour accepter les nouveaux numéros Belges commençant par 1
  libs/shared/constants/src/belgium.ts
  libs/shared/constants/src/companySearchHelpers.ts
Labels: ready for review, ready to merge

#4120 [TRA-16354] Mise à jour des logos & du CSS dans les courriers
  back/src/common/post/templates/adminRequestVerificationCodeLetter.html
  back/src/common/post/templates/verificationCodeLetter.html
Labels: ready for review, ready to merge

#4112 [TRA-12187] Il n'est plus possible de sélectionner des dates dans le passé pour les récépissés d'établissements
  back/src/companies/resolvers/mutations/__tests__/createBrokerReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/createTraderReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/createTransporterReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/createWorkerCertification.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateBrokerReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateTraderReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateTransporterReceipt.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateWorkerCertification.integration.ts
  back/src/companies/resolvers/mutations/createWorkerCertification.ts
  back/src/companies/validation.ts
  front/src/Apps/Companies/common/Components/CompanyTypeForm/RecepisseForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/WorkerCertificationForm.tsx
Labels: ready for review, ready to merge

#4126 [tra-16238]Mettre à jour les informations de contact de l'onglet Destination du PAOH
  front/src/Apps/Dashboard/Creation/bspaoh/steps/Destination.tsx
Labels: ready for review

#4114 [TRA-16300] Ajout de la possibilité de limiter la taille des payloads par query / mutation GraphQL
  back/src/common/plugins/gqlPayloadSizeLimiterPlugin.ts
  back/src/server.ts
Labels: ready for review, ready to merge

#4130 [tra-15834]Harmoniser chacun des onglets sur la plateforme
  front/src/Apps/Account/AccountContentWrapper.module.scss
  front/src/Apps/Account/AccountContentWrapper.tsx
  front/src/Apps/Account/AccountInfo/AccountInfo.tsx
  front/src/Apps/Companies/CompaniesList/CompaniesList.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/bsdCardList.scss
  front/src/Apps/Dashboard/dashboard.scss
  front/src/Apps/common/Components/Container/Container.tsx
  front/src/Apps/common/Components/Filters/Filters.tsx
  front/src/Apps/common/Components/Filters/filters.scss
  front/src/Pages/Dashboard.tsx
  front/src/Pages/dashboard.scss
  front/src/admin/Admin.tsx
  front/src/admin/adminRequests/AdminRequests.tsx
  front/src/admin/anonymousCompany/CreateAnonymousCompanyForm.tsx
  front/src/admin/bsd/BsdAdmin.tsx
  front/src/admin/bulkProfilesUpdate/BulkprofilesUpdateAdmin.tsx
  front/src/admin/companies/CompaniesDashboard.tsx
  front/src/admin/company/MembersAdmin.tsx
  front/src/admin/registry/Registry.tsx
  front/src/admin/user/anonymizeUser.tsx
  front/src/admin/user/impersonate.tsx
  front/src/admin/verification/CompaniesVerificationTable.scss
  front/src/admin/verification/actions/CompanyVerificationActions.tsx
  front/src/dashboard/exports/ExportsForms.module.scss
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/RegistryRoutes.tsx
  front/src/dashboard/registry/companyImport/CompanyImports.tsx
  front/src/dashboard/registry/companyImport/StatsTab.tsx
  front/src/dashboard/registry/myLines/MyLines.tsx
Labels: ready for review

#4119 Fix/ Droits S3 des modèles de registre
  libs/back/registry/src/scripts/generateModels.ts
Labels: ready for review

#4127 Registre - Insertion d'une ligne précedemment annulée
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  libs/back/registry/src/incomingTexs/validation/transform.ts
  libs/back/registry/src/incomingWaste/validation/transform.ts
  libs/back/registry/src/managed/validation/transform.ts
  libs/back/registry/src/outgoingTexs/validation/transform.ts
  libs/back/registry/src/outgoingWaste/validation/transform.ts
  libs/back/registry/src/shared/transform.ts
  libs/back/registry/src/ssd/validation/transform.ts
  libs/back/registry/src/transported/validation/transform.ts
Labels: ready for review

#4123 [tra-16210]Compléter la pastille de la timeline même lorsque l'émetteur n'a pas signé (VHU, situation irrégulière)
  front/src/Apps/Dashboard/Validation/Bsvhu/BsvhuJourneySummary.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
Labels: ready for review

#4138 [tra-15585] Mise à jour du texte présent dans le bandeau
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#4104 [TRA-16009 | TRA-16010 | TRA-16200 | TRA-16201 | TRA-16011] Permettre l'ajout d'un volume et de numéros d'identifications sur les contenants d'un BSDA
  Changelog.md
  back/src/bsda/__tests__/converter.test.ts
  back/src/bsda/converter.ts
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/resolvers/mutations/__tests__/createDraftBsda.integration.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/typeDefs/bsda.objects.graphql
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/schema.ts
  back/src/common/pdf/components/PackagingsTable.tsx
  back/src/common/pdf/components/__tests__/PackagingsTable.test.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/Appendix1ProducerRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/Forms/Components/PackagingList/FormikPackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/FormikPackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingList.test.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/RhfPackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/RhfPackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/helpers.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/Apps/common/queries/reviews/BsdaReviewQuery.ts
  front/src/Apps/common/utils/packagingsBsddSummary.ts
  front/src/common/__tests__/packagings.test.ts
  front/src/common/packagings.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteEmissionSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteTransportSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsResealedModalContent.tsx
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  front/src/form/bsda/components/bsdaPicker/BsdaPicker.tsx
  front/src/form/bsda/stepper/BsdaStepList.tsx
  front/src/form/bsda/stepper/initial-state.ts
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
  front/src/form/bsdd/components/appendix/__tests__/helpers.test.ts
  front/src/form/bsdd/components/appendix/helpers.ts
  front/src/form/bsdd/utils/initial-state.ts
Labels: ready for review

#4143 Registre - Déplacement de colonnes
  libs/back/registry/src/incomingTexs/constants.ts
  libs/back/registry/src/incomingWaste/constants.ts
Labels: ready for review

#4142 Registry - ajout d'updatedAt
  libs/back/prisma/src/migrations/20250423111714_registry_add_updated_at/migration.sql
  libs/back/prisma/src/schema/registry.prisma
Labels: ready for review

#4137 [TRA 16366] - Info sur le sélecteur de date modale d'export registres
  front/src/dashboard/registry/ExportModal.tsx
Labels: ready for review, ready to merge

#4147 [TRA-16388] Hotfix: Correction du code de vérification des différentiels sur les BSFF
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffPackaging.integration.ts
  back/src/bsffs/validation/bsff/index.ts
Labels: ready for review, ready to merge

#4141 [tra-16239]Corriger le décalage du mode de transport avec immatriculation sur BSDA
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.tsx
Labels: ready for review

#4146 [tra-16256]Corrections restants sur l'aperçu du BSVHU
  front/src/Apps/Dashboard/Preview/BSDPreviewUtils.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewTransport.tsx
Labels: ready for review

#4110 [TRA-16109] Affichage des erreurs Zod en français
  back/src/__tests__/errors.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/createBspaoh.integration.ts
  back/src/server.ts
  back/src/users/resolvers/queries/__tests__/membershipRequests.integration.ts
  front/src/App.tsx
  front/src/form/bsff/utils/schema.ts
  package-lock.json
  package.json
Labels: ready for review, ready to merge

#4116 [TRA-13446] Correction de l'affichage dans le PDF BSDD
  back/src/forms/pdf/components/BsddPdf.tsx
Labels: ready for review

#4153 [tra-16255] fix focustrap to propagate click event
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
Labels: ready for review, fix de recette

#4152 [tra-15834]add padding
  front/src/Apps/Companies/CompaniesList/SearchableCompaniesList.tsx
  front/src/Apps/Dashboard/dashboard.scss
Labels: ready for review, fix de recette

#4154 [tra-15834]fix recette
  front/src/Apps/Account/AccountInfo/AccountFormChangePassword.tsx
  front/src/Apps/Account/AccountInfo/AccountInfo.tsx
  front/src/dashboard/exports/ExportsForm.tsx
  front/src/dashboard/registry/RegistryTable.tsx
  front/src/dashboard/registry/companyImport/FileImportsTable.tsx
  front/src/dashboard/registry/companyImport/StatsTab.tsx
  front/src/dashboard/registry/myLines/MyLines.tsx
Labels: ready for review, fix de recette

#4140 Rendre le champ emitterWastePackagings requis à la signature émetteur au lieu de la publication
  Changelog.md
  back/src/bsdasris/resolvers/mutations/__tests__/publishBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEmission.integration.ts
  back/src/bsdasris/validation.ts
Labels: ready for review, ready to merge

#4156 [tra-15834]retour recette : fix table width
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/companyImport/StatsTab.tsx
Labels: ready for review, ready to merge, fix de recette
