Repository MTES-MCT/trackdechets, pull requests merged in 2025-03, with the labels that each got.

#3996 [TRA_15736] Permettre d'Enregistrer un VHU en brouillon lorsque le Type de conditionnement n'est pas sélectionné et afficher un message d'erreur à la publication si celui-ci est manquant
  Changelog.md
  back/src/bsvhu/resolvers/mutations/__tests__/createDraftBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/publishBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  back/src/bsvhu/validation/refinements.ts
Labels: ready for review, ready to merge

#4004 [TRA-15976] Fixes company switcher and saved orgId
  front/src/Apps/common/Components/CompanySwitcher/CompanySwitcher.tsx
Labels: ready for review

#4005 Corrections des erreurs en recette
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/converter.ts
Labels: ready for review, ready to merge

#4007 [TRA-15295] HOTFIX Mise à jour du texte présent dans le bandeau
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: hotfix, ready for review

#3944 [TRA-15707] Ajout des informations d'adresses splittées à l'objet Company
  back/src/common/__tests__/addresses.test.ts
  back/src/common/addresses.ts
  back/src/companies/__tests__/companyUtils.integration.ts
  back/src/companies/companyUtils.ts
  back/src/companies/database.ts
  back/src/companies/resolvers/mutations/__tests__/createCompany.integration.ts
  back/src/companies/resolvers/mutations/__tests__/updateCompany.integration.ts
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/mutations/updateCompany.ts
  back/src/scripts/bin/updateCompaniesSplittedAdresses.ts
  back/src/users/bulk-creation/__tests__/bulk-create.integration.ts
  back/src/users/bulk-creation/__tests__/csv/etablissements.csv
  back/src/users/bulk-creation/__tests__/csv/roles.csv
  back/src/users/bulk-creation/__tests__/loaders.test.ts
  back/src/users/bulk-creation/index.ts
  back/src/users/bulk-creation/sirene.ts
  back/src/users/bulk-creation/types.ts
  libs/back/prisma/src/migrations/20250130133907_add_company_splitted_address/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#4001 [TRA-15970] Enlever la limite des 60 jours pour permettre une correction du "code opération réalisé" par contenant
  Changelog.md
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffPackaging.integration.ts
  back/src/bsffs/validation/bsffPackaging/rules.ts
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingForm.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingsModal.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3980 [TRA-15674] Sortir Conditionné pour pipeline de la liste des conditionnements
  Changelog.md
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/common/typeDefs/common.enums.graphql
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/compat.ts
  back/src/forms/converter.ts
  back/src/forms/edition.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/registryV2.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/signEmissionForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/createForm.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
  back/src/forms/resolvers/mutations/signEmissionForm.ts
  back/src/forms/resolvers/mutations/updateForm.ts
  back/src/forms/typeDefs/bsdd.enums.graphql
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/types.ts
  back/src/forms/validation.ts
  back/src/forms/workflow/__tests__/machine.test.ts
  back/src/forms/workflow/machine.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/utils/packagingsBsddSummary.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormJourneySummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteEmissionSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionFormModalContent.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bsdd/Transporter.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/utils/initial-state.ts
  libs/back/prisma/src/migrations/20250213142801_add_form_is_direct_supply/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#3991 [TRA-15364] Si la révision d'un BSDA ne cible que les champs wasteSealedFields & packagings, l'approbation de l'émetteur n'est pas nécessaire
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsda/utils.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  front/src/Apps/Account/AccountNotifications/utils.ts
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/bsda-wasteSealNumbers-or-packagings-revision.html
Labels: ready for review, ready to merge

#4006 Registry - Améliorations
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/forms/registryV2.ts
  back/src/registryV2/columns.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/queries/__tests__/registryChangeAggregates.integration.ts
  back/src/registryV2/typeDefs/registryV2.enums.graphql
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/types.ts
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/dashboard/registry/ImportModal.tsx
  front/src/dashboard/registry/RegistryMenu.tsx
  libs/back/prisma/src/migrations/20250303161601_registry_remove_municipalities_names/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/incomingTexs/constants.ts
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingTexs/validation/index.ts
  libs/back/registry/src/incomingTexs/validation/refinement.ts
  libs/back/registry/src/incomingTexs/validation/schema.ts
  libs/back/registry/src/incomingWaste/constants.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/incomingWaste/validation/refinement.ts
  libs/back/registry/src/incomingWaste/validation/schema.ts
  libs/back/registry/src/managed/constants.ts
  libs/back/registry/src/managed/validation/refinement.ts
  libs/back/registry/src/managed/validation/schema.ts
  libs/back/registry/src/outgoingTexs/constants.ts
  libs/back/registry/src/outgoingTexs/registry.ts
  libs/back/registry/src/outgoingTexs/validation/index.ts
  libs/back/registry/src/outgoingTexs/validation/refinement.ts
  libs/back/registry/src/outgoingTexs/validation/schema.ts
  libs/back/registry/src/outgoingWaste/constants.ts
  libs/back/registry/src/outgoingWaste/registry.ts
  libs/back/registry/src/outgoingWaste/validation/refinement.ts
  libs/back/registry/src/outgoingWaste/validation/schema.ts
  libs/back/registry/src/s3.ts
  libs/back/registry/src/shared/refinement.ts
  libs/back/registry/src/shared/schemas.ts
Labels: ready for review

#4013 [TRA-16082] Updates oauth logo
  front/src/oauth/AuthDialog.tsx
Labels: ready for review

#4012 [tra-15920]fix recette signature Vhu: poids estimé/réel
  front/src/Apps/common/queries/fragments/bsdd.ts
Labels: ready for review, ready to merge

#4002 [TRA-15158 | Fix recette] Révision de la quantité refusée sur les BSDD avec entreposage provisoire
  back/src/forms/converter.ts
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/resolvers/FormRevisionRequest.ts
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/validation.ts
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  libs/back/prisma/src/migrations/20250228093927_add_revision_temp_storage_quantity_refused/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#4016 Mise à jour du Changelog
  Changelog.md
Labels: ready for review, ready to merge

#4014 Corrections cahier de recette Annexe 2 et entreposage provisoire
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/converter.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/resolvers/mutations/__tests__/signTransportForm.integration.ts
  back/src/forms/resolvers/mutations/signTransportForm.ts
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/validation.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/PackagingList/PackagingForm.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormJourneySummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteEmissionSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionFormModalContent.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready to merge

#4020 Fix csp for map tiles provider
  apps/ui/src/main.ts
Labels: ready to merge

#4024 [TRA-16081] Fixes redirect url
  front/src/graphql-client.ts
Labels: ready for review, fix de recette

#4017 Export registre transporté + géré
  Changelog.md
  apps/doc/docs/reference/validation/bsvhu.md
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/companies/resolvers/mutations/enableRegistryDndFromBsd.ts
  back/src/forms/registryV2.ts
  back/src/queue/jobs/processRegistryExport.ts
  back/src/registryV2/columns.ts
  back/src/registryV2/converters.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/types.ts
  back/src/scripts/bin/rebuildRegistryLookup.ts
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDndFromBsd.tsx
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/shared.tsx
  libs/back/prisma/src/migrations/20250227224647_transported_registry_mandatory_collectiondate/migration.sql
  libs/back/prisma/src/migrations/20250227225004_add_registry_transported_lookup_relation/migration.sql
  libs/back/prisma/src/migrations/20250227230719_transported_registry_mandatory_unloading_date/migration.sql
  libs/back/prisma/src/migrations/20250306214721_add_managed_registry_to_lookup/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/index.ts
  libs/back/registry/src/managed/database.ts
  libs/back/registry/src/managed/registry.ts
  libs/back/registry/src/options.ts
  libs/back/registry/src/outgoingTexs/registry.ts
  libs/back/registry/src/outgoingWaste/registry.ts
  libs/back/registry/src/transported/database.ts
  libs/back/registry/src/transported/registry.ts
Labels: ready for review, ready to merge

#4027 [TRA 16017] - ajout de quantité sur exports BSDD & fix date sur paramètre d'activation BSD DND
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registryV2.ts
  back/src/forms/types.ts
  back/src/registryV2/columns.ts
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDndFromBsd.tsx
Labels: ready for review

#4003 [TRA-14706] L’installation de destination ne peut pas signer le traitement, message d’erreur « Le numéro de récépissé du transporteur n° 2 est obligatoire.. » en cas de transport multi-modal
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/sign.ts
Labels: ready for review, ready to merge

#4029 HOTFIX : problème d'affichage d'une révision portant sur le conditionnement
  back/src/forms/converter.ts
  back/src/forms/resolvers/queries/__tests__/formRevisionRequests.integration.ts
Labels: hotfix, ready for review, ready to merge

#4028 Rebuild de l'index des registres V2: petites améliorations
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/forms/registryV2.ts
  back/src/scripts/bin/rebuildRegistryLookup.ts
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/index.ts
  libs/back/registry/src/lookup/utils.ts
  libs/back/registry/src/managed/registry.ts
  libs/back/registry/src/outgoingTexs/registry.ts
  libs/back/registry/src/outgoingWaste/registry.ts
  libs/back/registry/src/ssd/registry.ts
  libs/back/registry/src/transported/registry.ts
Labels: ready for review

#4038 HOTFIX - résolution de problèmes divers
  back/src/common/typeDefs/common.enums.graphql
  back/src/forms/registryV2.ts
  back/src/registryV2/resolvers/RegistryImportAssociation.ts
  back/src/registryV2/resolvers/mutations/genericAddToRegistry.ts
  back/src/registryV2/resolvers/queries/registryImports.ts
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  front/src/dashboard/registry/companyImport/FileImportsTable.tsx
  front/src/dashboard/registry/shared.tsx
  libs/back/prisma/src/migrations/20250314103530_registry_operation_mode_add_autres_valorisations/migration.sql
  libs/back/prisma/src/schema/schema.prisma
  libs/back/registry/src/outgoingWaste/validation/index.ts
  libs/back/registry/src/shared/schemas.ts
Labels: ready for review

#4039 [TRA-16155] Permettre aux intégrateurs API d'accéder aux délégations registre en lecture
  Changelog.md
  apps/doc/docusaurus.config.js
  back/src/registryDelegation/resolvers/queries/registryDelegation.ts
  back/src/registryDelegation/resolvers/queries/registryDelegations.ts
  back/src/registryDelegation/typeDefs/private/registryDelegation.inputs.graphql
  back/src/registryDelegation/typeDefs/registryDelegation.enums.graphql
  back/src/registryDelegation/typeDefs/registryDelegation.inputs.graphql
  back/src/registryDelegation/typeDefs/registryDelegation.objects.graphql
  back/src/registryDelegation/typeDefs/registryDelegation.queries.graphql
Labels: ready for review, ready to merge

#4034 [TRA-16142] Mettre à jour la doc "Utiliser le playground" de la documentation développeur
  Changelog.md
  apps/doc/docs/guides/playground.md
  apps/doc/static/img/playground-docs.png
  apps/doc/static/img/playground-guide.png
  apps/doc/static/img/playground-query.png
  apps/doc/static/img/playground-token.png
  apps/doc/static/img/playground-variables.png
Labels: ready for review, ready to merge

#4044 [HOTFIX] - changement de l'indexation DD/DND des registres
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/managed/registry.ts
  libs/back/registry/src/outgoingWaste/registry.ts
  libs/back/registry/src/transported/registry.ts
Labels: ready for review

#4049 Hotfix registry import
  libs/back/registry/src/shared/transform.ts
Labels: ready for review

#4037 HOTFIX - Sélecteur d'entreprises à l'export registre
  back/src/companies/resolvers/Query.ts
  back/src/companies/resolvers/queries/registryCompanies.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/private/company.queries.graphql
  back/src/registryDelegation/resolvers/queries/registryDelegations.ts
  back/src/registryDelegation/resolvers/queries/utils/registryDelegations.utils.ts
  back/src/registryV2/resolvers/mutations/generateRegistryV2Export.ts
  back/src/users/resolvers/queries/myCompanies.ts
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/queries/registryDelegation/queries.ts
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/MyExports.module.scss
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/shared.tsx
Labels: ready for review

#4042 [TRA-16150] Impossibilité d'ajouter un transporteur via l'UI si la liste de transporteur est vide lors de l'édition d'un BSDD
  Changelog.md
  front/src/Apps/Forms/Components/TransporterList/TransporterList.test.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.tsx
Labels: ready for review

#4051 [TRA-16172] Corriger le fonctionnement du filtre `hasNextStep` sur la query forms
  Changelog.md
  back/src/forms/resolvers/queries/__tests__/forms.integration.ts
  back/src/forms/resolvers/queries/forms.ts
Labels: ready for review, ready to merge

#4063 Hotfix/ Registry & file type
  front/src/dashboard/registry/ImportModal.tsx
Labels: ready to merge

#4055 [tra-16083]Corriger la coquille 'lesquelles' > 'lesquels' dans Gérer tout (Mon compte > Notifications)
  front/src/Apps/Account/AccountNotifications/NotificationsUpdateAllModal.tsx
Labels: ready for review

#4054 [tra-16046]Renommer 'Numéros de containers' par 'Numéros de contenants' sur la modale de signature transporteur DASRI
  front/src/form/bsdasri/steps/Transport.tsx
Labels: ready for review

#4040 [tra-16108]Corriger les endroits où il n'y a pas d'espace avant ':', notamment affichage du récépissé de courtier et négociant
  front/src/Apps/Companies/CompaniesList/SearchableCompaniesList.tsx
  front/src/Apps/Companies/CompanyDigestSheet/CompanyDigestSheet.tsx
  front/src/Apps/Dashboard/Components/Recepisse/Recepisse.tsx
  front/src/Apps/Dashboard/Components/Revision/RevisionDetail/TraderAndBrokerDetail.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignEmission.tsx
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.test.tsx
  front/src/Apps/Forms/Components/TransporterRecepisse/TransporterRecepisse.tsx
  front/src/Apps/common/Components/WasteCodeSelector/WasteCodeSelector.tsx
  front/src/admin/reindex/Reindex.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ReceivedInfo.tsx
  front/src/dashboard/detail/bsdasri/BsdasriDetailContent.tsx
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/dashboard/detail/bsff/BsffDetailContent.tsx
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
  front/src/form/bsda/stepper/steps/Emitter.tsx
  front/src/form/bsda/stepper/steps/Operation.tsx
  front/src/form/bsda/stepper/steps/Worker.tsx
  front/src/form/bsdd/components/waste-code/WasteCode.tsx
  front/src/form/common/components/processing-operation/ProcessingOperation.tsx
Labels: ready for review

#4033 [tra-16089]Ne pas permettre d'accéder au PDF dans le menu d'action d'un BSFF lorsque celui-ci est au statut Brouillons
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review

#4025 [tra-14734]Repasse (design + wording) sur les modales de révision (tous BSD)
  front/src/Apps/Dashboard/Components/Revision/wordingsRevision.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/BsdaRequestRevisionCancelationInput.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/BsdasriRequestRevisionCancelationInput.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdasri/request/BsdasriRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/BsddRequestRevisionCancelationInput.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/ReviewableField/RhfReviewableField.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingForm.tsx
  front/src/Apps/common/Components/WasteCodeSelector/WasteCodeSelector.tsx
  front/src/form/common/components/dsfr-work-site/DsfrfWorkSiteAddress.tsx
  front/src/form/common/components/work-site/WorkSiteAddress.tsx
Labels: ready for review

#4036 [TRA-15529] Adds VHU new DSFR preview
  e2e/src/utils/bsvhu.ts
  front/src/Apps/Dashboard/Components/WasteDetails/WasteDetails.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/Preview/BSDPreviewComponents.tsx
  front/src/Apps/Dashboard/Preview/BSDPreviewContainer.tsx
  front/src/Apps/Dashboard/Preview/BSDPreviewHeader.tsx
  front/src/Apps/Dashboard/Preview/BSDPreviewTabs.tsx
  front/src/Apps/Dashboard/Preview/BSDPreviewUtils.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewActors.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewContent.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewDestination.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewEmitter.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewTransport.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewWaste.tsx
  front/src/admin/bsd/BsdDetailContent.tsx
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
  front/src/dashboard/detail/bsvhu/RouteBsvhusView.tsx
  front/src/dashboard/detail/bsvhu/index.ts
  front/src/dashboard/detail/index.ts
Labels: ready for review, ready to merge

#4068 HOTFIX - résolution de problème d'écriture concurrente sur RegistryLookup
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/forms/registryV2.ts
Labels: ready for review

#4069 [TRA-16157] Fixes VHU creation CSS
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
Labels: ready for review

#4070 [TRA-15982] Fixes mobile transporter menu
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review

#4071 [TRA-16084] Adds notifications page title
  front/src/Apps/routes.ts
Labels: ready for review

#4073 HOTFIX - Permettre aux établissements identifiés comme systèmes d'individuels d'être désignés comme producteurs sur un BSDD et BSDA
  back/src/bsda/resolvers/mutations/__tests__/createDraftBsda.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/validation.ts
Labels: ready for review, ready to merge

#4021 Registry form builder - SSD
  back/src/registryV2/resolvers/Query.ts
  back/src/registryV2/resolvers/queries/registryLookup.ts
  back/src/registryV2/resolvers/queries/registryLookups.ts
  back/src/registryV2/resolvers/queries/utils/registryLookup.util.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/typeDefs/registryV2.queries.graphql
  front/index.html
  front/src/Apps/common/Components/Combobox/Combobox.tsx
  front/src/Apps/common/Components/Modal/Modal.tsx
  front/src/Apps/common/Components/Portal/Portal.tsx
  front/src/Apps/common/queries/company/query.ts
  front/src/Apps/routes.ts
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/RegistryMenu.tsx
  front/src/dashboard/registry/RegistryRoutes.tsx
  front/src/dashboard/registry/companyImport/CompanyImports.tsx
  front/src/dashboard/registry/myLines/FormContainer.tsx
  front/src/dashboard/registry/myLines/MyLines.tsx
  front/src/dashboard/registry/shared.tsx
  front/src/form/registry/builder/FormBuilder.scss
  front/src/form/registry/builder/FormBuilder.tsx
  front/src/form/registry/builder/FormTab.tsx
  front/src/form/registry/builder/error.ts
  front/src/form/registry/builder/handler.ts
  front/src/form/registry/builder/types.ts
  front/src/form/registry/builder/utils.ts
  front/src/form/registry/common/CompanySelector.tsx
  front/src/form/registry/common/ReportFor.tsx
  front/src/form/registry/common/WasteCodeSelector.tsx
  front/src/form/registry/common/WeightSelector.tsx
  front/src/form/registry/ssd/RegistrySsdForm.tsx
  front/src/form/registry/ssd/SecondaryWasteCodes.tsx
  front/src/form/registry/ssd/query.ts
  front/src/form/registry/ssd/shape.ts
  libs/back/prisma/src/migrations/20250327204729_add_lookup_readable_id_idx/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/shared/schemas.ts
  libs/back/registry/src/ssd/validation/schema.ts
  libs/shared/constants/src/ADMINISTRATIVE_ACT.ts
  libs/shared/constants/src/index.ts
Labels: ready for review, ready to merge

#4053 [TRA-15971] Après signature de la réception, un VHU reste dans l'onglet "Pour action" du destinataire
  back/src/bsvhu/elastic.ts
  back/src/scripts/bin/reindexReceivedVHUs.ts
Labels: ready for review, ready to merge

#4066 Correction d'un flaky test
  back/src/registryDelegation/resolvers/__tests__/utils.integration.ts
Labels: ready for review, ready to merge

#4057 [TRA-15657] ETQ utilisateur je peux renseigner l'option "Comprend des véhicules électriques ou hybrides" pour un VHU
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsvhu/converter.ts
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/bsvhu/registry.ts
  back/src/bsvhu/registryV2.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhumetadata.integration.ts
  back/src/bsvhu/typeDefs/bsvhu.inputs.graphql
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/schema.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
  front/src/Apps/Dashboard/Preview/BSDPreviewComponents.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewContent.tsx
  front/src/Apps/common/queries/fragments/bsvhu.ts
  libs/back/prisma/src/migrations/20250321134815_add_vhu_contains_electric_or_hybrid_vehicles/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#4050 [TRA 16007] - Ne pas permettre d'accéder aux brouillons des autres acteurs sur le PAOH
  Changelog.md
  back/src/bsds/resolvers/queries/__tests__/bsds.bspaoh.integration.ts
  back/src/bspaoh/elastic.ts
Labels: ready for review, ready to merge

#4061 [TRA 14422] - Ne pas afficher les brouillons DASRI aux acteurs tiers
  Changelog.md
  back/src/bsdasris/__tests__/factories.ts
  back/src/bsdasris/edition.ts
  back/src/bsdasris/elastic.ts
  back/src/bsdasris/permissions.ts
  back/src/bsdasris/repository/bsdasri/create.ts
  back/src/bsdasris/repository/bsdasri/update.ts
  back/src/bsdasris/resolvers/mutations/__tests__/publishBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
  back/src/bsdasris/resolvers/queries/bsdasris.ts
  back/src/bsdasris/utils.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdasri.integration.ts
  back/src/bsvhu/repository/bsvhu/create.ts
  back/src/bsvhu/repository/bsvhu/update.ts
  libs/back/prisma/src/migrations/20250321211406_bsdasri_draft_access/migration.sql
  libs/back/prisma/src/schema/schema.prisma
  libs/back/scripts/src/scripts/20250321215658031_bsdasri_draft_restriction.ts
Labels: ready for review, ready to merge

#4059 [TRA-15475] Demander les codes INSEE des communes lorsqu'une parcelle est renseignée plutôt que le(s) code(s) postaux
  Changelog.md
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/compat.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/registry.ts
  back/src/forms/registryV2.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/types.ts
  back/src/forms/validation.ts
  back/src/registry/columns.ts
  back/src/registry/typeDefs/registry.objects.graphql
  back/src/registry/types.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
  front/src/form/bsdd/components/parcel-number/ParcelNumber.tsx
Labels: ready for review
