Repository MTES-MCT/trackdechets, pull requests merged in 2025-02, with the labels that each got.

#3942 Fix addToIncomingWasteRegistry tests
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingWasteRegistry.integration.ts
Labels: ready for review

#3938 [TRA-15663] Lors de la réception d'un VHU, si le déchet est refusé le statut du bordereau doit être REFUSED
  back/src/bsvhu/machine.ts
  back/src/bsvhu/resolvers/mutations/__tests__/signBsvhu.integration.ts
Labels: ready for review, ready to merge

#3934 TRA-14007 Il ne devrait pas être possible de valider la réception d'un BSDA avec un poids à 0
  Changelog.md
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/schema.ts
Labels: ready for review, ready to merge

#3935 [TRA-15149] Appliquer des restrictions sur le format de l'immatriculation
  Changelog.md
  back/src/__tests__/factories.ts
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/schema.ts
  back/src/bsdasris/__tests__/factories.ts
  back/src/bsdasris/__tests__/registry.integration.ts
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/duplicateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriReception.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriTransport.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signSynthesisBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  back/src/bsdasris/validation.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdasri.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bspaoh.integration.ts
  back/src/bsffs/__tests__/factories.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/typeDefs/bsff.inputs.graphql
  back/src/bsffs/validation/bsff/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsff/schema.ts
  back/src/bspaoh/__tests__/registry.integration.ts
  back/src/bspaoh/resolvers/mutations/__tests__/duplicateBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/duplicate.ts
  back/src/bspaoh/typeDefs/bspaoh.inputs.graphql
  back/src/bspaoh/validation/__tests__/validation.integration.ts
  back/src/bspaoh/validation/schema.ts
  back/src/bsvhu/__tests__/registry.integration.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/schema.ts
  back/src/common/validation/messages.ts
  back/src/common/validation/zod/refinement.ts
  back/src/common/validation/zod/schema.ts
  back/src/forms/__tests__/registry.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/resolvers/mutations/__tests__/createFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsAccepted.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsReceived.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markSegmentAsReadyToTakeOver.integration.ts
  back/src/forms/resolvers/mutations/__tests__/signTransportForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateFormTransporter.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateTransporterFields.integration.ts
  back/src/forms/resolvers/mutations/updateTransporterFields.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/validation.ts
  front/src/form/bsdasri/steps/Transport.tsx
Labels: ready for review, ready to merge

#3933 [TRA 15661] Rewords TransporterDisplay displayed information
  front/src/Apps/Forms/Components/TransporterDisplay/TransporterDisplay.tsx
Labels: ready for review

#3930 [TRA-15101] Erreur serveur lors de la lecture d'un BSDA suite à sa création par API - Le champ GraphQL BsdaPackagingType.type est rendu obligatoire
  Changelog.md
  back/src/bsda/typeDefs/bsda.inputs.graphql
Labels: ready for review

#3943 [TRA-15849] La requête companyInfos renvoie la bonne valeur pour isDormant
  back/src/companies/resolvers/queries/__tests__/companyInfos.integration.ts
  back/src/companies/search.ts
Labels: ready for review, ready to merge

#3926 [TRA 15687 - 2] Ajout d'une validation de l'éco-organisme sur BSDD + update Changelog + ajout d'eco-org BSVHU
  Changelog.md
  back/prisma/seed.model.ts
  back/src/__tests__/factories.ts
  back/src/__tests__/testWorkflow.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEcoorganismeEmission.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEcoorganismeEmissionWithSecretCode.integration.ts
  back/src/companies/resolvers/queries/__tests__/ecoOrganismes.integration.ts
  back/src/forms/__tests__/permissions.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/importPaperForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsSealed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/validation.ts
  libs/back/object-creator/src/objects.ts
Labels: ready for review, ready to merge

#3945 [TRA-15875 - HOTFIX] Page d'erreur lors de la création d'un BSDD de regroupement
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
Labels: hotfix, ready for review, ready to merge

#3947 Correction du path retourné en cas d'erreur de validation sur les plaques
  back/src/common/validation/zod/refinement.ts
Labels: ready for review, ready to merge, fix de recette

#3929 Documentation de la validation Zod
  CONTRIBUTING.md
  apps/doc/docs/reference/validation/bsda.md
  apps/doc/docs/reference/validation/bsff.md
  apps/doc/docs/reference/validation/bspaoh.md
  apps/doc/docs/reference/validation/bsvhu.md
  apps/doc/project.json
  apps/doc/sidebars.js
  back/src/bsda/validation/rules.ts
  back/src/bsffs/validation/bsff/rules.ts
  back/src/bspaoh/validation/rules.ts
  back/src/bsvhu/validation/rules.ts
  docs/ZodValidation.md
  scripts/validation-doc.js
Labels: ready for review

#3946 Registres V2 : Optimisation de la table de lookup et de la réindexation
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/forms/registryV2.ts
  back/src/queue/jobs/processRegistryExport.ts
  back/src/scripts/bin/rebuildRegistryLookup.ts
  docs/RegistryExportV2.md
  libs/back/prisma/src/migrations/20250131221330_modify_lookup_indexes/migration.sql
  libs/back/prisma/src/migrations/20250204153812_single_report_as_siret_lookup/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/lookup/utils.ts
  libs/back/registry/src/ssd/registry.ts
Labels: ready for review, ready to merge

#3952 Ajouter les guillemets manquant au json de la doc
  apps/doc/docs/guides/oauth2.md
  apps/doc/docs/guides/openidconnect.md
  apps/doc/docs/guides/sirene.md
  apps/doc/docs/reference/authentification.md
Labels: ready for review

#3955 Mise à jour du changelog
  Changelog.md
Labels: ready for review, ready to merge

#3957 Updates changelog
  Changelog.md
Labels: ready for review

#3951 [TRA-12707] Mettre au DSFR la signature du traitement du BSDD
  front/src/Apps/Dashboard/Components/RhfExtraEuropeanCompanyManualInput.tsx/RhfCountrySelector.tsx
  front/src/Apps/Dashboard/Components/RhfExtraEuropeanCompanyManualInput.tsx/RhfExtraEuropeanCompanyManualInput.tsx.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingForm.tsx
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsddValidation.test.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsddValidation.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsProcessed.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsProcessedModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/ProcessedInfo.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/WorkflowAction.tsx
  front/src/form/common/components/company/CountrySelector.scss
  front/src/form/common/components/company/CountrySelector.tsx
  front/src/form/common/components/company/ExtraEuropeanCompanyManualInput.tsx
Labels: ready for review, ready to merge

#3956 Correctif validation plaques d'immatriculation
  back/src/bsda/resolvers/mutations/__tests__/createBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/createBsdaTransporter.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/createDraftBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/deleteBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/publishBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/updateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/updateBsdaTransporter.integration.ts
  back/src/bsda/validation/schema.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasri.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/createBsffTransporter.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffTransporter.integration.ts
  back/src/bsffs/validation/bsff/schema.ts
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditModal.tsx
Labels: ready for review, fix de recette

#3958 [TRA-15663] Lors de la duplication d'un VHU, on ne duplique pas la date & signature de réception
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/duplicate.ts
Labels: ready for review, ready to merge

#3962 [TRA-15293]Updates banner
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
  front/src/Apps/common/Components/SurveyBanner/surveyBanner.scss
  front/src/Apps/common/Components/SurveyBanner/surveyBannerTypes.ts
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3963 [TRA-15359] Fixes header links
  front/src/Apps/common/Components/layout/Header.tsx
Labels: ready for review

#3969 Fix plate validation on temporary storage
  back/src/bsvhu/validation/refinements.ts
  back/src/forms/resolvers/mutations/__tests__/signTransportForm.integration.ts
  back/src/forms/resolvers/mutations/signTransportForm.ts
  back/src/forms/validation.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
Labels: fix de recette

#3974 [TRA-15925] Fixes foreign company form
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
Labels: hotfix, ready for review, ready to merge

#3953 [TRA 15831] - Exports registres V2 : Modale d'export et petites améliorations d'UX
  Changelog.md
  front/src/Apps/common/Components/Loader/Loaders.tsx
  front/src/dashboard/registry/CompanyImports.tsx
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/MyExports.module.scss
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/dashboard/registry/WasteCodeSwitcher.tsx
  front/src/dashboard/registry/shared.tsx
Labels: ready to merge

#3977 Display plate format hint
  front/src/Apps/Forms/Components/TransportPlates/TransportPlates.tsx
  front/src/Apps/Forms/Components/TransporterForm/TransporterForm.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteTransportSummary.tsx
Labels: hotfix, ready to merge

#3972 [tra-15262]Rendre optionnel les agréments à l'inscription d'un centre VHU (broyeur et/ou casse auto)
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAdd.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CertificationForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/FormikCompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/RhfCompanyTypeForm.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/VhuAgrementForm.tsx
Labels: ready for review, ready to merge

#3971 [tra-15844]Corriger l'affichage de la timeline dans les modales de signature PAOH
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/BspaohJourneySummary.tsx
  front/src/Apps/common/Components/Journey/DsfrJourney.module.scss
  front/src/Apps/common/Components/Journey/DsfrJourney.tsx
  front/src/common/components/index.ts
Labels: ready for review

#3960 [tra-15868]Retirer le retour à la ligne sur Mot de passe
  front/src/Apps/Account/AccountInfo/AccountInfoActionBar.tsx
  front/src/Apps/Account/AccountInfo/accountInfoActionBar.scss
Labels: ready for review, ready to merge

#3978 Correction validation des plaques sur le bsdd multimodal
  back/src/bsvhu/validation/refinements.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/validation.ts
Labels: hotfix, ready to merge

#3966 [TRA-15738] Retrait de D6 et D7 comme codes d'opération
  back/src/__tests__/factories.ts
  back/src/activity-events/bsdd/__tests__/bsdd.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
  libs/shared/constants/src/PROCESSING_AND_REUSE_OPERATIONS.ts
  libs/shared/constants/src/PROCESSING_OPERATIONS.ts
Labels: ready for review, ready to merge

#3981 [TRA-15876] Ajout d'espaces et de texte en gras dans l'email sur la création d'une délégation registre
  back/src/registryDelegation/resolvers/mutations/__tests__/createRegistryDelegation.integration.ts
  libs/back/mail/src/templates/mustache/registry-delegation-creation.html
Labels: ready for review

#3983 [tra-15878]Mettre à jour / DSFR le composant d'ajout de numéros d'identification sur le VHU
  e2e/src/utils/bsvhu.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/Apps/Forms/Components/TagsInput/TagsInputWrapper.tsx
Labels: ready for review

#3986 [HOTFIX] BSDD signoperation foreign company
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
Labels: hotfix, ready for review, ready to merge

#3976 [TRA 15251] Export des registres sortants V2
  back/src/bsda/database.ts
  back/src/bsda/registryV2.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsffs/database.ts
  back/src/bsffs/registryV2.ts
  back/src/bspaoh/converter.ts
  back/src/bspaoh/registryV2.ts
  back/src/bsvhu/registryV2.ts
  back/src/forms/compat.ts
  back/src/forms/registryV2.ts
  back/src/queue/jobs/processRegistryExport.ts
  back/src/registryV2/columns.ts
  back/src/registryV2/converters.ts
  back/src/registryV2/resolvers/mutations/generateRegistryV2Export.ts
  back/src/registryV2/streams.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/typeDefs/registryV2.queries.graphql
  back/src/registryV2/types.ts
  back/src/registryV2/utils.ts
  back/src/scripts/bin/rebuildRegistryLookup.ts
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/MyExports.module.scss
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/MyImports.module.scss
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/shared.tsx
  libs/back/prisma/src/migrations/20250207192930_outgoing_registry_lookup/migration.sql
  libs/back/prisma/src/migrations/20250213011603_registry_export_all_companies_flag/migration.sql
  libs/back/prisma/src/migrations/20250218123154_outgoing_dispatch_date_mandatory/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/incomingTexs/database.ts
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/index.ts
  libs/back/registry/src/options.ts
  libs/back/registry/src/outgoingTexs/database.ts
  libs/back/registry/src/outgoingTexs/registry.ts
  libs/back/registry/src/outgoingTexs/validation/schema.ts
  libs/back/registry/src/outgoingWaste/database.ts
  libs/back/registry/src/outgoingWaste/registry.ts
  libs/back/registry/src/outgoingWaste/validation/schema.ts
  libs/back/registry/src/ssd/registry.ts
Labels: ready to merge

#3973 [TRA-15899] Fixes waste tree max width
  front/src/Apps/common/Components/Modal/modal.scss
Labels: ready for review

#3990 [TRA-15459] Fixes VHU date mobile width
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuEmission.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuOperation.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuReception.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuTransport.tsx
Labels: ready for review

#3989 [TRA-15847] Adds wastes codes to BSDD appendix 1
  libs/shared/constants/src/WASTES.ts
Labels: ready for review

#3987 [TRA-15711] Adds new Company page
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Pages/Company/Company.tsx
  front/src/Pages/Company/CompanyMap.tsx
  front/src/company/Company.scss
  front/src/company/Company.tsx
  front/src/company/CompanyContact.scss
  front/src/company/CompanyContact.tsx
  front/src/company/CompanyDisclaimer.tsx
  front/src/company/CompanyHeader.tsx
  front/src/company/CompanyMap.scss
  front/src/company/CompanyRegistration.tsx
Labels: ready for review, ready to merge

#3984 [TRA-15262] Rendre optionnel les agréments à la publication d'un VHU
  Changelog.md
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/rules.ts
Labels: ready for review, ready to merge

#3992 [dev] Upgrades DSFR
  package-lock.json
  package.json
Labels: ready for review

#3982 Registre - Fix + Managed + Transported
  back/src/queue/jobs/processRegistryImport.ts
  back/src/registryV2/resolvers/Mutation.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToManagedRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToOutgoingWasteRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToTransportedRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/addToManagedRegistry.ts
  back/src/registryV2/resolvers/mutations/addToTransportedRegistry.ts
  back/src/registryV2/resolvers/mutations/genericAddToRegistry.ts
  back/src/registryV2/resolvers/queries/registryImports.ts
  back/src/registryV2/typeDefs/registryV2.enums.graphql
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  back/src/registryV2/typeDefs/registryV2.mutations.graphql
  front/src/dashboard/registry/CompanyImports.tsx
  front/src/dashboard/registry/ImportModal.tsx
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/shared.tsx
  libs/back/prisma/src/migrations/20250215133424_registry_add_transported_and_managed/migration.sql
  libs/back/prisma/src/migrations/20250215140856_fix_registry_import_type/migration.sql
  libs/back/prisma/src/migrations/20250218132312_registry_template_edit/migration.sql
  libs/back/prisma/src/migrations/20250219145223_registry_review_managed/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/prisma/src/schema/schema.prisma
  libs/back/registry/src/incomingTexs/constants.ts
  libs/back/registry/src/incomingTexs/validation/index.ts
  libs/back/registry/src/incomingTexs/validation/refinement.ts
  libs/back/registry/src/incomingTexs/validation/schema.ts
  libs/back/registry/src/incomingWaste/constants.ts
  libs/back/registry/src/incomingWaste/validation/index.ts
  libs/back/registry/src/incomingWaste/validation/refinement.ts
  libs/back/registry/src/incomingWaste/validation/schema.ts
  libs/back/registry/src/managed/constants.ts
  libs/back/registry/src/managed/database.ts
  libs/back/registry/src/managed/validation/index.ts
  libs/back/registry/src/managed/validation/refinement.ts
  libs/back/registry/src/managed/validation/schema.ts
  libs/back/registry/src/managed/validation/transform.ts
  libs/back/registry/src/options.ts
  libs/back/registry/src/outgoingTexs/validation/index.ts
  libs/back/registry/src/outgoingTexs/validation/refinement.ts
  libs/back/registry/src/outgoingTexs/validation/schema.ts
  libs/back/registry/src/outgoingWaste/validation/index.ts
  libs/back/registry/src/outgoingWaste/validation/refinement.ts
  libs/back/registry/src/outgoingWaste/validation/schema.ts
  libs/back/registry/src/shared/__tests__/schemas.test.ts
  libs/back/registry/src/shared/refinement.ts
  libs/back/registry/src/shared/schemas.ts
  libs/back/registry/src/ssd/validation/refinement.ts
  libs/back/registry/src/transported/constants.ts
  libs/back/registry/src/transported/database.ts
  libs/back/registry/src/transported/validation/index.ts
  libs/back/registry/src/transported/validation/refinement.ts
  libs/back/registry/src/transported/validation/schema.ts
  libs/back/registry/src/transported/validation/transform.ts
Labels: ready for review

#3995 [TRA-15711] Fixes DSFR links CSS
  front/src/Pages/Company/Company.tsx
  front/src/scss/index.scss
Labels: ready for review

#3979 [TRA-15625] Affiche sur le PDF les informations du courtier ET du négociant lorsque ces deux acteurs sont renseignés sur un BSDD
  Changelog.md
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/forms/pdf/components/BsddPdf.tsx
Labels: ready for review, ready to merge

#3999 [TRA-15976] Fixes company switcher
  front/src/Apps/Dashboard/DashboardRoutes.tsx
Labels: ready for review

#3994 [tra-15920]Afficher 'Poids estimé' ou 'Poids réel' dans le composant Informations de chaque modale de signature réception, acceptation et traitement selon le poids disponible
  front/src/Apps/Dashboard/Validation/BSDD/FormWasteSummary.tsx
Labels: ready for review

#3997 [tra-15459]le clavier virtuel ne doit pas cacher les champs de saisie
  front/src/Apps/common/Components/Modal/Modal.tsx
Labels: ready for review

#3936 [TRA 15675 | 15396 | 15767 | 15698 | 15700] Permettre l'ajout d'un volume et de numéros d'identifications sur les contenants d'un BSDD
  Changelog.md
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/converter.ts
  back/src/forms/pdf/__tests__/helpers.test.ts
  back/src/forms/pdf/components/BsddPdf.tsx
  back/src/forms/pdf/helpers.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/typeDefs/bsdd.objects.graphql
  back/src/forms/validation.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/Appendix1ProducerRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/Packagings/packagings.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/rules.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/Dashboard/Creation/bspaoh/utils/numbers.ts
  front/src/Apps/Forms/Components/PackagingList/FormikPackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/FormikPackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingList.test.tsx
  front/src/Apps/Forms/Components/PackagingList/PackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/RhfPackagingForm.tsx
  front/src/Apps/Forms/Components/PackagingList/RhfPackagingList.tsx
  front/src/Apps/Forms/Components/PackagingList/helpers.ts
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
  front/src/Apps/common/utils/packagingsBsddSummary.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteEmissionSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/FormWasteTransportSummary.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsResealedModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignEmissionFormModalContent.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/SignTransportFormModalContent.tsx
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.test.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelectWrapper.tsx
  front/src/form/bsdd/components/appendix/__tests__/helpers.test.ts
  front/src/form/bsdd/components/appendix/helpers.ts
  front/src/form/bsdd/components/packagings/Packagings.scss
  front/src/form/bsdd/components/packagings/Packagings.test.tsx
  front/src/form/bsdd/components/packagings/Packagings.tsx
  front/src/form/bsdd/utils/initial-state.ts
  front/src/form/bsdd/utils/schema.ts
  libs/shared/constants/src/__tests__/formHelpers.test.ts
  libs/shared/constants/src/formHelpers.ts
Labels: ready for review, ready to merge

#3988 [TRA 14872] - Paramètre d'affichage des BSDs DND dans les exports
  Changelog.md
  back/src/companies/resolvers/Mutation.ts
  back/src/companies/resolvers/mutations/enableRegistryDndFromBsd.ts
  back/src/companies/typeDefs/company.mutations.graphql
  back/src/companies/typeDefs/company.objects.graphql
  back/src/queue/jobs/processRegistryExport.ts
  docs/RegistryExportV2.md
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistry.scss
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistry.tsx
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDelegationAsDelegate.tsx
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDelegationAsDelegator.tsx
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDndFromBsd.scss
  front/src/Apps/Companies/CompanyRegistry/CompanyRegistryDndFromBsd.tsx
  front/src/Apps/Companies/CompanyRegistry/CreateRegistryDelegationModal.tsx
  front/src/Apps/Companies/CompanyRegistry/RegistryDelegationsTable.tsx
  front/src/Apps/Companies/CompanyRegistry/RevokeOrCancelRegistryDelegationModal.tsx
  front/src/Apps/Companies/common/fragments.ts
  front/src/dashboard/registry/ExportModal.tsx
  libs/back/prisma/src/migrations/20250218224616_add_company_registry_dnd_from_bsd/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#3823 [TRA-15269] La quantité refusée (champ quantityRefused) est désormais obligatoire sur les BSDD
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/forms/__tests__/validation.integration.ts
  back/src/forms/converter.ts
  back/src/forms/examples/fixtures.ts
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/__tests__/importPaperForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsAccepted.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsReceived.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsTempStored.integration.ts
  back/src/forms/resolvers/mutations/__tests__/markAsTempStorerAccepted.integration.ts
  back/src/forms/resolvers/mutations/__tests__/submitFormRevisionRequestApproval.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/validation.ts
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/AcceptedInfo.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsAccepted.tsx
  front/src/dashboard/components/BSDList/BSDD/WorkflowAction/MarkAsTempStorerAccepted.tsx
Labels: ready for review, ready to merge

#3961 [TRA-15158] Possibilité de réviser la quantité refusée d'un BSD + correctifs
  back/src/forms/converter.ts
  back/src/forms/typeDefs/bsdd.objects.graphql
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/BsddRequestRevisionCancelationInput.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/Components/ReviewableField/RhfReviewableField.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/common/queries/reviews/BsddReviewsQuery.ts
Labels: ready for review, ready to merge

#4000 Fixes company switcher
  front/src/login/auth.service.ts
Labels: ready for review, fix de recette
