Repository MTES-MCT/trackdechets, pull requests merged in 2025-08, with the labels that each got.

#4340 [TRA 16879] Adds warning for corepile removal
  front/src/form/bsdd/components/eco-organismes/EcoOrganismes.tsx
Labels: hotfix, ready to merge

#4315 [tra-15808]Investiguer les GET_BSDS abusifs
  front/src/Apps/Dashboard/Components/DashboardTabs/useNotificationQueries.tsx
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/Dashboard/hooks/useShowTransportTabs.ts
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
Labels: ready for review, ready to merge

#4332 [tra-16757]Ne pas permettre de renseigner des notations scientifiques dans les Input de type number
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/common/Components/NonScrollableInput/NonScrollableInput.tsx
Labels: ready for review

#4345 Migrate SIGNED_BY_PRODUCER bsdds from an ecoorganisme to another
  libs/back/scripts/src/scripts/20250804082129967_update-ecoorganisme-siret.ts
Labels: hotfix, ready for review

#4338 [TRA 16685] Adds watermarking to PDFs
  .env.model
  .github/workflows/e2e.yml
  back/src/common/pdf/assets/styles.css
  back/src/common/pdf/components/Document.tsx
  back/src/common/sentry.ts
  front/.env.model
  front/src/setupSentry.ts
  libs/back/env/src/index.ts
Labels: ready for review, ready to merge

#4358 [tra-16615]fix recette : fix affichage parcels map sur mobile
  front/src/form/registry/common/ParcelsVisualizer/ParcelsVisualizer.tsx
Labels: ready for review

#4344 [TRA 16092] Résoud problème de dates sur l'export exhaustif
  Changelog.md
  back/src/common/where.ts
  back/src/registryV2/elastic.ts
Labels: ready for review, ready to merge

#4347 [TRA 16895] Ajout du chemin manquant sur erreur d'import registre
  Changelog.md
  libs/back/registry/src/shared/refinement.ts
Labels: ready for review, ready to merge

#4356 Update node
  .github/workflows/build-and-test.yml
  .github/workflows/deploy-recette.yml
  .github/workflows/deploy.yml
  .github/workflows/e2e.yml
  .github/workflows/integration-tests.yml
  back/package.json
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/__tests__/publishBsvhu.integration.ts
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  e2e/package.json
  front/package.json
  front/src/Apps/common/Components/Combobox/Combobox.tsx
  front/src/common/helper.ts
  libs/back/tracer/src/index.ts
  package-lock.json
  package.json
Labels: ready for review, ready to merge

#4357 [TRA-16622] Renvoyer une erreur si un code déchet terre a été ajouté sur un registre déchets entrant ou sortant
  libs/back/registry/src/incomingWaste/validation/schema.ts
  libs/back/registry/src/outgoingWaste/validation/schema.ts
  libs/shared/constants/src/WASTES.ts
Labels: ready for review, ready to merge

#4341 [TRA 16549] Changement des règles de scellées BSVHU
  Changelog.md
  apps/doc/.gitignore
  apps/doc/docs/reference/validation/bsda.md
  apps/doc/docs/reference/validation/bsdasri.md
  apps/doc/docs/reference/validation/bsff.md
  apps/doc/docs/reference/validation/bspaoh.md
  apps/doc/docs/reference/validation/bsvhu.md
  back/src/bsvhu/resolvers/queries/__tests__/bsvhumetadata.integration.ts
  back/src/bsvhu/validation/rules.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  scripts/validation-doc.js
Labels: ready for review

#4368 [tra-16881]Retirer le bandeau Warning en lien avec la fermeture du SIRET de COREPILE
  front/src/form/bsdd/components/eco-organismes/EcoOrganismes.tsx
Labels: hotfix, ready for review, ready to merge

#4372 [tra-16282]Mise à jour du texte présent dans le bandeau
  e2e/src/utils/company.ts
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeCheckbox.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#4369 [tra-16615]fix de recette
  front/src/form/registry/builder/FormBuilder.scss
Labels: ready for review, ready to merge, fix de recette

#4374 Réglage du problème de Checkbox collées
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAdd.tsx
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAddForeign.tsx
  front/src/Apps/Companies/AccountCompanyAdd/AccountCompanyAddProducer.tsx
  front/src/Apps/Companies/CompanyInfo/CompanyProfileInformation.tsx
  front/src/Apps/Companies/CompanyManage/CompanyAdminRequest/CompanyCreateAdminRequestModal/CompanyCreateAdminRequestModalStep3.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/CompanyTypeCheckbox.tsx
  front/src/Apps/Companies/common/Components/CompanyTypeForm/WorkerCertificationForm.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Validation/BSDD/SignOperation.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/components/PackagingAcceptationWidget.tsx
  front/src/Apps/Dashboard/Validation/bsff/SignBsffPackagingForm.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/SelectWithSubOptions.tsx
  front/src/Apps/common/Components/SelectWithSubOptions/selectWithSubOptions.scss
  front/src/Apps/common/Components/SingleCheckbox/SingleCheckbox.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
  front/src/form/registry/common/WasteCodeSelector.tsx
  front/src/login/Signup.tsx
Labels: ready for review, ready to merge

#4371 Réglage de problème de mémoire à l'import registre + update status RegistryImport sur échecs en début de process
  back/src/queue/jobs/__tests__/processRegistryImport.integration.ts
  back/src/queue/jobs/processRegistryImport.ts
  libs/back/registry/src/database.ts
  libs/back/registry/src/import.ts
  libs/back/registry/src/index.ts
Labels: ready for review
