Repository MTES-MCT/trackdechets, pull requests merged in 2025-01, with the labels that each got.

#3872 fix registry tests
  back/src/queue/jobs/__tests__/processRegistryImport.integration.ts
  back/src/registryV2/resolvers/mutations/__tests__/addToSsdRegistry.integration.ts
Labels: ready to merge

#3837 [TRA-15628] Seul l'émetteur peut supprimer un BSVHU s'il l'a signé (SIGNED_BY_PRODUCER)
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3834 [TRA-15078] Le champ "Modifié le" des BSDD dans le dashboard affiche la valeur du updatedAt, pas du lastActionOn
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/common/queries/fragments/bsdd.ts
Labels: ready for review, ready to merge

#3833 [TRA-14910] Traduction des intitulés des packagings des DASRI dans le PDF
  back/src/bsdasris/pdf/components/PackagingInfosTable.tsx
Labels: ready for review, ready to merge

#3832 [TRA-15456] Les DASRI annulés vont dans l'onglet "Archives" et non "Suivis"
  back/src/bsdasris/__tests__/elastic.integration.ts
  back/src/bsdasris/elastic.ts
Labels: ready for review, ready to merge

#3854 [TRA-15564] Il n'est plus possible de dupliquer une Annexe 1 (BSDD)
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
  front/src/dashboard/detail/bsdd/BSDDetailContent.tsx
Labels: ready for review, ready to merge

#3852 [TRA-14396] Ajout d'un createdAt sur l'objet AnonymousCompany
  libs/back/prisma/src/migrations/20241219080834_anonymous_company_created_at/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#3858 [TRA-15665] Cas particuliers pour le mail sur le changement de CAP: ajout ou suppression de la nextDestination
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/update.ts
Labels: ready for review, ready to merge

#3874 [TRA-15638]- Supprimer l'annexe 2 d'un BSDD de regroupement lorsque celle-ci a bien été retirée
  Changelog.md
  front/src/form/bsdd/StepList.tsx
Labels: ready for review

#3847 [TRA 15459] Updates viewport
  front/index.html
Labels: ready for review, ready to merge

#3865 [TRA 15491] Reworks BSDD ecoorg messages
  front/src/form/bsda/stepper/steps/Emitter.tsx
  front/src/form/bsdd/Emitter.tsx
  front/src/form/bsdd/appendix1Producer/form.tsx
  front/src/form/bsdd/components/eco-organismes/EcoOrganismes.tsx
Labels: ready for review, ready to merge

#3845 [TRA 15605] Adds wording
  Changelog.md
  front/src/Apps/Companies/common/utils.ts
Labels: ready for review

#3875 [TRA-15074] Au chargement des quantités du tableau des Annexes 2, bien récupérer la quantité acceptée par l'installation de destination finale et non par l'entreposage provisoire (si BSDD-suite à regrouper) à la modification
  Changelog.md
  back/src/forms/converter.ts
  back/src/forms/resolvers/queries/__tests__/form.integration.ts
  back/src/forms/resolvers/queries/form.ts
Labels: ready for review, ready to merge

#3853 [TRA-15501] Permettre la modification des informations d'un contenant à la signature de son opération et après son traitement pendant 60 jours
  Changelog.md
  back/src/bsffs/repository/bsffPackaging/update.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffPackaging.integration.ts
  back/src/bsffs/validation/bsffPackaging/__tests__/validation.integration.ts
  back/src/bsffs/validation/bsffPackaging/rules.ts
  back/src/bsffs/validation/bsffPackaging/schema.ts
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/BsdAdditionalActionsButton.tsx
  front/src/Apps/Dashboard/Components/BsdAdditionalActionsButton/bsdAdditionalActionsButtonTypes.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCard/bsdCardTypes.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingButton.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingForm.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingModal.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingsModal.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignPackagings.tsx
  front/src/Apps/Dashboard/Signature/bsff/queries.ts
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsffValidation.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/RhfCompanyContactInfo/RhfCompanyContactInfo.tsx
  front/src/Apps/common/Components/OperationModeSelect/RhfOperationModeSelect.tsx
  front/src/Apps/common/queries/bsff/queries.ts
  front/src/Apps/common/queries/fragments/bsff.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/PackagingAction.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignAcceptation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignOperation.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/SignPackagings.tsx
  front/src/dashboard/components/BSDList/BSFF/WorkflowAction/WorkflowAction.tsx
  front/src/dashboard/components/BSDList/BSFF/index.tsx
  front/src/dashboard/detail/bsff/BsffDetailContent.tsx
Labels: ready for review

#3848 Renommer le titre de la colonne Quantité (kg) des DASRI sélectionnés à la création d'un DASRI de synthèse par 'Nombre'
  front/src/form/bsdasri/components/grouping/BsdasriTableSynthesis.tsx
Labels: ready for review, ready to merge

#3849 [tra-9990]Compléter automatiquement les champs de contact de la destination à la création d'un BSDA de collecte en déchetterie avec ceux de l'établissement
  front/src/form/bsda/stepper/steps/Destination.tsx
Labels: ready for review, ready to merge

#3850 [tra-15650]Si 'Installation en situation irrégulière' est coché, alors ne pas afficher le champ 'Numéro d'agrément démolisseur'
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
Labels: ready for review, ready to merge

#3851 [tra-15653]Ajouter '(identification par numéro de lots)' à la suite de En lots (wording) sur le type de conditionnement à la création d'un VHU
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
Labels: ready for review

#3856 [tra-15635]Lorsque je coche L'installation n'a pas de numéro SIRET après avoir renseigné un SIRET, l'établissement sélectionné (Company Selector) ainsi que ses informations de contact devraient se vider
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
Labels: ready for review

#3857 [tra-15656]Retirer l'affichage du Conditionnement sur l'Aperçu d'un VHU pour ne pas faire doublon avec Critères d'identification
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
Labels: ready for review

#3863 [tra-15659]Revoir le fonctionnement / les messages d'erreur affichés selon le type de transporteur sélectionné sur un VHU
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
Labels: ready for review

#3864 [tra-15660]Garder les infos de contact saisies par l'utilisateur même quand c'est une donnée vide
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Destination.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
Labels: ready for review

#3870 [tra-15647]Ne pas afficher le bouton d'action Signer sur le tableau de bord du transporteur lorsque le VHU est au statut INITIAL, que l'émetteur est situation irrégulière ET que le SIRET est inscrit sur Trackdéchets
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/dashboardServices.ts
Labels: ready for review, ready to merge

#3846 [TRA 15644] Removes default identification for VHU
  e2e/src/utils/bsvhu.ts
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
Labels: ready for review

#3878 [tra-15460]fix css mobile modale aperçu
  front/src/Apps/common/Components/Modal/modal.scss
Labels: ready for review, ready to merge

#3855 [TRA 15626 + TRA 15662] VHU: édition d'intermédiaires & émetteur inscrit sur TD
  Changelog.md
  back/src/bsda/validation/refinements.ts
  back/src/bsffs/validation/bsff/refinements.ts
  back/src/bsvhu/resolvers/mutations/__tests__/updateBsvhu.integration.ts
  back/src/bsvhu/resolvers/queries/__tests__/bsvhumetadata.integration.ts
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/index.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/rules.ts
  back/src/common/validation/intermediaries.ts
  back/src/common/validation/zod/refinement.ts
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/form/common/components/dsfr-work-site/DsfrfWorkSiteAddress.tsx
Labels: ready for review

#3876 [TRA-15655] Correction de la mise à jour des numéros d'identification sur le bsvhu
  Changelog.md
  front/src/Apps/Forms/Components/IdentificationNumbers/IdentificationNumber.tsx
Labels: ready for review, ready to merge

#3882 [tra-15650]fix recette vhu situation irréguliere vider le champ agrement + fix afficher le message d'erreur sur conditionnement en unité quand la valeur n'est pas sélectionée
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Emitter.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
Labels: ready for review, ready to merge, fix de recette

#3761 [TRA-15182] ETQ je ne peux pas créer un BSDA avec un siret fermé, mais je peux finaliser un BSDA avec un siret fermé
  back/src/bsda/resolvers/mutations/__tests__/create.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/createDraft.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/common/validation/zod/refinement.ts
Labels: ready for review, ready to merge

#3888 [TRA-14910] Traduction des types de contenants pour les DASRI de synthèse
  front/src/dashboard/detail/bsdasri/BsdasriDetailContent.tsx
  front/src/form/bsdasri/components/grouping/BsdasriTableSynthesis.tsx
Labels: ready for review, ready to merge

#3889 Afficher correctement le logo lorsque je consulte les informations d'un établissement et que je ne suis pas connectée
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/oauth/AuthDialog.tsx
Labels: ready for review

#3886 [Recette/tra-15501] Permettre la modification des informations d'un contenant à la signature de son opération et après son traitement pendant 60 jours
  back/src/bsffs/__tests__/factories.ts
  back/src/bsffs/__tests__/registry.integration.ts
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/bsffs/pdf/generator.tsx
  back/src/bsffs/registry.ts
  back/src/bsffs/repository/bsffPackaging/update.ts
  back/src/bsffs/resolvers/mutations/__tests__/updateBsffPackaging.integration.ts
  back/src/bsffs/validation/bsffPackaging/rules.ts
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingForm.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingModal.tsx
  front/src/Apps/Dashboard/Signature/bsff/SignBsffPackagingsModal.tsx
  front/src/Apps/Dashboard/Signature/bsff/queries.ts
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsffValidation.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/common/Components/NonScrollableInput/NonScrollableInput.tsx
  front/src/Apps/common/queries/fragments/bsff.ts
Labels: ready for review

#3885 [tra-9990]fix recette : Bsda de collecte en dechetterie - reprendre les informations de contact de la déchetterie dans l'onglet de destination
  front/src/form/bsda/stepper/steps/Destination.tsx
Labels: ready for review, fix de recette

#3879 [TRA-15708] Ajout d'un endpoint pour récupérer les demandes de rattachement en cours d'une entreprise
  back/src/users/repository/index.ts
  back/src/users/repository/membershipRequest/count.ts
  back/src/users/repository/membershipRequest/findMany.ts
  back/src/users/repository/types.ts
  back/src/users/resolvers/Query.ts
  back/src/users/resolvers/queries/__tests__/membershipRequests.integration.ts
  back/src/users/resolvers/queries/membershipRequests.ts
  back/src/users/typeDefs/private/user.inputs.graphql
  back/src/users/typeDefs/private/user.objects.graphql
  back/src/users/typeDefs/private/user.queries.graphql
Labels: ready for review, ready to merge

#3891 [TRA-14910] Traduction des types de contenants pour les DASRI (BsdasriWasteSummary)
  front/src/dashboard/components/BSDList/BSDasri/Summary/BsdasriWasteSummary.tsx
Labels: ready for review, ready to merge

#3887 [tra-15333]Permettre au créateur d'Effacer le composant transporteur lorsqu'il n'y a qu'un seul transporteur de visé
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.test.tsx
  front/src/Apps/Forms/Components/TransporterAccordion/TransporterAccordion.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.test.tsx
  front/src/Apps/Forms/Components/TransporterList/TransporterList.tsx
Labels: ready for review, ready to merge

#3901 [TRA-14876] Updates banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#3900 Correction headers csp
  back/src/server.ts
Labels: ready for review, ready to merge

#3898 [TRA-14915] Recette - gestion des plaques et mode de transport
  back/src/bsvhu/converter.ts
  back/src/bsvhu/typeDefs/bsvhu.inputs.graphql
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/index.ts
  back/src/bsvhu/validation/refinements.ts
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/schema.ts
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/TransporterInfoEditModal/TransporterInfoEditModal.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Transporter.tsx
  front/src/Apps/Dashboard/Creation/utils.ts
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/SignTransport.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuTransport.tsx
  front/src/Apps/Dashboard/bsdMapper.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/TagsInput/TagsInput.tsx
  front/src/Apps/common/queries/fragments/bsvhu.ts
  front/src/Pages/Dashboard.tsx
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
Labels: ready for review, ready to merge

#3902 [tra-9990]fix recette bsda collecte dechetterie : conserver les infos de contact saisie par le user
  front/src/form/bsda/stepper/steps/Destination.tsx
Labels: ready for review, fix de recette

#3896 [TRA 15626 fix] Ne pas supprimer l'intermédiaire inopinément
  front/src/Apps/Dashboard/Creation/bsvhu/BsvhuFormSteps.tsx
Labels: ready for review, ready to merge

#3905 [Fix TRA-14396] Le champ createdAt des AnonymousCompany ne devrait pas être rempli pour les anciennes entreprises
  libs/back/prisma/src/migrations/20241219080834_anonymous_company_created_at/migration.sql
  libs/back/prisma/src/migrations/20250113161530_add_anonymous_company_created_at/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#3907 Amélioration du message d'erreur sur la longueur des numéros de plaques sur le bsvhu
  back/src/bsvhu/typeDefs/bsvhu.inputs.graphql
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/refinements.ts
Labels: ready for review, fix de recette

#3897 [TRA 15647 fix] Résolution de problème d'indexation de BSVHU
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/create.ts
  back/src/bsvhu/validation/rules.ts
  back/src/bsvhu/validation/sirenify.ts
  back/src/bsvhu/validation/types.ts
  back/src/companies/sirenify.ts
Labels: ready to merge

#3903 [TRA-15678] Permettre d'ajouter un 0 après la virgule dans la quantité à regrouper d'une Annexe 2
  Changelog.md
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
Labels: ready for review

#3912 Disable Nx cache for prisma generate
  libs/back/prisma/project.json
Labels: ready to merge

#3881 [TRA-15504] Dupliquer le(s) conditionnement(s) et la mention ADR et afficher un message informatif sur le besoin de confirmer, selon le type de BSDD
  Changelog.md
  back/src/bsda/converter.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/typeDefs/bsda.objects.graphql
  back/src/bsdasris/converter.ts
  back/src/bsdasris/edition.ts
  back/src/bsdasris/resolvers/mutations/__tests__/duplicateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/duplicateBsdasri.ts
  back/src/bsdasris/typeDefs/bsdasri.objects.graphql
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsffs/converter.ts
  back/src/bsffs/resolvers/mutations/__tests__/duplicateBsff.integration.ts
  back/src/bsffs/resolvers/mutations/duplicateBsff.ts
  back/src/bsffs/typeDefs/bsff.objects.graphql
  back/src/bspaoh/converter.ts
  back/src/bspaoh/fragments.ts
  back/src/bspaoh/resolvers/mutations/__tests__/duplicateBspaoh.integration.ts
  back/src/bspaoh/resolvers/mutations/duplicate.ts
  back/src/bspaoh/typeDefs/bspaoh.objects.graphql
  back/src/bspaoh/validation/rules.ts
  back/src/bsvhu/converter.ts
  back/src/bsvhu/resolvers/mutations/__tests__/duplicateBsvhu.integration.ts
  back/src/bsvhu/resolvers/mutations/duplicate.ts
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  back/src/forms/__tests__/form-converter.integration.ts
  back/src/forms/converter.ts
  back/src/forms/edition.ts
  back/src/forms/resolvers/mutations/__tests__/duplicateForm.integration.ts
  back/src/forms/resolvers/mutations/duplicateForm.ts
  back/src/forms/typeDefs/bsdd.objects.graphql
  front/src/Apps/common/queries/fragments/bsdd.ts
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/WasteInfo.tsx
  front/src/form/bsdd/utils/initial-state.ts
  libs/back/prisma/src/migrations/20250107141838_add_is_duplicate_of/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#3917 [TRA 15756] Fixes autogenerating siret at company creation
  front/src/Apps/Companies/AccountCompanyAdd/companyAdd/AccountCompanyAddSiret.tsx
Labels: ready for review

#3920 Affichage de l'erreur renvoyée par le serveur dans la page admin d'impersonation
  front/src/admin/user/impersonate.tsx
Labels: ready for review, ready to merge

#3921 Affichage des erreurs API dans l'interface d'admin pour la recherche par BSD
  front/src/admin/bsd/BsdAdmin.tsx
Labels: ready for review

#3916 [TRA 15687] Ajout d'éco-organismes, filtrage des éco-organismes en front
  Changelog.md
  back/src/companies/resolvers/queries/ecoOrganismes.ts
  back/src/companies/typeDefs/company.objects.graphql
  back/src/companies/typeDefs/company.queries.graphql
  front/src/form/bsda/components/eco-organismes/EcoOrganismes.tsx
  front/src/form/bsdasri/components/eco-organismes/EcoOrganismes.tsx
  front/src/form/bsdd/components/eco-organismes/EcoOrganismes.tsx
  libs/back/object-creator/src/main.ts
  libs/back/object-creator/src/objects.ts
  libs/back/prisma/src/migrations/20250116003327_add_handle_bsdd_ecoorganisme/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#3904 [TRA 15455] Adds membership requests to the members page
  back/src/users/resolvers/queries/__tests__/membershipRequest.integration.ts
  back/src/users/resolvers/queries/membershipRequest.ts
  front/src/Apps/Account/AccountMembershipRequest.tsx
  front/src/Apps/Companies/CompanyDetails.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembers.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersRequestModal.tsx
  front/src/Apps/Companies/CompanyMembers/CompanyMembersRequestsList.tsx
  front/src/Apps/Companies/common/queries.ts
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/Apps/routes.ts
  libs/back/mail/src/templates/mustache/membership-request.html
  libs/back/mail/src/templates/mustache/pending-membership-request.html
Labels: ready for review, ready to merge

#3919 TRA-15652 - BSVHU : Ajoute un nouveau type de conditionnement En unités > Identification par numéro de fiche VHU DROMCOM
  Changelog.md
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  back/src/bsvhu/resolvers/mutations/__tests__/createBsvhu.integration.ts
  back/src/bsvhu/typeDefs/bsvhu.enums.graphql
  back/src/bsvhu/validation/__tests__/validation.integration.ts
  back/src/bsvhu/validation/refinements.ts
  front/src/Apps/Dashboard/Creation/bsvhu/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
  libs/back/prisma/src/migrations/20250123083809_vh_identification_type_dromcom/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#3924 [tra-15750]vhu eco-organismes : Ajouter 'ou système individuel'
  back/src/bsvhu/pdf/components/BsvhuPdf.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/steps/EcoOrganism.tsx
  front/src/dashboard/detail/bsvhu/BsvhuDetailContent.tsx
Labels: ready for review, ready to merge

#3923 TRA-15684 Mise à jour des logos du ministère
  apps/doc/src/css/custom.css
  apps/doc/static/img/mte.svg
  front/src/Apps/common/Components/layout/Header.tsx
  package-lock.json
  package.json
Labels: ready for review, ready to merge

#3925 [tra-15780]Corriger Numéro d'achantillon par 'Numéro d'échantillon' à la révision d'une annexe 1
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/Appendix1ProducerRequestRevision.tsx
Labels: ready for review

#3931 [tra-15633]front: ajouter les éco-organismes VHU
  front/src/Apps/Dashboard/Creation/bsvhu/steps/EcoOrganism.tsx
  front/src/Apps/Dashboard/Creation/bsvhu/utils/initial-state.ts
Labels: ready for review, ready to merge

#3914 [TRA-15623 | TRA-15080 | TRA-15697 | TRA-15696] - (BSDD & BSDA) Vérifier le type de profil du courtier et/ou négociant lors dans le formulaire de création et sur le formulaire de demande de révision
  .env.model
  .github/workflows/integration-tests.yml
  Changelog.md
  back/src/__tests__/factories.integration.ts
  back/src/__tests__/factories.ts
  back/src/__tests__/oidc.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/sign.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/update.integration.ts
  back/src/bsda/resolvers/mutations/create.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsda/resolvers/mutations/update.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/validation/helpers.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/common/validation.ts
  back/src/forms/__tests__/recipify.integration.ts
  back/src/forms/recipify.ts
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/__tests__/createFormRevisionRequest.integration.ts
  back/src/forms/resolvers/mutations/__tests__/updateForm.integration.ts
  back/src/forms/resolvers/mutations/createFormRevisionRequest.ts
  back/src/forms/resolvers/mutations/updateForm.ts
  back/src/forms/typeDefs/bsdd.inputs.graphql
  back/src/forms/validation.ts
  front/src/Apps/Dashboard/Components/Recepisse/Recepisse.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsdd/request/BsddRequestRevision.tsx
  front/src/Apps/Dashboard/Components/RevisionRequestList/common/utils/schema.ts
  front/src/Apps/Dashboard/Creation/bsvhu/steps/ActorsList.tsx
  front/src/Apps/Forms/Components/Broker/Broker.tsx
  front/src/Apps/Forms/Components/Broker/FormikBroker.tsx
  front/src/Apps/Forms/Components/Broker/RhfBroker.tsx
  front/src/Apps/Forms/Components/Broker/types.ts
  front/src/Apps/Forms/Components/Broker/useBroker.ts
  front/src/Apps/Forms/Components/IntermediaryList/FormikIntermediaryList.tsx
  front/src/Apps/Forms/Components/Trader/FormikTrader.tsx
  front/src/Apps/Forms/Components/Trader/RhfTrader.tsx
  front/src/Apps/Forms/Components/Trader/Trader.tsx
  front/src/Apps/common/Components/CompanySelectorWrapper/CompanySelectorWrapper.tsx
  front/src/form/bsda/components/intermediaries/IntermediariesSelector.tsx
  front/src/form/bsda/stepper/steps/Destination.tsx
  front/src/form/bsdd/Recipient.tsx
  libs/back/env/src/index.ts
Labels: ready for review, ready to merge

#3922 [tra-15400] [tra-15669] Modales de signatures VHU (reception acceptation | traitement)
  front/src/Apps/Dashboard/Creation/bspaoh/components/Packagings.tsx
  front/src/Apps/Dashboard/Validation/BSPaoh/WorkflowAction/components/Signature.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuOperation.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuReception.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/WasteVhuSummary.tsx
  front/src/Apps/Dashboard/Validation/workflow/Act/ActBsvhuValidation.tsx
  front/src/Apps/Dashboard/dashboardServices.test.ts
  front/src/Apps/Dashboard/dashboardServices.ts
  front/src/Apps/Forms/Components/IdentificationNumbers/IdentificationNumber.tsx
  front/src/Apps/Forms/Components/IdentificationNumbers/identificationNumber.scss
  front/src/Apps/common/Components/OperationModeSelect/RhfOperationModeSelect.tsx
  front/src/Apps/common/queries/company/query.ts
  front/src/dashboard/components/BSDList/BSVhu/WorkflowAction/SignOperation.tsx
  front/src/form/bsvhu/Operation.tsx
Labels: ready for review, ready to merge

#3937 [Hotfix] Modification de l'adresse mail de la DREAL 93 Pays Loire
  libs/shared/constants/src/DREALS.ts
Labels: ready for review

#3932 [TRA-15631] La révision du BSDA permet de modifier le CAP de l'exutoire
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
  front/src/Apps/Dashboard/Components/RevisionRequestList/bsda/request/BsdaRequestRevision.tsx
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#3910 [TRA 15239] Export registre entrant
  .github/workflows/build-and-test.yml
  CONTRIBUTING.md
  Changelog.md
  back/src/bsda/registryV2.ts
  back/src/bsda/repository/bsda/delete.ts
  back/src/bsda/repository/bsda/updateMany.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsdasris/repository/bsdasri/create.ts
  back/src/bsdasris/repository/bsdasri/delete.ts
  back/src/bsdasris/repository/bsdasri/updateMany.ts
  back/src/bsffs/registryV2.ts
  back/src/bsffs/repository/bsff/create.ts
  back/src/bsffs/repository/bsff/delete.ts
  back/src/bsffs/repository/bsff/updateMany.ts
  back/src/bspaoh/registryV2.ts
  back/src/bspaoh/repository/bspaoh/updateMany.ts
  back/src/bsvhu/registryV2.ts
  back/src/bsvhu/repository/bsvhu/delete.ts
  back/src/bsvhu/repository/bsvhu/update.ts
  back/src/bsvhu/repository/bsvhu/updateMany.ts
  back/src/forms/__tests__/compat.integration.ts
  back/src/forms/compat.ts
  back/src/forms/registryV2.ts
  back/src/forms/repository/form/update.ts
  back/src/forms/repository/form/updateMany.ts
  back/src/forms/repository/formRevisionRequest/acceptRevisionRequestApproval.ts
  back/src/forms/types.ts
  back/src/queue/jobs/deleteBsd.ts
  back/src/queue/jobs/indexBsd.ts
  back/src/queue/jobs/processRegistryExport.ts
  back/src/registryV2/columns.ts
  back/src/registryV2/converters.ts
  back/src/registryV2/streams.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/types.ts
  back/src/scripts/bin/rebuildRegistryLookup.ts
  back/src/scripts/bin/reindexPartialInPlace.ts
  docs/RegistryExportV2.md
  front/src/dashboard/registry/MyExports.tsx
  front/src/dashboard/registry/WasteCodeSwitcher.module.scss
  front/src/dashboard/registry/WasteCodeSwitcher.tsx
  libs/back/prisma/src/migrations/20241227002155_registry_lookup_relation_dnd_texs/migration.sql
  libs/back/prisma/src/migrations/20250115004726_registrylookup_optional_wastecode/migration.sql
  libs/back/prisma/src/schema/registry.prisma
  libs/back/registry/src/incomingTexs/database.ts
  libs/back/registry/src/incomingTexs/registry.ts
  libs/back/registry/src/incomingWaste/database.ts
  libs/back/registry/src/incomingWaste/registry.ts
  libs/back/registry/src/index.ts
  libs/back/registry/src/lookup/utils.ts
  libs/back/registry/src/options.ts
  libs/back/registry/src/ssd/constants.ts
  libs/back/registry/src/ssd/database.ts
  libs/back/registry/src/ssd/registry.ts
Labels: ready for review, ready to merge
