Repository MTES-MCT/trackdechets, pull requests merged in 2025-09, with the labels that each got.

#4395 HOTFIX focus trap
  front/src/Apps/common/Components/Modal/Modal.tsx
Labels: ready to merge

#4387 [tra-16616]Harmoniser la hauteur et le positionnement des modales sur bordereau et déclaration
  front/src/scss/Modals.scss
Labels: ready for review

#4389 [tra-17001-tra-17025] fix typo 'Pulvérulents' + add Label for consistence (Other->Autres,...)
  front/src/Apps/Dashboard/Preview/BSDA/BSDAPreviewContent.tsx
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaWork.tsx
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
Labels: ready for review, ready to merge

#4399 [tra-16890]Compléter par défaut la timeline lorsque l'émetteur est un particulier sur les modales de signature BSDA
  front/src/Apps/Dashboard/Validation/Bsda/BsdaJourneySummary.tsx
Labels: ready for review, ready to merge

#4409 [tra-17052]Compléter par défaut la timeline sur la modale de réception et acceptation et traitement d'un BSDA de collecte en déchetterie
  front/src/Apps/Dashboard/Validation/Bsda/BsdaJourneySummary.tsx
Labels: ready for review

#4425 [TRA-16932] Afficher le code de traitement R12 pour les déchets * sur les VHU
  front/src/Apps/Dashboard/Creation/bsvhu/steps/Waste.tsx
Labels: ready for review

#4432 [TRA-16937] Fix recette : Remonter sur l'Aperçu l'Installation de broyage prévisionnelle ajoutée au traitement
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewDestination.tsx
  front/src/Apps/Dashboard/Validation/Bsvhu/SignVhuOperation.tsx
Labels: ready for review, fix de recette

#4433 [TRA-17010] Ajouter une majuscule dans la fenêtre de révision
  front/src/Apps/Dashboard/Components/Revision/RevisionList/revisionList.scss
Labels: ready for review, fix de recette

#4434 [TRA-16999] Corrige le transporteur par défaut dans un BSDA avec multimodal
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
Labels: ready for review, fix de recette

#4427 [Yogosha 30138] Retrait de l'endpoint /ip inutilisé avec une faille de sécurité potentielle
  back/src/server.ts
Labels: ready for review

#4412 [Yogosha 30068] Un membre lambda d'une entreprise ne peut pas refuser une demande de droits d'admin
  back/src/adminRequest/resolvers/mutations/__tests__/refuseAdminRequest.integration.ts
  back/src/adminRequest/resolvers/mutations/utils/refuseAdminRequest.utils.ts
Labels: ready for review

#4396 [TRA-16607] Correction de l'affichage du statut de signature émetteur dans l'Aperçu des BSVHU
  back/src/bsvhu/converter.ts
  back/src/bsvhu/typeDefs/bsvhu.objects.graphql
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewEmitter.tsx
  front/src/Apps/common/queries/fragments/bsvhu.ts
Labels: ready for review

#4440 [TRA 16999] Fixes multimodal BSDA default transporter
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
Labels: ready for review, fix de recette

#4441 [TRA 16284] Updates banner
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review

#4443 [TRA 16999] Fixes BSDA signTransport company update
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
Labels: ready for review, fix de recette

#4401 [TRA 16961] Amélioration du zoom de la carte des parcelles pour éviter la confusion
  Changelog.md
  front/src/form/registry/common/ParcelsVisualizer/ParcelsVisualizer.tsx
Labels: ready for review

#4403 [TRA 16884] déplacement des champs de transfert transfrontalier sur IHM Registre DND entrant
  Changelog.md
  front/src/form/registry/incomingWaste/shape.ts
Labels: ready for review

#4450 Hotfix revision display
  front/src/Apps/Dashboard/Components/Revision/revisionMapper.ts
Labels: ready to merge

#4453 [Hotfix] Envoi d'emails séparés aux entreprises délégantes / délégataires
  apps/cron/src/commands/__tests__/onboarding.helpers.integration.ts
  apps/cron/src/commands/onboarding.helpers.ts
  back/src/registryDelegation/resolvers/mutations/__tests__/createRegistryDelegation.integration.ts
  back/src/registryDelegation/resolvers/mutations/utils/createRegistryDelegation.utils.ts
Labels: ready for review, ready to merge

#4449 [TRA-17101] Afficher un message lorsqu'aucun transporteur n'est renseigné au lieu de "undefined" sur l'aperçu
  front/src/Apps/Dashboard/Preview/BSDA/BSDAPreviewTransport.tsx
  front/src/Apps/Dashboard/Preview/BSVHU/BSVHUPreviewActors.tsx
Labels: ready for review

#4455 [TRA-17185] Ajout d'une taille limite plus stricte aux PDFs d'entreprises anonymes
  back/src/companies/resolvers/mutations/createAnonymousCompanyFromPDF.ts
Labels: ready for review, ready to merge
