Repository MTES-MCT/trackdechets, pull requests merged in 2025-07, with the labels that each got.

#4296 [TRA-16613] La quantité refusée des BSDA s'affiche dans le registre
  back/src/bsda/registryV2.ts
Labels: ready for review

#4303 [TRA 16609] Erreurs de dates de récépissé en français
  Changelog.md
  back/src/companies/validation.ts
Labels: ready for review, ready to merge

#4312 [TRA-16773] Prendre en compte la demande de droits administrateur la plus récente à la complétion du code de vérification
  back/src/adminRequest/resolvers/mutations/utils/acceptAdminRequest.utils.ts
Labels: ready for review

#4321 [hotfix] - Résolution d'un problème de pagination sur les exports exhaustifs
  back/src/queue/jobs/processRegistryExhaustiveExport.ts
Labels: ready for review

#4313 [TRA-16759] Accepter les numéros de parcelles à 4 chiffres
  libs/back/registry/src/shared/__tests__/schemas.test.ts
  libs/back/registry/src/shared/schemas.ts
Labels: ready for review, ready to merge

#4308 [TRA-16173] Ajout du CAP sur la destination d'un DASRI
  back/src/__tests__/factories.ts
  back/src/bsdasris/converter.ts
  back/src/bsdasris/fragments.ts
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
  back/src/bsdasris/pdf/components/FormCompanyFields.tsx
  back/src/bsdasris/registry.ts
  back/src/bsdasris/registryV2.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriSynthesis.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/resolvers/queries/__tests__/bsdasri.integration.ts
  back/src/bsdasris/typeDefs/bsdasri.inputs.graphql
  back/src/bsdasris/typeDefs/bsdasri.objects.graphql
  back/src/bsdasris/validation/refinements.ts
  back/src/bsdasris/validation/rules.ts
  back/src/bsdasris/validation/schema.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  front/src/Apps/common/queries/fragments/bsdasri.ts
  front/src/dashboard/detail/bsdasri/BsdasriDetailContent.tsx
  front/src/form/bsdasri/steps/Destination.tsx
  front/src/form/bsdasri/utils/initial-state.ts
  libs/back/prisma/src/migrations/20250704083402_add_dasri_destination_cap/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#4306 [TRA 16585] Auth: modification de signup/signin pour éviter l'énumération
  Changelog.md
  back/src/__tests__/auth.integration.ts
  back/src/auth/auth.ts
  back/src/users/resolvers/mutations/__tests__/signup.integration.ts
  back/src/users/resolvers/mutations/__tests__/signup.test.ts
  back/src/users/resolvers/mutations/signup.ts
  back/src/users/typeDefs/private/user.mutations.graphql
  front/src/login/mutations.ts
  libs/back/mail/src/templates/index.ts
  libs/back/mail/src/templates/mustache/confirmation-de-compte-existant.html
Labels: ready for review, ready to merge

#4318 Ajout d'une bannière de consentement au suivi, d'une interface de gestion dans les prefs utilisateur et d'un script de suivi Matomo
  Changelog.md
  back/src/common/typeDefs/common.objects.graphql
  back/src/users/resolvers/mutations/__tests__/editProfile.integration.ts
  back/src/users/resolvers/mutations/editProfile.ts
  back/src/users/resolvers/queries/__tests__/me.integration.ts
  back/src/users/typeDefs/private/user.mutations.graphql
  e2e/src/plans/bsvhu/createBsvhu.spec.ts
  front/.env.model
  front/src/App.tsx
  front/src/Apps/Account/AccountInfo/AccountFormChangeTrackingSetting.tsx
  front/src/Apps/Account/AccountInfo/AccountInfo.tsx
  front/src/Apps/Account/accountSchema.ts
  front/src/Apps/common/Components/ConsentBanner/ConsentBanner.tsx
  front/src/Apps/common/Components/layout/Layout.tsx
  front/src/Apps/common/queries/user/userQueries.ts
  front/src/common/contexts/AuthContext.tsx
  front/src/common/tracking/Tracking.tsx
  libs/back/prisma/src/migrations/20250721083713_user_tracking_consent/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review, ready to merge

#4307 Tickets sécu Yogosha
  apps/ui/src/main.ts
  back/src/__tests__/auth.integration.ts
  back/src/common/__tests__/helpers.test.ts
  back/src/common/helpers.ts
  back/src/routers/auth-router.ts
  back/src/server.ts
  back/src/users/__tests__/utils.test.ts
  back/src/users/resolvers/mutations/__tests__/changePassword.integration.ts
  back/src/users/resolvers/mutations/__tests__/changePassword.test.ts
  back/src/users/resolvers/mutations/__tests__/resetPassword.integration.ts
  back/src/users/resolvers/mutations/__tests__/signup.integration.ts
  back/src/users/utils.ts
  e2e/src/utils/user.ts
  front/src/Apps/Account/AccountInfo/AccountFormChangePassword.tsx
  front/src/common/components/PasswordHelper.tsx
Labels: ready for review, ready to merge

#4314 [TRA-16275] À l'export d'un registre, filtrer la liste des codes déchets selon si Terres et sédiments ou Déchets dangereux ou non dangereux est sélectionné
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/WasteCodeSwitcher.module.scss
  front/src/dashboard/registry/WasteCodeSwitcher.tsx
  front/src/form/registry/common/WasteCodeSelector.tsx
Labels: ready for review

#4323 Fix dasri with intermediaries signature
  front/src/Apps/common/queries/dashboard/detailQueries.ts
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasri.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/RouteSignBsdasriSecretCode.tsx
Labels: ready for review

#4325 [TRA-16173] Fix de recette: ajout du CAP dans la BSDCard + dans ES pour les recherches
  back/src/bsdasris/elastic.ts
  front/src/Apps/common/queries/fragments/bsdasri.ts
Labels: ready for review, fix de recette

#4326 [FIX 16491/16657] petits fix de recette Registre/IHM
  apps/ui/src/main.ts
  front/src/form/registry/common/WasteCodeSelector.tsx
Labels: ready to merge

#4317 [tra-16216] Ajout des fichiers d'analyse sur les déclarations TEXS
  .env.model
  .github/workflows/build-and-test.yml
  .github/workflows/e2e.yml
  .github/workflows/integration-tests.yml
  back/src/registryV2/resolvers/Mutation.ts
  back/src/registryV2/resolvers/Query.ts
  back/src/registryV2/resolvers/mutations/addToIncomingTexsRegistry.ts
  back/src/registryV2/resolvers/mutations/createTexsAnalysisFile.ts
  back/src/registryV2/resolvers/queries/registryDownloadTexsAnalysisSignedUrl.ts
  back/src/registryV2/resolvers/queries/registryLookup.ts
  back/src/registryV2/resolvers/queries/registryUploadTexsAnalysisSignedUrl.ts
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  back/src/registryV2/typeDefs/registryV2.mutations.graphql
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  back/src/registryV2/typeDefs/registryV2.objects.imports.graphql
  back/src/registryV2/typeDefs/registryV2.queries.graphql
  front/src/form/registry/common/TexsAnalysisFile.tsx
  front/src/form/registry/incomingTexs/RegistryIncomingTexsForm.tsx
  front/src/form/registry/incomingTexs/shape.ts
  front/src/form/registry/outgoingTexs/RegistryOutgoingTexsForm.tsx
  front/src/form/registry/outgoingTexs/shape.ts
  front/src/form/registry/queries.ts
  libs/back/env/src/index.ts
  libs/back/registry/src/incomingTexs/database.ts
  libs/back/registry/src/incomingTexs/validation/schema.ts
  libs/back/registry/src/outgoingTexs/database.ts
  libs/back/registry/src/outgoingTexs/validation/schema.ts
Labels: ready for review

#4334 Réduction de la taille de l'app + split du bundle
  front/src/Apps/Account/AccountInfo/AccountFormChangePassword.tsx
  front/src/Apps/Dashboard/Components/RhfExtraEuropeanCompanyManualInput/RhfCountrySelector.tsx
  front/src/Apps/common/Components/Filters/Filters.tsx
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/common/components/PasswordHelper.tsx
  front/src/common/countries.json
  front/src/common/validation/schema.ts
  front/src/dashboard/registry/RegistryRoutes.tsx
  front/src/dashboard/registry/myLines/FormContainer.tsx
  front/src/form/registry/common/CountrySelector.tsx
  front/src/form/registry/common/ParcelsVisualizer/ParcelsVisualizer.tsx
  front/src/form/registry/common/ParcelsVisualizer/utils.ts
  front/src/login/Invite.tsx
  front/src/login/PasswordReset.tsx
  front/src/login/Signup.tsx
  front/vite.config.ts
  package-lock.json
  package.json
Labels: ready to merge
