Repository MTES-MCT/trackdechets, pull requests merged in 2025-06, with the labels that each got.

#4216 [tra-16347]fix recette : add mention ADR alert info
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
  front/src/Apps/Forms/Components/TransporterRecepisse/TransporterRecepisse.tsx
  front/src/form/common/components/company/TransporterRecepisseWrapper.tsx
Labels: ready for review, fix de recette

#4218 Mise à jour du Changelog
  Changelog.md
Labels: ready for review

#4212 HOTFIX / Gestion des version ES
  back/integration-tests/helper.ts
  back/src/bsda/elastic.ts
  back/src/bsdasris/elastic.ts
  back/src/bsdasris/resolvers/mutations/createSynthesisBsdasri.ts
  back/src/bsds/indexation/reindexBsdHelpers.ts
  back/src/bsffs/elastic.ts
  back/src/bspaoh/elastic.ts
  back/src/bsvhu/elastic.ts
  back/src/common/elastic.ts
  back/src/forms/elastic.ts
  back/src/queue/jobs/indexBsd.ts
  back/src/queue/producers/elastic.ts
  libs/back/registry/src/import.ts
Labels: ready to merge

#4181 [TRA-16222] - Analyser les erreurs à l'import pour avoir le top 10 des erreurs
  libs/back/registry/project.json
  libs/back/registry/src/scripts/analyzeS3Errors.ts
Labels: ready for review

#4226 [TRA-16338] Correction de la réception & traitement des BSDA dans le cas d'un COLLECTION_2710
  back/src/bsda/machine.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/resolvers/mutations/sign.ts
Labels: ready for review, ready to merge, fix de recette

#4227 fix ajout d'un tiret dans le texte du bandeau
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
Labels: ready for review, ready to merge, fix de recette

#4234 [TRA 16842] Ajout d'un mode lecture seule à l'IHM
  Changelog.md
  apps/doc/docusaurus.config.js
  back/src/registryV2/resolvers/RegistryCompany.ts
  back/src/registryV2/resolvers/RegistryExhaustiveExport.ts
  back/src/registryV2/resolvers/RegistryImportAssociation.ts
  back/src/registryV2/resolvers/RegistryLookup.ts
  back/src/registryV2/resolvers/RegistryV2Export.ts
  back/src/registryV2/resolvers/index.ts
  back/src/registryV2/typeDefs/registryV2.objects.graphql
  front/src/dashboard/registry/MyImports.tsx
  front/src/dashboard/registry/companyImport/FileImportsTable.tsx
  front/src/dashboard/registry/myLines/MyLines.tsx
  front/src/dashboard/registry/shared.tsx
  front/src/form/registry/builder/FormBuilder.tsx
  front/src/form/registry/incomingWaste/RegistryIncomingWasteForm.tsx
  front/src/form/registry/outgoingWaste/RegistryOutgoingWasteForm.tsx
Labels: ready for review

#4239 [Hotfix] Les BSDA legacy avec isSubjectToADR = null devraient pouvoir poursuivre leur workflow
  front/src/form/bsda/stepper/BsdaStepList.tsx
Labels: hotfix, ready for review

#4243 [Hotfix TRA-16639] Un BSDD d'entreposage provisoire devrait pouvoir forward un BSD legacy avec wasteDetailsIsSubjectToADR = null
  back/src/common/subTypes.ts
  back/src/forms/resolvers/mutations/__tests__/markAsResealed.integration.ts
  back/src/forms/validation.ts
Labels: hotfix, ready for review

#4245 [Hotfix TRA-16641] Il ne devrait pas être possible de valider la réception d'un BSDA avec une quantité à zéro
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/validation/refinements.ts
Labels: hotfix, ready for review

#4247 [Hotfix TRA-16652] On devrait pouvoir ajouter une étape d'entreposage provisoire sur un BSDA legacy avec wasteIsSubjectToADR = null
  front/src/form/bsda/stepper/BsdaStepList.tsx
Labels: hotfix, ready for review

#4249 Hotfix: synthesis dasri update
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasriSynthesis.integration.ts
  back/src/bsdasris/validation/refinements.ts
Labels: hotfix, ready for review

#4250 [HOTFIX TRA-16640] Correction de l'état initial des modales de signature BSDA
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaReception.tsx
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
Labels: ready for review, ready to merge

#4254 [Hotfix TRA-16635] Meilleur gestion de isSubjectToADR pour les BSDA de réexpédition
  front/src/form/bsda/components/bsdaPicker/BsdaPicker.tsx
Labels: hotfix, ready for review

#4259 [HOTFIX TRA 16674] - Résolution de problèmes liés aux délégations
  back/src/registryV2/resolvers/mutations/__tests__/addToIncomingTexsRegistry.integration.ts
  back/src/registryV2/resolvers/mutations/genericAddToRegistry.ts
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/form/registry/builder/FormBuilder.tsx
  front/src/form/registry/builder/utils.ts
  front/src/form/registry/common/ReportFor.tsx
  front/src/form/registry/incomingTexs/RegistryIncomingTexsForm.tsx
  front/src/form/registry/incomingWaste/RegistryIncomingWasteForm.tsx
  front/src/form/registry/managed/RegistryManagedForm.tsx
  front/src/form/registry/outgoingTexs/RegistryOutgoingTexsForm.tsx
  front/src/form/registry/outgoingWaste/RegistryOutgoingWasteForm.tsx
  front/src/form/registry/ssd/RegistrySsdForm.tsx
  front/src/form/registry/transported/RegistryTransportedForm.tsx
  libs/back/registry/src/index.ts
  libs/back/registry/src/options.ts
Labels: ready to merge

#4235 Affiche un icone d'éco-organisme sur le composant de selection des dasri à grouper
  Changelog.md
  front/src/form/bsdasri/components/grouping/BsdasriTableGrouping.tsx
  front/src/form/bsdasri/components/grouping/grouping.module.scss
Labels: ready for review, ready to merge

#4220 [TRA-15324] Ajout de nouvelles catégories pour les demandes de révisions
  back/src/bsda/elastic.ts
  back/src/bsdasris/elastic.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsda.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdasri.integration.ts
  back/src/bsds/resolvers/queries/__tests__/bsds.bsdd.integration.ts
  back/src/bsds/resolvers/queries/bsds.ts
  back/src/bsds/typeDefs/private/bsd.inputs.graphql
  back/src/bsffs/elastic.ts
  back/src/bspaoh/elastic.ts
  back/src/bsvhu/elastic.ts
  back/src/common/elastic.ts
  back/src/common/elasticHelpers.ts
  back/src/forms/__tests__/elastic.integration.ts
  back/src/forms/__tests__/elasticHelpers.integration.ts
  back/src/forms/elastic.ts
  back/src/forms/elasticHelpers.ts
  e2e/src/utils/navigation.ts
  front/src/Apps/Dashboard/Components/BsdCard/BsdCard.tsx
  front/src/Apps/Dashboard/Components/BsdCardList/BsdCardList.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/DashboardTabs.tsx
  front/src/Apps/Dashboard/Components/DashboardTabs/useNotificationQueries.tsx
  front/src/Apps/Dashboard/DashboardRoutes.tsx
  front/src/Apps/Dashboard/dashboardUtils.tsx
  front/src/Apps/common/Components/layout/Header.tsx
  front/src/Apps/common/types/commonTypes.ts
  front/src/Apps/common/wordings/dashboard/wordingsDashboard.ts
  front/src/Apps/routes.ts
  front/src/Pages/Dashboard.tsx
  front/src/Pages/Dashboard.utils.tsx
  libs/back/mail/src/templates/mustache/pending-revision-request-admin-details.html
Labels: ready for review

#4269 Correction d'une déclaration de clé en double
  back/src/common/elasticHelpers.ts
Labels: ready for review

#4267 [HOTFIX TRA 16682] résolution de problèmes d'export registre pour délégataires
  front/src/dashboard/registry/ExportModal.tsx
  front/src/dashboard/registry/RegistryCompanySwitcher.tsx
  front/src/form/registry/common/ReportFor.tsx
  front/src/form/registry/outgoingTexs/RegistryOutgoingTexsForm.tsx
  front/src/form/registry/transported/shape.ts
Labels: ready for review

#4240 [TRA-165XX] Résolution de problèmes divers et améliorations de l'IHM
  Changelog.md
  back/src/queue/jobs/__tests__/processRegistryImport.integration.ts
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  back/src/registryV2/typeDefs/registryV2.objects.imports.graphql
  front/src/Apps/common/Components/Combobox/Combobox.tsx
  front/src/form/registry/common/CompanySelector.tsx
  front/src/form/registry/common/EcoOrganismes.tsx
  front/src/form/registry/common/FrenchCompanySelector.tsx
  front/src/form/registry/common/Operation.tsx
  front/src/form/registry/common/OptionalCompanySelector.tsx
  front/src/form/registry/common/TransporterTags.tsx
  front/src/form/registry/common/WasteCodeSelector.tsx
  front/src/form/registry/incomingTexs/RegistryIncomingTexsForm.tsx
  front/src/form/registry/incomingTexs/shape.ts
  front/src/form/registry/incomingWaste/shape.ts
  front/src/form/registry/managed/RegistryManagedForm.tsx
  front/src/form/registry/managed/shape.ts
  front/src/form/registry/outgoingTexs/RegistryOutgoingTexsForm.tsx
  front/src/form/registry/outgoingTexs/shape.ts
  front/src/form/registry/outgoingWaste/shape.ts
  front/src/form/registry/queries.ts
  front/src/form/registry/ssd/RegistrySsdForm.tsx
  front/src/form/registry/ssd/SecondaryWasteCodes.tsx
  front/src/form/registry/ssd/shape.ts
  front/src/form/registry/transported/shape.ts
  libs/back/registry/src/shared/__tests__/schemas.test.ts
  libs/back/registry/src/shared/schemas.ts
  libs/back/registry/src/ssd/validation/index.ts
Labels: ready for review, ready to merge

#4258 [TRA-16364] On ne peut plus ajouter un conditionnement sur un BSDD de tournée dédiée
  back/src/forms/resolvers/mutations/__tests__/createForm.integration.ts
  back/src/forms/resolvers/mutations/createForm.ts
Labels: ready for review, ready to merge

#4265 [TRA-15816] Lorsqu'un exutoire est visé, le TTR ne peut plus renseigner un code de traitement final sur un BSDA initial
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/schema.ts
  back/src/common/operationCodes.ts
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaOperation.tsx
  libs/shared/constants/src/PROCESSING_OPERATIONS.ts
Labels: ready for review

#4273 [HOTFIX BSDA] signature transporteur: passage de la date de prise en charge dans takenOverAt
  front/src/Apps/Dashboard/Validation/Bsda/SignBsdaTransport.tsx
Labels: ready for review, ready to merge

#4231 [TRA-16566] Ajout de limites de caractères quand manquants
  libs/back/registry/src/incomingTexs/validation/schema.ts
  libs/back/registry/src/outgoingTexs/validation/schema.ts
  libs/back/registry/src/outgoingWaste/validation/schema.ts
  libs/back/registry/src/shared/schemas.ts
  libs/back/registry/src/transported/validation/schema.ts
Labels: ready for review

#4261 [tra-16395] - Bordereaux suite et récursivité
  Changelog.md
  back/src/forms/resolvers/mutations/__tests__/markAsProcessed.integration.ts
  back/src/forms/updateAppendix2.ts
Labels: ready for review

#4274 Update authors
  AUTHORS.md
Labels: ready for review

#4246 [TRA-16612] Changes weight on bsda grouping
  front/src/form/bsda/components/bsdaPicker/BsdaPicker.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.test.tsx
  front/src/form/bsdd/components/appendix/Appendix2MultiSelect.tsx
Labels: ready for review, ready to merge

#4278 [TRA-16610] BSDA: ajout de la quantité refusée et la quantité acceptée dans l'e-mail de refus partiel / total
  back/src/bsda/mails/refused.ts
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/updateBsda.integration.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsda/validation/rules.ts
Labels: ready for review, ready to merge
