Repository MTES-MCT/trackdechets, pull requests merged in 2025-05, with the labels that each got.

#4157 [tra-16237]Aligner les champs (léger décalage) sur le tableau de bord
  front/src/Apps/Dashboard/Components/BsdCard/bsdCard.scss
  front/src/Apps/Dashboard/Components/InfoWithIcon/infoWithIcon.scss
Labels: ready for review, fix de recette

#4177 feat(core): amélioration du middleware de logging
  back/src/__tests__/errors.integration.ts
  back/src/__tests__/testClient.ts
  back/src/common/middlewares/__tests__/loggingMiddleware.test.ts
  back/src/common/middlewares/loggingMiddleware.ts
  back/src/common/plugins/gqlInfosPlugin.ts
  back/src/types.ts
Labels: ready for review, ready to merge

#4169 [TRA-15999] Ajout d'un switch pour déclarer si un BSDA est soumis à l'ADR ou non
  back/src/bsda/converter.ts
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/pdf/components/WasteDetails.tsx
  back/src/bsda/registry.ts
  back/src/bsda/resolvers/mutations/__tests__/createBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/typeDefs/bsda.objects.graphql
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsdasris/pdf/components/BsdasriPdf.tsx
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/bsffs/pdf/BsffPdf.tsx
  back/src/forms/pdf/components/BsddPdf.tsx
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/common/components/EstimatedQuantityTooltip.tsx
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  front/src/form/bsda/stepper/initial-state.ts
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
  libs/back/prisma/src/migrations/20250505075550_bsda_waste_is_subject_to_adr/migration.sql
  libs/back/prisma/src/schema/schema.prisma
  libs/shared/constants/src/adrHelpers.ts
Labels: ready for review, ready to merge

#4184 Divers fix
  back/src/companies/resolvers/mutations/createCompany.ts
  back/src/companies/resolvers/queries/__tests__/companyPrivateInfos.integration.ts
  back/src/companies/resolvers/queries/companyInfos.ts
  back/src/companies/sirenify.ts
  front/src/Apps/common/queries/company/query.ts
  libs/back/registry/src/import.ts
  libs/back/registry/src/transformers.ts
  libs/back/registry/src/utf8Transformer.ts
Labels: ready for review

#4174 [tra-16396]Mettre à jour les textes sur la page de choix d'établissement à créer
  front/src/Apps/Companies/AccountCompanyOrientation.tsx
Labels: ready for review

#4190 FIX Scalingo - Réduction du nombre de fichiers dans le bundle
  front/src/Apps/common/Components/layout/LayoutContainer.tsx
  front/src/dashboard/components/BSDList/BSDa/WorkflowAction/TransporterInfoEdit.tsx
  front/src/dashboard/components/BSDList/BSDasri/BSDasriActions/UpdateBsdasriTransporterPlates.tsx
  front/src/dashboard/components/BSDList/BSDasri/WorkflowAction/PartialForms.tsx
  front/src/dashboard/components/BSDList/BSFF/BsffActions/UpdateTransporterPlates.tsx
  front/src/form/bsda/stepper/BsdaStepList.tsx
  front/src/form/bsda/stepper/steps/Transport.tsx
  front/src/form/bsda/stepper/steps/WasteInfo.tsx
  front/src/form/bsdasri/BsdasriStepList.tsx
  front/src/form/bsdasri/steps/Transport.tsx
  front/src/form/bsdd/StepList.tsx
  front/src/form/bsdd/components/parcel-number/ParcelNumber.tsx
  front/src/form/bsff/BsffStepList.tsx
  front/vite.config.ts
Labels: ready for review, ready to merge

#4208 Changement d'email DREAL
  libs/shared/constants/src/DREALS.ts
Labels: ready to merge

#4150 [TRA-15343] Ajout d'un nouvel endpoint optionnel pour signer la réception d'un BSDA indépendemment du traitement
  apps/doc/docs/reference/statuts/bsda.mdx
  back/src/bsda/converter.ts
  back/src/bsda/examples/fixtures.ts
  back/src/bsda/examples/steps/signBsda.ts
  back/src/bsda/examples/workflows/collecteChantier.ts
  back/src/bsda/machine.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/signBsda.integration.ts
  back/src/bsda/resolvers/mutations/sign.ts
  back/src/bsda/typeDefs/bsda.enums.graphql
  back/src/bsda/typeDefs/bsda.mutations.graphql
  back/src/bsda/validation/constants.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/scripts/bin/bsdTemplates/emptyPdfData.ts
  back/src/scripts/bin/bsdTemplates/index.ts
  front/src/dashboard/components/BSDList/BSDa/index.tsx
  libs/back/prisma/src/migrations/20250425124307_bsda_add_reception_step/migration.sql
  libs/back/prisma/src/schema/schema.prisma
  libs/shared/constants/src/statuses.ts
Labels: ready for review

#4209 [TRA-16018] Le nombre de conditionnements du BSDA apparaît dans le registre V2
  back/src/bsda/__tests__/registryV2.integration.ts
  back/src/bsda/registryV2.ts
Labels: ready for review

#4196 [TRA-16446] Ajout de la quantité refusée sur le BSDA
  back/src/bsda/__tests__/registry.integration.ts
  back/src/bsda/converter.ts
  back/src/bsda/pdf/components/BsdaPdf.tsx
  back/src/bsda/registry.ts
  back/src/bsda/repository/revisionRequest/accept.ts
  back/src/bsda/resolvers/BsdaRevisionRequest.ts
  back/src/bsda/resolvers/mutations/__tests__/duplicateBsda.integration.ts
  back/src/bsda/resolvers/mutations/__tests__/updateBsda.integration.ts
  back/src/bsda/resolvers/mutations/duplicate.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/createRevisionRequest.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/__tests__/submitRevisionRequestApproval.integration.ts
  back/src/bsda/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsda/typeDefs/bsda.inputs.graphql
  back/src/bsda/typeDefs/bsda.objects.graphql
  back/src/bsda/utils.ts
  back/src/bsda/validation/__tests__/validation.integration.ts
  back/src/bsda/validation/helpers.ts
  back/src/bsda/validation/refinements.ts
  back/src/bsda/validation/rules.ts
  back/src/bsda/validation/schema.ts
  back/src/bsds/resolvers/mutations/utils/clone.utils.ts
  back/src/common/__tests__/wasteQuantities.test.ts
  back/src/common/wasteQuantities.ts
  back/src/forms/helpers/bsddWasteQuantities.ts
  front/src/Apps/common/queries/fragments/bsda.ts
  front/src/dashboard/detail/bsda/BsdaDetailContent.tsx
  libs/back/prisma/src/migrations/20250527070507_add_bsda_quantity_refused/migration.sql
  libs/back/prisma/src/schema/schema.prisma
Labels: ready for review

#4192 Cacher table d'export si elle est vide
  front/src/dashboard/registry/MyExports.tsx
Labels: ready for review, ready to merge

#4194 [TRA 16457] Passage des limites de date à -18 mois sur les registres
  Changelog.md
  back/src/registryV2/typeDefs/registryV2.inputs.graphql
  front/src/form/registry/builder/FormTab.tsx
  libs/back/registry/src/shared/schemas.ts
  libs/shared/constants/src/VALIDATION.ts
Labels: ready for review, ready to merge

#4205 Refactoring du système de validation Dasri (Zod)
  Pipfile
  apps/doc/docs/reference/validation/bsda.md
  apps/doc/docs/reference/validation/bsdasri.md
  back/src/bsda/validation/__tests__/rules.test.ts
  back/src/bsda/validation/transformers.ts
  back/src/bsdasris/__tests__/edition.integration.ts
  back/src/bsdasris/__tests__/edition.test.ts
  back/src/bsdasris/__tests__/factories.ts
  back/src/bsdasris/__tests__/validation.integration.ts
  back/src/bsdasris/converter.ts
  back/src/bsdasris/database.ts
  back/src/bsdasris/edition.ts
  back/src/bsdasris/resolvers/BsdasriMetadata.ts
  back/src/bsdasris/resolvers/Metadata.ts
  back/src/bsdasris/resolvers/index.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriEcoOrganisme.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriGrouping.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/createBsdasriSynthesis.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/publishBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriEmission.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriOperation.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriTransport.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/signBsdasriTransportDirectTakeover.integration.ts
  back/src/bsdasris/resolvers/mutations/__tests__/updateBsdasri.integration.ts
  back/src/bsdasris/resolvers/mutations/createBsdasri.ts
  back/src/bsdasris/resolvers/mutations/createSynthesisBsdasri.ts
  back/src/bsdasris/resolvers/mutations/publishBsdasri.ts
  back/src/bsdasris/resolvers/mutations/revisionRequest/createRevisionRequest.ts
  back/src/bsdasris/resolvers/mutations/signBsdasri.ts
  back/src/bsdasris/resolvers/mutations/updateBsdasri.ts
  back/src/bsdasris/resolvers/mutations/updateSimpleBsdasri.ts
  back/src/bsdasris/resolvers/mutations/updateSynthesisBsdasri.ts
  back/src/bsdasris/resolvers/mutations/utils.ts
  back/src/bsdasris/validation.ts
  back/src/bsdasris/validation/__tests__/rules.test.ts
  back/src/bsdasris/validation/__tests__/validation.integration.ts
  back/src/bsdasris/validation/constants.ts
  back/src/bsdasris/validation/helpers.ts
  back/src/bsdasris/validation/index.ts
  back/src/bsdasris/validation/recipify.ts
  back/src/bsdasris/validation/refinements.ts
  back/src/bsdasris/validation/revisionSchema.ts
  back/src/bsdasris/validation/rules.ts
  back/src/bsdasris/validation/schema.ts
  back/src/bsdasris/validation/sirenify.ts
  back/src/bsdasris/validation/transformers.ts
  back/src/bsdasris/validation/types.ts
  back/src/bsvhu/validation/schema.ts
  back/src/common/validation/zod/refinement.ts
  back/src/registryV2/typeDefs/registryV2.queries.graphql
  libs/shared/constants/src/DASRI_CONSTANTS.ts
  scripts/validation-doc.js
Labels: ready for review
